"""Autotune Helion attention kernels for one shape and check in the Triton.

Usage:
    python tools/generate.py --batch 2 --seqlen 1024 --nheads 32 --head-dim 64 \
        --dtype bf16 [--causal] [--nheads-kv 8] [--seqlen-k 1024] \
        [--backward | --varlen]

The emitted module under ``helion_attention/kernels/`` is Helion's own output
with small mechanical substitutions applied, so that the runtime package needs
only ``torch`` and ``triton``.
"""

from __future__ import annotations

import argparse
import ast
import fcntl
import importlib
from importlib.metadata import version as package_version
import json
import math
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Callable
from typing import TYPE_CHECKING

import torch

REPO_ROOT = Path(__file__).resolve().parent.parent
KERNELS_DIR = REPO_ROOT / "helion_attention" / "kernels"
MANIFEST = KERNELS_DIR / "manifest.json"

sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "tools"))

DTYPES = {"bf16": torch.bfloat16, "fp16": torch.float16}
PERSISTENT_CAUSAL_16K_KEY = (
    "b1_sq16384_sk16384_hq16_hkv16_d128_bf16_causal"
)
SPLIT_KV_DECODE_16K_KEY = "b1_sq1_sk16384_hq32_hkv8_d128_bf16_causal"
SPLIT_KV_DECODE_SPLITS = 8
AUTOTUNE_ACCEPTANCE_REPEAT = 100
MIN_CANDIDATE_SPEEDUP = 0.02

if TYPE_CHECKING:
    from helion_attention._shape import AttnShape


def select_dense_kernel_name(spec: "AttnShape") -> str:
    """Choose a Helion source without applying shape-specific configs broadly."""
    if spec.key == PERSISTENT_CAUSAL_16K_KEY:
        return "causal_attention_bshd_16k"
    if spec.key == SPLIT_KV_DECODE_16K_KEY:
        return "decode_attention_bshd_split_kv"
    return "causal_attention_bshd" if spec.causal else "attention_bshd"


def nonpersistent_decode_config(config):  # noqa: ANN001, ANN201
    """Keep decode's small head grid out of persistent launch schedules."""
    return None if config.pid_type.startswith("persistent_") else config


_HEADER = '''"""Generated by Helion, checked in as plain Triton. Do not edit by hand.

Regenerate with:
    {command}

{description}

{provenance}
"""

'''

_SUBSTITUTIONS = (
    ("import helion\n", ""),
    ("import helion.language as hl\n", ""),
    (": hl.constexpr", ""),
    (
        "from helion.runtime import default_launcher as _default_launcher",
        "from .._launcher import default_launcher as _default_launcher\n"
        "from .._runtime import get_num_sm\n"
        "from .._runtime import set_triton_allocator",
    ),
    ("helion.runtime.set_triton_allocator()", "set_triton_allocator()"),
    ("helion.runtime.get_num_sm(", "get_num_sm("),
)


def strip_helion(code: str) -> str:
    """Rewrite Helion's generated module into a Helion-free one."""
    for needle, replacement in _SUBSTITUTIONS:
        code = code.replace(needle, replacement)
    leftover = re.findall(r"^.*(?:\bhelion\b|_source_module).*$", code, flags=re.MULTILINE)
    leftover = [line for line in leftover if not line.lstrip().startswith("#")]
    if leftover:
        raise RuntimeError("unhandled Helion reference in generated code:\n" + "\n".join(leftover))
    return code


def rename_entry_point(
    code: str, generated_name: str, stable_name: str = "attention"
) -> str:
    """Expose a generated host wrapper under a stable runtime name."""
    pattern = rf"^def {re.escape(generated_name)}\("
    if not re.search(pattern, code, flags=re.MULTILINE):
        raise RuntimeError(f"generated code has no `def {generated_name}(`")
    return re.sub(
        pattern, f"def {stable_name}(", code, count=1, flags=re.MULTILINE
    )


def namespace_generated_constants(code: str, prefix: str) -> str:
    """Keep module-level constexpr names distinct when composing two kernels."""
    names = re.findall(r"^(_[A-Z][A-Z0-9_]*)\s*=", code, flags=re.MULTILINE)
    for name in names:
        code = re.sub(rf"\b{re.escape(name)}\b", f"_{prefix}{name}", code)
    return code


def merge_generated_modules(*modules: str) -> str:
    """Combine standalone Helion outputs under one future import."""
    bodies = []
    for module in modules:
        first, body = module.split("\n", 1)
        if first != "from __future__ import annotations":
            raise RuntimeError("generated module has an unexpected header")
        bodies.append(body)
    return "from __future__ import annotations\n" + "\n".join(bodies)


_SPLIT_KV_DECODE_ENTRY_POINT = f'''
from .._launcher import launcher_context as _launcher_context

def attention(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, sm_scale: float, *, _launcher=_default_launcher):
    num_splits = {SPLIT_KV_DECODE_SPLITS}
    partial_acc = torch.empty(
        (q.size(0), q.size(2), num_splits, 1, q.size(3)),
        dtype=torch.float32,
        device=q.device,
    )
    partial_stats = torch.empty(
        (q.size(0), q.size(2), 2, num_splits, 1),
        dtype=torch.float32,
        device=q.device,
    )
    out = torch.empty_like(q)
    with _launcher_context(q.device, _launcher) as launch:
        _attention_split_kv_partials(
            q, k, v, partial_acc, partial_stats, sm_scale, _launcher=launch
        )
        return _attention_split_kv_combine(
            partial_acc, partial_stats, out, _launcher=launch
        )
'''


def build_inputs(spec: "AttnShape") -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, float]:
    generator = torch.Generator(device="cuda").manual_seed(0)

    def rand(seqlen: int, nheads: int) -> torch.Tensor:
        return torch.randn(
            (spec.batch, seqlen, nheads, spec.head_dim),
            device="cuda",
            dtype=spec.dtype,
            generator=generator,
        )

    q = rand(spec.seqlen_q, spec.nheads_q)
    k = rand(spec.seqlen_k, spec.nheads_kv)
    v = rand(spec.seqlen_k, spec.nheads_kv)
    return q, k, v, 1.0 / math.sqrt(spec.head_dim)


def varlen_lengths(batch: int, maximum: int, *, reverse: bool = False) -> list[int]:
    """Deterministic ragged lengths that include the declared maximum."""
    lengths = [max(1, maximum * (batch - index) // batch) for index in range(batch)]
    return list(reversed(lengths)) if reverse else lengths


def build_varlen_inputs(
    spec: "AttnShape",
) -> tuple[
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    int,
    int,
    float,
    bool,
]:
    """Packed autotuning inputs with unequal per-sequence Q/K lengths."""
    generator = torch.Generator(device="cuda").manual_seed(0)
    lengths_q = varlen_lengths(spec.batch, spec.seqlen_q)
    lengths_k = varlen_lengths(spec.batch, spec.seqlen_k, reverse=True)

    def cumulative(lengths: list[int]) -> torch.Tensor:
        values = [0]
        for length in lengths:
            values.append(values[-1] + length)
        return torch.tensor(values, dtype=torch.int32, device="cuda")

    q = torch.randn(
        (sum(lengths_q), spec.nheads_q, spec.head_dim),
        device="cuda",
        dtype=spec.dtype,
        generator=generator,
    )
    k = torch.randn(
        (sum(lengths_k), spec.nheads_kv, spec.head_dim),
        device="cuda",
        dtype=spec.dtype,
        generator=generator,
    )
    v = torch.randn(
        k.shape,
        device="cuda",
        dtype=spec.dtype,
        generator=generator,
    )
    return (
        q,
        k,
        v,
        cumulative(lengths_q),
        cumulative(lengths_k),
        spec.seqlen_q,
        spec.seqlen_k,
        1.0 / math.sqrt(spec.head_dim),
        spec.causal,
    )


def build_paged_inputs(
    spec: "AttnShape", page_size: int
) -> tuple[
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    int,
    int,
    float,
    bool,
]:
    """Packed-query/paged-cache inputs with deliberately reordered pages."""
    generator = torch.Generator(device="cuda").manual_seed(0)
    lengths_q = varlen_lengths(spec.batch, spec.seqlen_q, reverse=True)
    lengths_k = varlen_lengths(spec.batch, spec.seqlen_k)

    def cumulative(lengths: list[int]) -> torch.Tensor:
        values = [0]
        for length in lengths:
            values.append(values[-1] + length)
        return torch.tensor(values, dtype=torch.int32, device="cuda")

    # vLLM splits Q from a packed projection, so its token stride can exceed
    # heads * head_dim even though the two trailing dimensions are dense.
    q_storage = torch.randn(
        (
            sum(lengths_q),
            (spec.nheads_q + 2 * spec.nheads_kv) * spec.head_dim,
        ),
        device="cuda",
        dtype=spec.dtype,
        generator=generator,
    )
    q = q_storage[:, : spec.nheads_q * spec.head_dim].view(
        sum(lengths_q), spec.nheads_q, spec.head_dim
    )
    blocks_per_request = [
        (length + page_size - 1) // page_size for length in lengths_k
    ]
    total_blocks = sum(blocks_per_request) + 3
    # This is vLLM's real cache contract: logical [blocks, heads, page, 2*dim]
    # followed by transpose(1, 2) and a K/V split of the content dimension.
    kv_cache = torch.zeros(
        (total_blocks, spec.nheads_kv, page_size, 2 * spec.head_dim),
        device="cuda",
        dtype=spec.dtype,
    )
    k, v = kv_cache.transpose(1, 2).split(spec.head_dim, dim=-1)
    block_table = torch.zeros(
        (spec.batch, (spec.seqlen_k + page_size - 1) // page_size),
        device="cuda",
        dtype=torch.int32,
    )
    next_physical = total_blocks - 1
    for request, (length, request_blocks) in enumerate(
        zip(lengths_k, blocks_per_request)
    ):
        contiguous_k = torch.randn(
            (length, spec.nheads_kv, spec.head_dim),
            device="cuda",
            dtype=spec.dtype,
            generator=generator,
        )
        contiguous_v = torch.randn(
            contiguous_k.shape,
            device="cuda",
            dtype=spec.dtype,
            generator=generator,
        )
        for logical_block in range(request_blocks):
            physical_block = next_physical
            next_physical -= 1
            block_table[request, logical_block] = physical_block
            start = logical_block * page_size
            stop = min(start + page_size, length)
            k[physical_block, : stop - start] = contiguous_k[start:stop]
            v[physical_block, : stop - start] = contiguous_v[start:stop]

    return (
        q,
        k,
        v,
        cumulative(lengths_q),
        torch.tensor(lengths_k, dtype=torch.int32, device="cuda"),
        block_table,
        spec.seqlen_q,
        spec.seqlen_k,
        1.0 / math.sqrt(spec.head_dim),
        spec.causal,
    )


def reference(q, k, v, sm_scale, causal):  # noqa: ANN001, ANN201
    mask = None
    if causal:
        row = torch.arange(q.size(1), device=q.device)[:, None]
        col = torch.arange(k.size(1), device=q.device)[None, :]
        mask = col <= row + k.size(1) - q.size(1)
    return torch.nn.functional.scaled_dot_product_attention(
        q.transpose(1, 2).float(),
        k.transpose(1, 2).float(),
        v.transpose(1, 2).float(),
        scale=sm_scale,
        attn_mask=mask,
        enable_gqa=q.size(2) != k.size(2),
    ).transpose(1, 2)


def reference_gradients(
    q: torch.Tensor,
    k: torch.Tensor,
    v: torch.Tensor,
    grad_out: torch.Tensor,
    sm_scale: float,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Compute the generation-time backward oracle with fp32 SDPA."""
    with torch.enable_grad():
        q_ref = q.float().detach().requires_grad_()
        k_ref = k.float().detach().requires_grad_()
        v_ref = v.float().detach().requires_grad_()
        out_ref = reference(q_ref, k_ref, v_ref, sm_scale, False)
        grads = torch.autograd.grad(
            out_ref,
            (q_ref, k_ref, v_ref),
            grad_out.float(),
        )
        return grads[0], grads[1], grads[2]


def config_dict(config) -> dict[str, object]:  # noqa: ANN001
    """Return JSON-compatible arguments that reconstruct a ``helion.Config``."""
    if hasattr(config, "to_json"):
        value = json.loads(config.to_json())
    else:
        value = dict(config)
    if not isinstance(value, dict):
        raise TypeError("Helion config serialization did not produce an object")
    return value


def render_helion_config(config: dict[str, object]) -> str:
    """Render structured config arguments as a copyable constructor."""
    arguments = ", ".join(
        f"{name}={value!r}" for name, value in sorted(config.items())
    )
    return f"helion.Config({arguments})"


def make_provenance(
    *,
    helion_version: str,
    selection: str,
    configs: list[tuple[str, object]],
    wall_time_seconds: float,
    measured_time_ms: float,
    rejected_candidate: tuple[str, object, float] | None = None,
) -> dict[str, object]:
    """Build the stable, JSON-compatible provenance schema."""
    if selection not in {"autotuned", "fixed", "incumbent"}:
        raise ValueError(f"unknown config selection mode: {selection}")
    if not configs:
        raise ValueError("at least one Helion config is required")
    if wall_time_seconds < 0 or measured_time_ms <= 0:
        raise ValueError("provenance timings must be non-negative and non-zero")
    if rejected_candidate is not None and selection != "incumbent":
        raise ValueError("only retained incumbents can record a rejected candidate")
    provenance: dict[str, object] = {
        "helion_version": helion_version,
        "selection": selection,
        "configs": [
            {"kernel": kernel_name, "config": config_dict(config)}
            for kernel_name, config in configs
        ],
        "autotuning_wall_time_seconds": round(wall_time_seconds, 3),
        "measured_time_ms": round(measured_time_ms, 6),
    }
    if rejected_candidate is not None:
        kernel_name, config, candidate_time_ms = rejected_candidate
        if candidate_time_ms <= 0:
            raise ValueError("the rejected candidate timing must be positive")
        provenance["rejected_candidate"] = {
            "kernel": kernel_name,
            "config": config_dict(config),
            "measured_time_ms": round(candidate_time_ms, 6),
        }
    return provenance


def format_provenance(provenance: dict[str, object]) -> str:
    """Format manifest provenance for a generated module docstring."""
    configs = provenance["configs"]
    assert isinstance(configs, list)
    lines = [
        "Autotuning provenance:",
        f"    Helion version: {provenance['helion_version']}",
        f"    Config selection: {provenance['selection']}",
        "    Autotuning wall time: "
        f"{float(provenance['autotuning_wall_time_seconds']):.3f} s",
        f"    Measured time: {float(provenance['measured_time_ms']):.6f} ms",
    ]
    for item in configs:
        assert isinstance(item, dict)
        label = "Config" if len(configs) == 1 else f"Config ({item['kernel']})"
        config = item["config"]
        assert isinstance(config, dict)
        lines.append(f"    {label}: {render_helion_config(config)}")
    rejected = provenance.get("rejected_candidate")
    if rejected is not None:
        assert isinstance(rejected, dict)
        rejected_config = rejected["config"]
        assert isinstance(rejected_config, dict)
        lines.extend(
            [
                "    Rejected candidate time: "
                f"{float(rejected['measured_time_ms']):.6f} ms",
                "    Rejected candidate: " f"{render_helion_config(rejected_config)}",
            ]
        )
    return "\n".join(lines)


def provenance_config(
    provenance: dict[str, object] | None, kernel_name: str
) -> dict[str, object] | None:
    """Return the incumbent config for ``kernel_name`` when provenance has one."""
    if provenance is None:
        return None
    configs = provenance.get("configs")
    if not isinstance(configs, list):
        return None
    for item in configs:
        if not isinstance(item, dict) or item.get("kernel") != kernel_name:
            continue
        config = item.get("config")
        if isinstance(config, dict):
            return config
    return None


def candidate_is_faster(
    incumbent_time_ms: float,
    candidate_time_ms: float,
    *,
    minimum_speedup: float = MIN_CANDIDATE_SPEEDUP,
) -> bool:
    """Require a measurable win before replacing a checked-in executable."""
    if incumbent_time_ms <= 0 or candidate_time_ms <= 0:
        raise ValueError("acceptance timings must be positive")
    if not 0 <= minimum_speedup < 1:
        raise ValueError("minimum speedup must be in [0, 1)")
    return candidate_time_ms < incumbent_time_ms * (1.0 - minimum_speedup)


def seed_incumbent_config(kernel, config: dict[str, object]):  # noqa: ANN001, ANN201
    """Put the checked-in config in Helion's initial search population."""
    from helion import Config

    incumbent = Config(**config)
    seeds = kernel.settings.autotune_seed_configs
    if seeds is None:
        existing = []
    elif isinstance(seeds, (Config, dict)):
        existing = [seeds]
    else:
        existing = list(seeds)
    if not any(config_dict(seed) == config for seed in existing):
        existing.insert(0, incumbent)
    kernel.settings.autotune_seed_configs = existing
    return incumbent


def run_with_provenance(
    kernel,  # noqa: ANN001
    args: tuple[object, ...],
    *,
    helion_version: str,
    incumbent_provenance: dict[str, object] | None = None,
    incumbent: Callable[[], object] | None = None,
):  # noqa: ANN201
    """Select a config, run the kernel, and capture tuning provenance."""
    from helion.autotuner.benchmarking import do_bench
    from helion.autotuner.benchmarking import interleaved_bench
    from helion.autotuner.metrics import register_post_autotune_hook
    from helion.autotuner.metrics import remove_post_autotune_hook

    if (incumbent_provenance is None) != (incumbent is None):
        raise ValueError("incumbent provenance and runner must be provided together")
    incumbent_config = None
    if len(kernel.configs) != 1 and incumbent_provenance is not None:
        incumbent_config_dict = provenance_config(incumbent_provenance, kernel.name)
        if incumbent_config_dict is not None:
            incumbent_config = seed_incumbent_config(kernel, incumbent_config_dict)

    bound = kernel.bind(args)
    if len(kernel.configs) == 1:
        config = kernel.configs[0]
        result = bound(*args)
        measured_time_ms = float(
            do_bench(lambda: bound(*args), return_mode="mean")
        )
        provenance = make_provenance(
            helion_version=helion_version,
            selection="fixed",
            configs=[(kernel.name, config)],
            wall_time_seconds=0.0,
            measured_time_ms=measured_time_ms,
        )
        return result, provenance

    captured_metrics = []
    capture_metrics = captured_metrics.append
    register_post_autotune_hook(capture_metrics)
    started = time.perf_counter()
    try:
        # Generation is the authoritative search for a checked-in artifact. Do
        # not silently substitute a local cache hit whose original wall time
        # and winning measurement are unavailable.
        config = bound.autotune(args, force=not kernel.configs)
    finally:
        wall_time_seconds = time.perf_counter() - started
        remove_post_autotune_hook(capture_metrics)
    if len(captured_metrics) != 1:
        raise RuntimeError(
            "Helion did not report exactly one set of autotuning metrics"
        )
    metrics = captured_metrics[0]
    selection = "autotuned"
    selected_config = config
    rejected_candidate = None
    if incumbent_config is not None:
        assert incumbent is not None
        incumbent_time_ms, candidate_time_ms = interleaved_bench(
            [incumbent, lambda: bound(*args)],
            repeat=AUTOTUNE_ACCEPTANCE_REPEAT,
            desc="validating autotuned candidate against incumbent",
        )
        if candidate_is_faster(incumbent_time_ms, candidate_time_ms):
            measured_time_ms = candidate_time_ms
            result = bound(*args)
        else:
            selection = "incumbent"
            selected_config = incumbent_config
            measured_time_ms = incumbent_time_ms
            result = incumbent()
            rejected_candidate = (kernel.name, config, candidate_time_ms)
            print(
                "retaining incumbent: candidate "
                f"{candidate_time_ms:.6f} ms vs incumbent "
                f"{incumbent_time_ms:.6f} ms",
                flush=True,
            )
    else:
        measured_time_ms = float(metrics.best_perf_ms)
        result = bound(*args)
    provenance = make_provenance(
        helion_version=helion_version,
        selection=selection,
        configs=[(kernel.name, selected_config)],
        wall_time_seconds=wall_time_seconds,
        measured_time_ms=measured_time_ms,
        rejected_candidate=rejected_candidate,
    )
    return result, provenance


def build_module(
    code: str,
    *,
    command: str,
    description: str,
    spec_fields: dict[str, object],
    provenance: dict[str, object],
) -> str:
    """Add the checked-in module header and shape metadata to Helion output."""
    spec_block = (
        "KERNEL_SPEC = {\n"
        + "".join(f"    {name!r}: {value!r},\n" for name, value in spec_fields.items())
        + "}\n\n"
    )
    header = _HEADER.format(
        command=command,
        description=description,
        provenance=format_provenance(provenance),
    )
    body = code.split("\n", 1)
    assert body[0] == "from __future__ import annotations"
    return header + body[0] + "\n\n" + spec_block + body[1]


def refresh_module_provenance(module: str, provenance: dict[str, object]) -> str:
    """Replace only the generated header, preserving incumbent executable code."""
    parsed = ast.parse(module)
    if not parsed.body or not isinstance(parsed.body[0], ast.Expr):
        raise ValueError("generated module has no leading docstring")
    value = parsed.body[0].value
    if not isinstance(value, ast.Constant) or not isinstance(value.value, str):
        raise ValueError("generated module has no leading docstring")
    if parsed.body[0].end_lineno is None:
        raise ValueError("generated module docstring has no source location")
    description = value.value.split("\n\nAutotuning provenance:", 1)[0]
    suffix = "".join(
        module.splitlines(keepends=True)[parsed.body[0].end_lineno :]
    ).lstrip("\n")
    return f'"""{description}\n\n{format_provenance(provenance)}\n"""\n\n' + suffix


def manifest_entry(key: str, section: str = "kernels") -> dict[str, object] | None:
    """Read one manifest entry while excluding concurrent manifest writers."""
    if not MANIFEST.exists():
        return None
    with MANIFEST.open() as handle:
        fcntl.flock(handle, fcntl.LOCK_SH)
        contents = handle.read()
        payload = json.loads(contents) if contents else {"kernels": []}
    for item in payload.get(section, []):
        if item["key"] == key:
            return item
    return None


def load_incumbent_runner(
    kernel_key: str,
    entry_point: str,
    args: tuple[object, ...],
    *,
    backward: bool = False,
) -> Callable[[], object]:
    """Load the exact checked-in executable used for acceptance benchmarking."""
    suffix = "_backward" if backward else ""
    module_name = f"helion_attention.kernels.{kernel_key}{suffix}"
    importlib.invalidate_caches()
    module = importlib.import_module(module_name)
    function = getattr(module, entry_point)
    return lambda: function(*args)


_ANY_MANIFEST_ENTRY = object()


def _replace_manifest_entry(
    *,
    key: str,
    replacement: dict[str, object] | None,
    section: str,
    expected: object = _ANY_MANIFEST_ENTRY,
) -> tuple[dict[str, object] | None, bool]:
    """Atomically replace one key, optionally only if its current value matches."""
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.touch(exist_ok=True)
    with MANIFEST.open("r+") as handle:
        fcntl.flock(handle, fcntl.LOCK_EX)
        handle.seek(0)
        contents = handle.read()
        payload = json.loads(contents) if contents else {"kernels": []}
        items = payload.get(section, [])
        previous = next((item for item in items if item["key"] == key), None)
        if expected is not _ANY_MANIFEST_ENTRY and previous != expected:
            return previous, False
        updated = [item for item in items if item["key"] != key]
        if replacement is not None:
            updated.append(replacement)
        updated.sort(key=lambda item: item["key"])
        payload[section] = updated
        handle.seek(0)
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")
        handle.truncate()
        handle.flush()
        return previous, True


def upsert_manifest(
    entry: dict[str, object], section: str = "kernels"
) -> dict[str, object] | None:
    """Install one entry and return the value replaced under the manifest lock."""
    # generate_all.py has one process per GPU. Lock the shared manifest while
    # reading and rewriting it so two shapes that finish together cannot drop
    # each other's entries or observe a partially-written JSON document.
    previous, updated = _replace_manifest_entry(
        key=str(entry["key"]), replacement=entry, section=section
    )
    assert updated
    return previous


def rollback_manifest_entry(
    failed_entry: dict[str, object],
    previous_entry: dict[str, object] | None,
    section: str = "kernels",
) -> bool:
    """Restore one failed key without overwriting unrelated successful jobs."""
    _, restored = _replace_manifest_entry(
        key=str(failed_entry["key"]),
        replacement=previous_entry,
        section=section,
        expected=failed_entry,
    )
    return restored


class GenerationVerificationError(RuntimeError):
    """Raised after a candidate kernel fails standalone verification."""


def require_portable_cooperative_grid(code: str) -> None:
    """Reject generated cooperative kernels that launch multiple CTAs per SM."""
    if "launch_cooperative_grid=True" not in code:
        return
    multiplier = re.search(r"_NUM_SM\s*\*\s*(\d+)", code)
    if multiplier is not None:
        raise RuntimeError(
            "cooperative backward grid is not portable: generated code launches "
            f"{multiplier.group(1)} CTAs per SM"
        )


def install_generated_artifacts(
    *,
    target: Path,
    module: str,
    backward_target: Path,
    backward_module: str | None,
    manifest_entry: dict[str, object],
    verify: Callable[[], int],
    manifest_section: str = "kernels",
) -> None:
    """Install and verify files, rolling back only this manifest key on error."""
    paths = (target, backward_target)
    previous = {path: path.read_bytes() if path.exists() else None for path in paths}
    previous_manifest_entry = None
    manifest_updated = False
    try:
        target.write_text(module)
        if backward_module is None:
            backward_target.unlink(missing_ok=True)
        else:
            backward_target.write_text(backward_module)
        previous_manifest_entry = upsert_manifest(manifest_entry, manifest_section)
        manifest_updated = True
        if verify() != 0:
            raise GenerationVerificationError(
                "generated kernel failed standalone verification"
            )
    except BaseException:
        for path, contents in previous.items():
            if contents is None:
                path.unlink(missing_ok=True)
            else:
                path.write_bytes(contents)
        if manifest_updated:
            rollback_manifest_entry(
                manifest_entry, previous_manifest_entry, manifest_section
            )
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--batch", type=int, required=True)
    parser.add_argument("--seqlen", type=int, required=True)
    parser.add_argument("--seqlen-k", type=int, default=None)
    parser.add_argument("--nheads", type=int, required=True)
    parser.add_argument("--nheads-kv", type=int, default=None)
    parser.add_argument("--head-dim", type=int, required=True)
    parser.add_argument("--dtype", choices=sorted(DTYPES), default="bf16")
    parser.add_argument("--causal", action="store_true")
    parser.add_argument(
        "--backward",
        action="store_true",
        help="also generate the non-causal MHA backward specialization",
    )
    layout = parser.add_mutually_exclusive_group()
    layout.add_argument(
        "--varlen",
        action="store_true",
        help="generate a packed [total, heads, dim] forward specialization",
    )
    layout.add_argument(
        "--paged",
        action="store_true",
        help="generate packed-query attention over a paged KV cache",
    )
    parser.add_argument(
        "--page-size",
        type=int,
        default=16,
        help="KV cache page size for --paged (vLLM defaults to 16)",
    )
    parser.add_argument("--label", default="", help="human note stored in the manifest")
    args = parser.parse_args()

    from helion_attention._shape import AttnShape

    spec = AttnShape(
        batch=args.batch,
        seqlen_q=args.seqlen,
        seqlen_k=args.seqlen_k if args.seqlen_k is not None else args.seqlen,
        nheads_q=args.nheads,
        nheads_kv=args.nheads_kv if args.nheads_kv is not None else args.nheads,
        head_dim=args.head_dim,
        dtype=DTYPES[args.dtype],
        causal=args.causal,
    )
    if args.backward and (
        spec.causal
        or spec.seqlen_q != spec.seqlen_k
        or spec.nheads_q != spec.nheads_kv
    ):
        raise SystemExit(
            "backward generation currently supports only non-causal MHA with "
            "equal query/key sequence lengths"
        )
    if args.backward and (args.varlen or args.paged):
        raise SystemExit("--backward cannot be combined with --varlen or --paged")
    if args.page_size <= 0:
        raise SystemExit("--page-size must be positive")

    kernel_key = (
        f"paged_{spec.key}_ps{args.page_size}"
        if args.paged
        else f"varlen_{spec.key}" if args.varlen else spec.key
    )
    manifest_section = (
        "paged_kernels"
        if args.paged
        else "varlen_kernels" if args.varlen else "kernels"
    )
    target = KERNELS_DIR / f"{kernel_key}.py"
    backward_target = KERNELS_DIR / f"{kernel_key}_backward.py"
    prior_entry = manifest_entry(kernel_key, manifest_section)

    import helion_kernels

    def incumbent_inputs(
        kernel,  # noqa: ANN001
        kernel_args: tuple[object, ...],
        entry_point: str,
        *,
        backward: bool = False,
    ) -> dict[str, object]:
        provenance_name = (
            "backward_autotuning_provenance" if backward else "autotuning_provenance"
        )
        provenance = (
            prior_entry.get(provenance_name) if prior_entry is not None else None
        )
        if not isinstance(provenance, dict):
            return {}
        if provenance_config(provenance, kernel.name) is None:
            return {}
        artifact = backward_target if backward else target
        if not artifact.exists():
            return {}
        return {
            "incumbent_provenance": provenance,
            "incumbent": load_incumbent_runner(
                kernel_key,
                entry_point,
                kernel_args,
                backward=backward,
            ),
        }

    helion_version = package_version("helion")
    split_kv_decode = False
    forward_provenance = None
    if args.paged:
        kernel = helion_kernels.paged_attention_thd
        forward_args = build_paged_inputs(spec, args.page_size)
        q, k, v = forward_args[:3]
        sm_scale = forward_args[-2]
        print(
            f"autotuning paged page_size={args.page_size} {spec.describe()}",
            flush=True,
        )
        got, forward_provenance = run_with_provenance(
            kernel,
            forward_args,
            helion_version=helion_version,
            **incumbent_inputs(kernel, forward_args, "attention_paged"),
        )
        expected = helion_kernels._paged_sdpa_reference(*forward_args)
    elif args.varlen:
        kernel = helion_kernels.varlen_attention_thd
        forward_args = build_varlen_inputs(spec)
        q, k, v = forward_args[:3]
        sm_scale = forward_args[-2]
        print(f"autotuning varlen {spec.describe()}", flush=True)
        got, forward_provenance = run_with_provenance(
            kernel,
            forward_args,
            helion_version=helion_version,
            **incumbent_inputs(kernel, forward_args, "attention_varlen"),
        )
        expected = helion_kernels._varlen_sdpa_reference(*forward_args)
    else:
        kernel_name = select_dense_kernel_name(spec)
        kernel = getattr(helion_kernels, kernel_name)
        split_kv_decode = kernel_name == "decode_attention_bshd_split_kv"
        if spec.is_decode and not split_kv_decode:
            # Decode has only batch * heads independent programs. A persistent
            # grid adds scheduler overhead without exposing more parallelism.
            kernel.settings.autotune_config_filter = nonpersistent_decode_config
        q, k, v, sm_scale = build_inputs(spec)
        forward_args = (q, k, v, sm_scale)
        print(f"autotuning {spec.describe()}", flush=True)
        if split_kv_decode:
            # This composite uses two deliberately fixed Helion configs.
            got = kernel(*forward_args)
        else:
            got, forward_provenance = run_with_provenance(
                kernel,
                forward_args,
                helion_version=helion_version,
                **incumbent_inputs(kernel, forward_args, "attention"),
            )
        expected = reference(q, k, v, sm_scale, spec.causal)
    error = (got.float() - expected).abs().max().item()
    print(f"max abs error vs fp32 SDPA: {error:.4g}")
    if error > 5e-2:
        raise SystemExit(f"autotuned kernel is not accurate enough: {error}")

    backward_kernel = None
    backward_code = None
    backward_provenance = None
    if args.backward:
        backward_kernel = helion_kernels.attention_backward_bshd
        grad_generator = torch.Generator(device="cuda").manual_seed(1)
        grad_out = torch.randn(
            q.shape,
            device=q.device,
            dtype=q.dtype,
            generator=grad_generator,
        )
        print(f"autotuning backward for {spec.describe()}", flush=True)
        backward_args = (q, k, v, grad_out, sm_scale)
        got_grads, backward_provenance = run_with_provenance(
            backward_kernel,
            backward_args,
            helion_version=helion_version,
            **incumbent_inputs(
                backward_kernel,
                backward_args,
                "attention_backward",
                backward=True,
            ),
        )
        expected_grads = reference_gradients(q, k, v, grad_out, sm_scale)
        grad_errors = [
            (actual.float() - expected).abs().max().item()
            for actual, expected in zip(got_grads, expected_grads)
        ]
        print(
            "max abs gradient errors vs fp32 SDPA: "
            + ", ".join(
                f"{name}={error:.4g}"
                for name, error in zip(("dq", "dk", "dv"), grad_errors)
            )
        )
        if max(grad_errors) > 5e-2:
            raise SystemExit(
                f"autotuned backward kernel is not accurate enough: {grad_errors}"
            )
        if backward_provenance["selection"] != "incumbent":
            backward_bound = backward_kernel.bind(backward_args)
            backward_code = strip_helion(backward_bound.to_triton_code())
            backward_code = rename_entry_point(
                backward_code, backward_kernel.name, "attention_backward"
            )
            require_portable_cooperative_grid(backward_code)

    if not (args.paged or args.varlen) and split_kv_decode:
        partial_kernel = helion_kernels.decode_attention_bshd_split_kv_partials
        partial_acc = torch.empty(
            (
                spec.batch,
                spec.nheads_q,
                SPLIT_KV_DECODE_SPLITS,
                1,
                spec.head_dim,
            ),
            dtype=torch.float32,
            device=q.device,
        )
        partial_stats = torch.empty(
            (spec.batch, spec.nheads_q, 2, SPLIT_KV_DECODE_SPLITS, 1),
            dtype=torch.float32,
            device=q.device,
        )
        partial_args = (q, k, v, partial_acc, partial_stats, sm_scale)
        partial_bound = partial_kernel.bind(partial_args)
        partial_code = strip_helion(partial_bound.to_triton_code())
        partial_code = rename_entry_point(
            partial_code,
            partial_kernel.name,
            "_attention_split_kv_partials",
        )
        partial_code = namespace_generated_constants(partial_code, "PARTIAL")

        partial_kernel(*partial_args)
        combine_kernel = helion_kernels.decode_attention_bshd_split_kv_combine
        combine_args = (partial_acc, partial_stats, torch.empty_like(q))
        combine_bound = combine_kernel.bind(combine_args)
        combine_code = strip_helion(combine_bound.to_triton_code())
        combine_code = rename_entry_point(
            combine_code,
            combine_kernel.name,
            "_attention_split_kv_combine",
        )
        combine_code = namespace_generated_constants(combine_code, "COMBINE")
        code = (
            merge_generated_modules(partial_code, combine_code)
            + _SPLIT_KV_DECODE_ENTRY_POINT
        )
        from helion.autotuner.benchmarking import do_bench

        measured_time_ms = float(
            do_bench(lambda: kernel(*forward_args), return_mode="mean")
        )
        forward_provenance = make_provenance(
            helion_version=helion_version,
            selection="fixed",
            configs=[
                (partial_kernel.name, partial_kernel.configs[0]),
                (combine_kernel.name, combine_kernel.configs[0]),
            ],
            wall_time_seconds=0.0,
            measured_time_ms=measured_time_ms,
        )
    elif forward_provenance["selection"] != "incumbent":
        bound = kernel.bind(forward_args)
        code = strip_helion(bound.to_triton_code())
        code = rename_entry_point(
            code,
            kernel.name,
            (
                "attention_paged"
                if args.paged
                else "attention_varlen" if args.varlen else "attention"
            ),
        )

    command = " ".join(
        ["python tools/generate.py", f"--batch {spec.batch}", f"--seqlen {spec.seqlen_q}"]
        + ([f"--seqlen-k {spec.seqlen_k}"] if spec.seqlen_k != spec.seqlen_q else [])
        + [f"--nheads {spec.nheads_q}"]
        + ([f"--nheads-kv {spec.nheads_kv}"] if spec.nheads_kv != spec.nheads_q else [])
        + [f"--head-dim {spec.head_dim}", f"--dtype {spec.dtype_name}"]
        + (["--causal"] if spec.causal else [])
        + (["--backward"] if args.backward else [])
        + (["--varlen"] if args.varlen else [])
        + ([f"--paged --page-size {args.page_size}"] if args.paged else [])
    )
    description = (
        f"paged page_size={args.page_size} {spec.describe()}"
        if args.paged
        else f"varlen {spec.describe()}" if args.varlen else spec.describe()
    )
    spec_fields = {
        "key": kernel_key,
        "batch": spec.batch,
        "seqlen_q": spec.seqlen_q,
        "seqlen_k": spec.seqlen_k,
        "nheads_q": spec.nheads_q,
        "nheads_kv": spec.nheads_kv,
        "head_dim": spec.head_dim,
        "dtype": spec.dtype_name,
        "causal": spec.causal,
        "backward": args.backward,
        "varlen": args.varlen,
    }
    if args.paged:
        spec_fields.update({"paged": True, "page_size": args.page_size})
    assert forward_provenance is not None
    if forward_provenance["selection"] == "incumbent":
        module = refresh_module_provenance(target.read_text(), forward_provenance)
    else:
        module = build_module(
            code,
            command=command,
            description=description,
            spec_fields=spec_fields,
            provenance=forward_provenance,
        )

    KERNELS_DIR.mkdir(parents=True, exist_ok=True)
    backward_module = None
    if args.backward:
        assert backward_provenance is not None
        if backward_provenance["selection"] == "incumbent":
            backward_module = refresh_module_provenance(
                backward_target.read_text(), backward_provenance
            )
        else:
            assert backward_code is not None
            backward_module = build_module(
                backward_code,
                command=command,
                description=f"{spec.describe()} backward",
                spec_fields=spec_fields,
                provenance=backward_provenance,
            )
    manifest_entry = {
        "key": kernel_key,
        "batch": spec.batch,
        "seqlen_q": spec.seqlen_q,
        "seqlen_k": spec.seqlen_k,
        "nheads_q": spec.nheads_q,
        "nheads_kv": spec.nheads_kv,
        "head_dim": spec.head_dim,
        "dtype": spec.dtype_name,
        "causal": spec.causal,
        "backward": args.backward,
        "varlen": args.varlen,
        "description": description,
        "note": args.label,
        "autotuning_provenance": forward_provenance,
    }
    if backward_provenance is not None:
        manifest_entry["backward_autotuning_provenance"] = backward_provenance
    if args.paged:
        manifest_entry.update({"paged": True, "page_size": args.page_size})

    def verify_generated_kernel() -> int:
        return subprocess.run(
            [sys.executable, str(REPO_ROOT / "tools" / "verify.py"), kernel_key],
            cwd=REPO_ROOT,
        ).returncode

    try:
        install_generated_artifacts(
            target=target,
            module=module,
            backward_target=backward_target,
            backward_module=backward_module,
            manifest_entry=manifest_entry,
            verify=verify_generated_kernel,
            manifest_section=manifest_section,
        )
    except GenerationVerificationError as exc:
        raise SystemExit(f"{exc}; restored previous artifacts") from exc

    print(f"wrote {target.relative_to(REPO_ROOT)} ({len(module.splitlines())} lines)")
    if backward_module is not None:
        print(
            f"wrote {backward_target.relative_to(REPO_ROOT)} "
            f"({len(backward_module.splitlines())} lines)"
        )
    print("manifest updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
