"""Autotune a Helion attention kernel for one shape and check in the Triton.

Usage:
    python tools/generate.py --batch 2 --seqlen 1024 --nheads 32 --head-dim 64 \
        --dtype bf16 [--causal] [--nheads-kv 8] [--seqlen-k 1024]

The emitted module under ``helion_attention/kernels/`` is Helion's own output
with four mechanical substitutions applied, so that the runtime package needs
only ``torch`` and ``triton``.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import subprocess
import sys
from pathlib import Path

import torch

REPO_ROOT = Path(__file__).resolve().parent.parent
KERNELS_DIR = REPO_ROOT / "helion_attention" / "kernels"
MANIFEST = KERNELS_DIR / "manifest.json"

sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "tools"))

DTYPES = {"bf16": torch.bfloat16, "fp16": torch.float16}

_HEADER = '''"""Generated by Helion, checked in as plain Triton. Do not edit by hand.

Regenerate with:
    {command}

{description}
"""

'''

_SUBSTITUTIONS = (
    ("import helion\n", ""),
    (
        "from helion.runtime import default_launcher as _default_launcher",
        "from .._launcher import default_launcher as _default_launcher\n"
        "from .._runtime import get_num_sm\n"
        "from .._runtime import set_triton_allocator",
    ),
    ("helion.runtime.set_triton_allocator()", "set_triton_allocator()"),
    ("helion.runtime.get_num_sm(", "get_num_sm("),
)


def strip_helion(code: str) -> str:
    """Rewrite Helion's generated module into a Helion-free one."""
    for needle, replacement in _SUBSTITUTIONS:
        code = code.replace(needle, replacement)
    leftover = re.findall(r"^.*(?:\bhelion\b|_source_module).*$", code, flags=re.MULTILINE)
    leftover = [line for line in leftover if not line.lstrip().startswith("#")]
    if leftover:
        raise RuntimeError("unhandled Helion reference in generated code:\n" + "\n".join(leftover))
    return code


def rename_entry_point(code: str, generated_name: str) -> str:
    """Expose the host wrapper under the stable name ``attention``."""
    pattern = rf"^def {re.escape(generated_name)}\("
    if not re.search(pattern, code, flags=re.MULTILINE):
        raise RuntimeError(f"generated code has no `def {generated_name}(`")
    return re.sub(pattern, "def attention(", code, count=1, flags=re.MULTILINE)


def build_inputs(spec: "AttnShape") -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, float]:
    generator = torch.Generator(device="cuda").manual_seed(0)

    def rand(seqlen: int, nheads: int) -> torch.Tensor:
        return torch.randn(
            (spec.batch, seqlen, nheads, spec.head_dim),
            device="cuda",
            dtype=spec.dtype,
            generator=generator,
        )

    q = rand(spec.seqlen_q, spec.nheads_q)
    k = rand(spec.seqlen_k, spec.nheads_kv)
    v = rand(spec.seqlen_k, spec.nheads_kv)
    return q, k, v, 1.0 / math.sqrt(spec.head_dim)


def reference(q, k, v, sm_scale, causal):  # noqa: ANN001, ANN201
    # PyTorch's is_causal mask is top-left aligned for unequal sequence
    # lengths. FlashAttention's is bottom-right aligned, which means a single
    # newest-token query sees the full cache and needs no explicit mask.
    is_causal = causal and q.size(1) == k.size(1)
    return torch.nn.functional.scaled_dot_product_attention(
        q.transpose(1, 2).float(),
        k.transpose(1, 2).float(),
        v.transpose(1, 2).float(),
        scale=sm_scale,
        is_causal=is_causal,
        enable_gqa=q.size(2) != k.size(2),
    ).transpose(1, 2)


def upsert_manifest(entry: dict[str, object]) -> None:
    payload = {"kernels": []}
    if MANIFEST.exists():
        with MANIFEST.open() as handle:
            payload = json.load(handle)
    kernels = [item for item in payload["kernels"] if item["key"] != entry["key"]]
    kernels.append(entry)
    kernels.sort(key=lambda item: item["key"])
    payload["kernels"] = kernels
    with MANIFEST.open("w") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")


def remove_from_manifest(key: str) -> None:
    if not MANIFEST.exists():
        return
    with MANIFEST.open() as handle:
        payload = json.load(handle)
    payload["kernels"] = [item for item in payload["kernels"] if item["key"] != key]
    with MANIFEST.open("w") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--batch", type=int, required=True)
    parser.add_argument("--seqlen", type=int, required=True)
    parser.add_argument("--seqlen-k", type=int, default=None)
    parser.add_argument("--nheads", type=int, required=True)
    parser.add_argument("--nheads-kv", type=int, default=None)
    parser.add_argument("--head-dim", type=int, required=True)
    parser.add_argument("--dtype", choices=sorted(DTYPES), default="bf16")
    parser.add_argument("--causal", action="store_true")
    parser.add_argument("--label", default="", help="human note stored in the manifest")
    args = parser.parse_args()

    from helion_attention._shape import AttnShape

    spec = AttnShape(
        batch=args.batch,
        seqlen_q=args.seqlen,
        seqlen_k=args.seqlen_k if args.seqlen_k is not None else args.seqlen,
        nheads_q=args.nheads,
        nheads_kv=args.nheads_kv if args.nheads_kv is not None else args.nheads,
        head_dim=args.head_dim,
        dtype=DTYPES[args.dtype],
        causal=args.causal,
    )
    if spec.causal and spec.seqlen_q != spec.seqlen_k and not spec.is_decode:
        raise SystemExit(
            "unequal causal lengths are supported only for seqlen_q=1 decode"
        )

    import helion_kernels

    kernel = helion_kernels.select_kernel(
        causal=spec.causal,
        seqlen_q=spec.seqlen_q,
        seqlen_k=spec.seqlen_k,
    )
    q, k, v, sm_scale = build_inputs(spec)

    print(f"autotuning {spec.describe()}", flush=True)
    got = kernel(q, k, v, sm_scale)
    expected = reference(q, k, v, sm_scale, spec.causal)
    error = (got.float() - expected).abs().max().item()
    print(f"max abs error vs fp32 SDPA: {error:.4g}")
    if error > 5e-2:
        raise SystemExit(f"autotuned kernel is not accurate enough: {error}")

    bound = kernel.bind((q, k, v, sm_scale))
    code = strip_helion(bound.to_triton_code())
    code = rename_entry_point(code, kernel.name)

    command = " ".join(
        ["python tools/generate.py", f"--batch {spec.batch}", f"--seqlen {spec.seqlen_q}"]
        + ([f"--seqlen-k {spec.seqlen_k}"] if spec.seqlen_k != spec.seqlen_q else [])
        + [f"--nheads {spec.nheads_q}"]
        + ([f"--nheads-kv {spec.nheads_kv}"] if spec.nheads_kv != spec.nheads_q else [])
        + [f"--head-dim {spec.head_dim}", f"--dtype {spec.dtype_name}"]
        + (["--causal"] if spec.causal else [])
    )
    spec_fields = {
        "key": spec.key,
        "batch": spec.batch,
        "seqlen_q": spec.seqlen_q,
        "seqlen_k": spec.seqlen_k,
        "nheads_q": spec.nheads_q,
        "nheads_kv": spec.nheads_kv,
        "head_dim": spec.head_dim,
        "dtype": spec.dtype_name,
        "causal": spec.causal,
    }
    spec_block = (
        "KERNEL_SPEC = {\n"
        + "".join(f"    {name!r}: {value!r},\n" for name, value in spec_fields.items())
        + "}\n\n"
    )
    header = _HEADER.format(command=command, description=spec.describe())
    body = code.split("\n", 1)
    assert body[0] == "from __future__ import annotations"
    module = header + body[0] + "\n\n" + spec_block + body[1]

    KERNELS_DIR.mkdir(parents=True, exist_ok=True)
    target = KERNELS_DIR / f"{spec.key}.py"
    target.write_text(module)
    print(f"wrote {target.relative_to(REPO_ROOT)} ({len(module.splitlines())} lines)")

    upsert_manifest(
        {
            "key": spec.key,
            "batch": spec.batch,
            "seqlen_q": spec.seqlen_q,
            "seqlen_k": spec.seqlen_k,
            "nheads_q": spec.nheads_q,
            "nheads_kv": spec.nheads_kv,
            "head_dim": spec.head_dim,
            "dtype": spec.dtype_name,
            "causal": spec.causal,
            "description": spec.describe(),
            "note": args.label,
        }
    )

    check = subprocess.run(
        [sys.executable, str(REPO_ROOT / "tools" / "verify.py"), spec.key],
        cwd=REPO_ROOT,
    )
    if check.returncode != 0:
        target.unlink()
        remove_from_manifest(spec.key)
        raise SystemExit("generated kernel failed standalone verification; rolled back")
    print("manifest updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
