"""Generated by Helion, checked in as plain Triton. Do not edit by hand.

Regenerate with:
    python tools/generate.py --batch 1 --seqlen 1 --seqlen-k 16384 --nheads 32 --nheads-kv 8 --head-dim 128 --dtype bf16 --causal --replace-incumbent

batch=1 seqlen_q=1 seqlen_k=16384 nheads=32 (GQA 32:8) head_dim=128 dtype=bf16 causal=True

Autotuning provenance:
    Helion version: 1.4.0
    Config selection: fixed
    Autotuning wall time: 0.000 s
    Measured time: 0.105506 ms
    Config (decode_attention_bshd_split_kv_partials): helion.Config(block_sizes=[128], loop_orders=[[1, 2, 0]], num_stages=3, num_warps=4, pid_type='flat')
    Config (decode_attention_bshd_split_kv_combine): helion.Config(num_stages=3, num_warps=1, pid_type='flat')
"""

from __future__ import annotations

KERNEL_SPEC = {
    'key': 'b1_sq1_sk16384_hq32_hkv8_d128_bf16_causal',
    'batch': 1,
    'seqlen_q': 1,
    'seqlen_k': 16384,
    'nheads_q': 32,
    'nheads_kv': 8,
    'head_dim': 128,
    'dtype': 'bf16',
    'causal': True,
    'backward': False,
    'varlen': False,
}


import torch
import triton
import triton.language as tl
from torch._inductor.runtime.triton_compat import libdevice
from .._launcher import default_launcher as _default_launcher
from .._runtime import get_num_sm
from .._runtime import set_triton_allocator

_PARTIAL_BLOCK_SIZE_3 = tl.constexpr(4)
_PARTIAL_BLOCK_SIZE_5 = tl.constexpr(128)

@triton.jit
def _helion_decode_attention_bshd_split_kv_partials(q, k, v, partial_acc, partial_stats, qk_scale, _RDIM_SIZE_4: tl.constexpr):
    # src[helion_kernels.py:303]: for b, h_kv, split in hl.grid([batch, nheads_kv, num_splits]):
    num_blocks_0 = 8
    num_blocks_1 = 16
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    offset_1 = pid_0
    offset_2 = pid_1
    indices_4 = tl.arange(0, _RDIM_SIZE_4).to(tl.int32)
    # src[helion_kernels.py:307]: h_kv * group,
    mul = 4 * offset_1
    # src[helion_kernels.py:308]: (h_kv + 1) * group,
    add = 1 + offset_1
    mul_1 = 4 + 4 * offset_1
    # src[helion_kernels.py:315]: for tile_n in hl.tile(
    # src[helion_kernels.py:316]:     split * split_size,
    # src[helion_kernels.py:317]:     min((split + 1) * split_size, n_dim),
    # src[helion_kernels.py:315-328]: ...
    symnode_0 = 16384 * (16384 <= 1024 + 1024 * offset_2) + (1024 + 1024 * offset_2) * (1024 + 1024 * offset_2 < 16384)
    # src[helion_kernels.py:306]: for tile_h in hl.tile(
    # src[helion_kernels.py:307]:     h_kv * group,
    # src[helion_kernels.py:308]:     (h_kv + 1) * group,
    # src[helion_kernels.py:306-331]: ...
    for offset_3 in tl.range(tl.cast(mul, tl.int32), tl.cast(mul_1, tl.int32), _PARTIAL_BLOCK_SIZE_3):
        indices_3 = offset_3 + tl.arange(0, _PARTIAL_BLOCK_SIZE_3).to(tl.int32)
        # src[helion_kernels.py:311]: m_i = hl.full([tile_h], float("-inf"), dtype=torch.float32)
        m_i = tl.full([_PARTIAL_BLOCK_SIZE_3], float('-inf'), tl.float32)
        # src[helion_kernels.py:312]: l_i = hl.zeros([tile_h], dtype=torch.float32)
        l_i = tl.full([_PARTIAL_BLOCK_SIZE_3], 0.0, tl.float32)
        # src[helion_kernels.py:313]: acc = hl.zeros([tile_h, head_dim], dtype=torch.float32)
        acc = tl.full([_PARTIAL_BLOCK_SIZE_3, _RDIM_SIZE_4], 0.0, tl.float32)
        # src[helion_kernels.py:314]: q_rows = q[b, 0, tile_h, :]
        q_rows = tl.load(q + (indices_3[:, None] * 128 + (0 + indices_4)[None, :] * 1), None)
        # src[helion_kernels.py:316]: split * split_size,
        mul_2 = 1024 * offset_2
        # src[helion_kernels.py:315]: for tile_n in hl.tile(
        # src[helion_kernels.py:316]:     split * split_size,
        # src[helion_kernels.py:317]:     min((split + 1) * split_size, n_dim),
        # src[helion_kernels.py:315-328]: ...
        for offset_5 in tl.range(tl.cast(mul_2, tl.int32), tl.cast(symnode_0, tl.int32), _PARTIAL_BLOCK_SIZE_5):
            indices_5 = offset_5 + tl.arange(0, _PARTIAL_BLOCK_SIZE_5).to(tl.int32)
            mask_5 = indices_5 < symnode_0
            q_rows_copy = q_rows
            m_i_copy = m_i
            l_i_copy = l_i
            acc_copy = acc
            q_rows_copy_0 = q_rows_copy
            m_i_copy_0 = m_i_copy
            l_i_copy_0 = l_i_copy
            acc_copy_0 = acc_copy
            # src[helion_kernels.py:319]: k_blk = k[b, tile_n, h_kv, :]
            k_blk = tl.load(k + (indices_5[:, None] * 1024 + offset_1 * 128 + (0 + indices_4)[None, :] * 1), mask_5[:, None], other=0)
            # src[helion_kernels.py:320]: qk = hl.dot(q_rows, k_blk.T, out_dtype=torch.float32) * qk_scale
            permute = tl.permute(k_blk, [1, 0])
            dot = tl.dot(tl.cast(q_rows_copy_0, tl.bfloat16), tl.cast(permute, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
            v_0 = dot * qk_scale
            # src[helion_kernels.py:321]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
            _mask_to = tl.where(tl.broadcast_to(mask_5[None, :], [_PARTIAL_BLOCK_SIZE_3, _PARTIAL_BLOCK_SIZE_5]), v_0, tl.full([], float('-inf'), tl.float32))
            amax = tl.cast(tl.max(_mask_to, 1), tl.float32)
            v_1 = tl.maximum(m_i_copy_0, amax, tl.PropagateNan.ALL)
            # src[helion_kernels.py:322]: p = torch.exp2(qk - m_ij[:, None])
            subscript = v_1[:, None]
            v_2 = v_0 - subscript
            v_3 = libdevice.exp2(v_2)
            # src[helion_kernels.py:323]: alpha = torch.exp2(m_i - m_ij)
            v_4 = m_i_copy_0 - v_1
            v_5 = libdevice.exp2(v_4)
            # src[helion_kernels.py:324]: l_i = l_i * alpha + torch.sum(p, -1)
            v_6 = l_i_copy_0 * v_5
            _mask_to_1 = tl.where(tl.broadcast_to(mask_5[None, :], [_PARTIAL_BLOCK_SIZE_3, _PARTIAL_BLOCK_SIZE_5]), v_3, tl.full([], 0, tl.float32))
            sum_1 = tl.cast(tl.sum(_mask_to_1, 1), tl.float32)
            l_i = v_6 + sum_1
            # src[helion_kernels.py:325]: acc = acc * alpha[:, None]
            subscript_1 = v_5[:, None]
            v_8 = acc_copy_0 * subscript_1
            # src[helion_kernels.py:326]: v_blk = v[b, tile_n, h_kv, :]
            v_blk = tl.load(v + (indices_5[:, None] * 1024 + offset_1 * 128 + (0 + indices_4)[None, :] * 1), mask_5[:, None], other=0)
            # src[helion_kernels.py:327]: acc = hl.dot(p.to(v_blk.dtype), v_blk, acc=acc)
            v_9 = tl.cast(v_3, tl.bfloat16)
            acc = tl.dot(tl.cast(v_9, tl.bfloat16), tl.cast(v_blk, tl.bfloat16), acc=v_8, input_precision='tf32', out_dtype=tl.float32)
            # src[helion_kernels.py:328]: m_i = m_ij
            m_i = v_1
        # src[helion_kernels.py:329]: partial_acc[b, tile_h, split, :, :] = acc[:, None, :]
        subscript_2 = acc[:, None, :]
        tl.store(partial_acc + (indices_3[:, None, None] * 2048 + offset_2 * 128 + (0 + indices_4)[None, None, :] * 1), subscript_2, None)
        # src[helion_kernels.py:330]: partial_stats[b, tile_h, 0, split, :] = m_i[:, None]
        subscript_3 = m_i[:, None]
        tl.store(partial_stats + (indices_3[:, None] * 32 + 0 * 16 + offset_2 * 1), subscript_3, None)
        # src[helion_kernels.py:331]: partial_stats[b, tile_h, 1, split, :] = l_i[:, None]
        subscript_4 = l_i[:, None]
        tl.store(partial_stats + (indices_3[:, None] * 32 + 1 * 16 + offset_2 * 1), subscript_4, None)

def _attention_split_kv_partials(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, partial_acc: torch.Tensor, partial_stats: torch.Tensor, sm_scale: float, *, _launcher=_default_launcher):
    """Compute independent online-softmax partials for each GQA head group."""
    # src[helion_kernels.py:293]: batch = q.size(0)
    batch = q.size(0)
    # src[helion_kernels.py:301]: qk_scale = sm_scale * 1.44269504088896340736
    qk_scale = sm_scale * 1.4426950408889634
    # src[helion_kernels.py:303]: for b, h_kv, split in hl.grid([batch, nheads_kv, num_splits]):
    _RDIM_SIZE_4 = 128
    # src[helion_kernels.py:303]: for b, h_kv, split in hl.grid([batch, nheads_kv, num_splits]):
    # src[helion_kernels.py:304]:     # Process the complete GQA group together so its query heads share each
    # src[helion_kernels.py:305]:     # K/V load. More KV splits preserve a full launch grid for small batches.
    # src[helion_kernels.py:303-331]: ...
    _launcher(_helion_decode_attention_bshd_split_kv_partials, (8 * 16 * 1,), q, k, v, partial_acc, partial_stats, qk_scale, _RDIM_SIZE_4, num_warps=4, num_stages=3)
    # src[helion_kernels.py:332]: return partial_acc, partial_stats
    return (partial_acc, partial_stats)

import torch
import triton
import triton.language as tl
from torch._inductor.runtime.triton_compat import libdevice
from .._launcher import default_launcher as _default_launcher
from .._runtime import get_num_sm
from .._runtime import set_triton_allocator

@triton.jit
def _helion_decode_attention_bshd_split_kv_combine(partial_stats, partial_acc, out, softmax_lse, _RDIM_SIZE_2: tl.constexpr, _RDIM_SIZE_3: tl.constexpr, STORE_LSE: tl.constexpr):
    # src[helion_kernels.py:351]: for b, h in hl.grid([batch, nheads_q]):
    num_blocks_0 = 1
    pid_1 = tl.program_id(0) // num_blocks_0
    offset_1 = pid_1
    indices_2 = tl.arange(0, _RDIM_SIZE_2).to(tl.int32)
    indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
    # src[helion_kernels.py:352]: split_max = partial_stats[b, h, 0, :, :]
    split_max = tl.load(partial_stats + (offset_1 * 32 + 0 * 16 + (0 + indices_2)[:, None] * 1), None)
    # src[helion_kernels.py:353]: global_max = torch.amax(split_max, 0)
    global_max = tl.cast(tl.max(split_max, 0), tl.float32)
    # src[helion_kernels.py:354]: renormalize = torch.exp2(split_max - global_max)
    v_0 = global_max[None, :]
    v_1 = split_max - v_0
    v_2 = libdevice.exp2(v_1)
    # src[helion_kernels.py:356]: partial_stats[b, h, 1, :, :] * renormalize,
    load_1 = tl.load(partial_stats + (offset_1 * 32 + 1 * 16 + (0 + indices_2)[:, None] * 1), None)
    v_3 = load_1 * v_2
    # src[helion_kernels.py:355]: denominator = torch.sum(
    # src[helion_kernels.py:356]:     partial_stats[b, h, 1, :, :] * renormalize,
    # src[helion_kernels.py:357]:     0,
    # src[helion_kernels.py:355-358]: ...
    denominator = tl.cast(tl.sum(v_3, 0), tl.float32)
    # src[helion_kernels.py:360]: partial_acc[b, h, :, :, :] * renormalize[:, :, None],
    load_2 = tl.load(partial_acc + (offset_1 * 2048 + (0 + indices_2)[:, None, None] * 128 + (0 + indices_3)[None, None, :] * 1), None)
    subscript = v_2[:, :, None]
    v_4 = load_2 * subscript
    # src[helion_kernels.py:359]: numerator = torch.sum(
    # src[helion_kernels.py:360]:     partial_acc[b, h, :, :, :] * renormalize[:, :, None],
    # src[helion_kernels.py:361]:     0,
    # src[helion_kernels.py:359-362]: ...
    numerator = tl.cast(tl.sum(v_4, 0), tl.float32)
    # src[helion_kernels.py:363]: out[b, :, h, :] = (numerator / denominator[:, None]).to(out.dtype)
    subscript_1 = denominator[:, None]
    v_5 = numerator / subscript_1
    v_6 = tl.cast(v_5, tl.bfloat16)
    tl.store(out + (offset_1 * 128 + (0 + indices_3)[None, :] * 1), v_6, None)
    if STORE_LSE:
        # The split statistics use base-2 exponentials. Convert their combined
        # normalization factor to FlashAttention's natural-log convention.
        lse = (global_max + libdevice.log2(denominator)) * 0.6931471805599453
        tl.store(softmax_lse + offset_1 + tl.arange(0, 1), lse, None)

def _attention_split_kv_combine(partial_acc: torch.Tensor, partial_stats: torch.Tensor, out: torch.Tensor, softmax_lse: torch.Tensor, return_softmax_lse: bool, *, _launcher=_default_launcher):
    """Renormalize and combine the per-split softmax numerators."""
    # src[helion_kernels.py:349]: batch = out.size(0)
    batch = out.size(0)
    # src[helion_kernels.py:351]: for b, h in hl.grid([batch, nheads_q]):
    _RDIM_SIZE_2 = 16
    _RDIM_SIZE_3 = 128
    # src[helion_kernels.py:351]: for b, h in hl.grid([batch, nheads_q]):
    # src[helion_kernels.py:352]:     split_max = partial_stats[b, h, 0, :, :]
    # src[helion_kernels.py:353]:     global_max = torch.amax(split_max, 0)
    # src[helion_kernels.py:351-363]: ...
    _launcher(_helion_decode_attention_bshd_split_kv_combine, (1 * 32,), partial_stats, partial_acc, out, softmax_lse, _RDIM_SIZE_2, _RDIM_SIZE_3, STORE_LSE=return_softmax_lse, num_warps=1, num_stages=3)
    # src[helion_kernels.py:364]: return out
    return out
import threading as _threading

from .._launcher import launcher_context as _launcher_context

# Keep scratch alive between decode steps. Workspaces are stream-local, and
# the lock keeps each partial/combine launch pair adjacent on a shared stream.
_SPLIT_KV_WORKSPACES = {}

def _split_kv_workspace(q: torch.Tensor, num_splits: int):
    key = (
        q.device.index,
        torch.cuda.current_stream(q.device).cuda_stream,
    )
    workspace = _SPLIT_KV_WORKSPACES.get(key)
    if workspace is None:
        candidate = (
            torch.empty(
                (q.size(0), q.size(2), num_splits, 1, q.size(3)),
                dtype=torch.float32,
                device=q.device,
            ),
            torch.empty(
                (q.size(0), q.size(2), 2, num_splits, 1),
                dtype=torch.float32,
                device=q.device,
            ),
            _threading.Lock(),
        )
        workspace = _SPLIT_KV_WORKSPACES.setdefault(key, candidate)
    return workspace

def attention(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, sm_scale: float, *, return_softmax_lse: bool = False, _launcher=_default_launcher):
    num_splits = 16
    partial_acc, partial_stats, workspace_lock = _split_kv_workspace(
        q, num_splits
    )
    out = torch.empty_like(q)
    softmax_lse = (
        torch.empty(
            (q.size(0), q.size(2), q.size(1)),
            dtype=torch.float32,
            device=q.device,
        )
        if return_softmax_lse
        else out
    )
    with workspace_lock, _launcher_context(q.device, _launcher) as launch:
        _attention_split_kv_partials(
            q, k, v, partial_acc, partial_stats, sm_scale, _launcher=launch
        )
        out = _attention_split_kv_combine(
            partial_acc,
            partial_stats,
            out,
            softmax_lse,
            return_softmax_lse,
            _launcher=launch,
        )
    return (out, softmax_lse) if return_softmax_lse else out
