"""Generated by Helion, checked in as plain Triton. Do not edit by hand.

Regenerate with:
    python tools/generate.py --batch 1 --seqlen 1 --seqlen-k 4096 --nheads 32 --nheads-kv 8 --head-dim 128 --dtype bf16 --causal

batch=1 seqlen_q=1 seqlen_k=4096 nheads=32 (GQA 32:8) head_dim=128 dtype=bf16 causal=True

Autotuning provenance:
    Helion version: 1.4.0
    Config selection: autotuned
    Autotuning wall time: 389.546 s
    Measured time: 0.040192 ms
    Config: helion.Config(atomic_indexing=[], block_sizes=[64, 128], indexing=['tensor_descriptor', 'pointer', 'pointer', 'pointer'], l2_groupings=[32], load_eviction_policies=['', 'last', 'first'], loop_orders=[[0, 1]], num_stages=3, num_warps=4, pid_type='flat', range_flattens=[None, None, None], range_multi_buffers=[None, None, False], range_num_stages=[0, 1, 0], range_unroll_factors=[0, 2, 0], range_warp_specializes=[], static_ranges=[False])
"""

from __future__ import annotations

KERNEL_SPEC = {
    'key': 'b1_sq1_sk4096_hq32_hkv8_d128_bf16_causal',
    'batch': 1,
    'seqlen_q': 1,
    'seqlen_k': 4096,
    'nheads_q': 32,
    'nheads_kv': 8,
    'head_dim': 128,
    'dtype': 'bf16',
    'causal': True,
    'backward': False,
    'varlen': False,
}


import torch
import triton
import triton.language as tl
from torch._inductor.runtime import triton_helpers
from torch._inductor.runtime.triton_compat import libdevice
from .._launcher import default_launcher as _default_launcher
from .._runtime import get_num_sm
from .._runtime import set_triton_allocator

_BLOCK_SIZE_2 = tl.constexpr(1)
_BLOCK_SIZE_4 = tl.constexpr(128)

@triton.jit
def _helion_causal_attention_bshd(q, k, v, out, softmax_lse, qk_scale, _RDIM_SIZE_3: tl.constexpr, STORE_LSE: tl.constexpr):
    # src[helion_kernels.py:233]: for b, h in hl.grid([batch, nheads_q]):
    num_pid_m = 1
    num_pid_n = 32
    inner_2d_pid = tl.program_id(0)
    num_pid_in_group = 32 * num_pid_n
    group_id = inner_2d_pid // num_pid_in_group
    first_pid_m = group_id * 32
    group_size_m = min(num_pid_m - first_pid_m, 32)
    pid_1 = inner_2d_pid % num_pid_in_group // group_size_m
    offset_1 = pid_1
    indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
    # src[helion_kernels.py:248]: k_blk = k[b, tile_n, h_kv, :]
    symnode_0 = triton_helpers.div_floor_integer(offset_1, 4)
    # src[helion_kernels.py:235]: for tile_m in hl.tile(m_dim):
    # src[helion_kernels.py:236]:     m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
    # src[helion_kernels.py:237]:     l_i = hl.zeros([tile_m], dtype=torch.float32)
    # src[helion_kernels.py:235-270]: ...
    for offset_2 in tl.range(0, 1):
        indices_2 = offset_2 + tl.arange(0, 1).to(tl.int32)
        # src[helion_kernels.py:236]: m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
        m_i = tl.full([_BLOCK_SIZE_2], float('-inf'), tl.float32)
        # src[helion_kernels.py:237]: l_i = hl.zeros([tile_m], dtype=torch.float32)
        l_i = tl.full([_BLOCK_SIZE_2], 0.0, tl.float32)
        # src[helion_kernels.py:238]: acc = hl.zeros([tile_m, head_dim], dtype=torch.float32)
        acc = tl.full([_BLOCK_SIZE_2, _RDIM_SIZE_3], 0.0, tl.float32)
        # src[helion_kernels.py:239]: q_blk = q[b, tile_m, h, :]
        q_blk = tl.broadcast_to(tl.load(q + (offset_1 * 128 + (0 + indices_3)[None, :] * 1), None), [_BLOCK_SIZE_2, _RDIM_SIZE_3])
        # src[helion_kernels.py:247]: for tile_n in hl.tile(0, key_stop):
        # src[helion_kernels.py:248]:     k_blk = k[b, tile_n, h_kv, :]
        # src[helion_kernels.py:249]:     qk = hl.dot(q_blk, k_blk.T, out_dtype=torch.float32) * qk_scale
        # src[helion_kernels.py:247-264]: ...
        for offset_4 in tl.range(0, 4096, _BLOCK_SIZE_4, disallow_acc_multi_buffer=True):
            indices_4 = offset_4 + tl.arange(0, _BLOCK_SIZE_4).to(tl.int32)
            q_blk_copy = q_blk
            m_i_copy = m_i
            l_i_copy = l_i
            acc_copy = acc
            q_blk_copy_0 = q_blk_copy
            m_i_copy_0 = m_i_copy
            l_i_copy_0 = l_i_copy
            acc_copy_0 = acc_copy
            # src[helion_kernels.py:248]: k_blk = k[b, tile_n, h_kv, :]
            k_blk = tl.load(k + (indices_4[:, None] * 1024 + symnode_0 * 128 + (0 + indices_3)[None, :] * 1), None, eviction_policy='evict_last')
            # src[helion_kernels.py:249]: qk = hl.dot(q_blk, k_blk.T, out_dtype=torch.float32) * qk_scale
            permute = tl.permute(k_blk, [1, 0])
            dot = tl.dot(tl.cast(q_blk_copy_0, tl.bfloat16), tl.cast(permute, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
            v_0 = dot * qk_scale
            # src[helion_kernels.py:250]: score_mask = tile_n.index[None, :] <= (
            subscript = indices_4[None, :]
            # src[helion_kernels.py:251]: tile_m.index + causal_offset
            v_1 = tl.full([], 4095, tl.int32)
            v_2 = indices_2 + v_1
            # src[helion_kernels.py:250]: score_mask = tile_n.index[None, :] <= (
            # src[helion_kernels.py:251]:     tile_m.index + causal_offset
            # src[helion_kernels.py:252]: )[:, None]
            subscript_1 = v_2[:, None]
            v_3 = subscript <= subscript_1
            # src[helion_kernels.py:253]: qk = torch.where(score_mask, qk, float("-inf"))
            scalar_tensor = tl.full([], float('-inf'), tl.float32)
            qk_1 = tl.where(v_3, v_0, scalar_tensor)
            # src[helion_kernels.py:254]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
            amax = tl.cast(tl.max(qk_1, 1), tl.float32)
            v_4 = tl.maximum(m_i_copy_0, amax, tl.PropagateNan.ALL)
            # src[helion_kernels.py:255]: has_key = m_ij != float("-inf")
            v_5 = tl.full([], float('-inf'), tl.float32)
            v_6 = v_4 != v_5
            # src[helion_kernels.py:257]: torch.where(score_mask, qk - m_ij[:, None], float("-inf"))
            subscript_2 = v_4[:, None]
            v_7 = qk_1 - subscript_2
            scalar_tensor_1 = tl.full([], float('-inf'), tl.float32)
            where_1 = tl.where(v_3, v_7, scalar_tensor_1)
            # src[helion_kernels.py:256]: p = torch.exp2(
            # src[helion_kernels.py:257]:     torch.where(score_mask, qk - m_ij[:, None], float("-inf"))
            # src[helion_kernels.py:258]: )
            v_8 = libdevice.exp2(where_1)
            # src[helion_kernels.py:259]: alpha = torch.where(has_key, torch.exp2(m_i - m_ij), 1.0)
            v_9 = m_i_copy_0 - v_4
            v_10 = libdevice.exp2(v_9)
            scalar_tensor_2 = tl.full([], 1.0, tl.float32)
            alpha = tl.where(v_6, v_10, scalar_tensor_2)
            # src[helion_kernels.py:260]: l_i = l_i * alpha + torch.sum(p, -1)
            v_11 = l_i_copy_0 * alpha
            sum_1 = tl.cast(tl.sum(v_8, 1), tl.float32)
            l_i = v_11 + sum_1
            # src[helion_kernels.py:261]: acc = acc * alpha[:, None]
            subscript_3 = alpha[:, None]
            v_13 = acc_copy_0 * subscript_3
            # src[helion_kernels.py:262]: v_blk = v[b, tile_n, h_kv, :]
            v_blk = tl.load(v + (indices_4[:, None] * 1024 + symnode_0 * 128 + (0 + indices_3)[None, :] * 1), None, eviction_policy='evict_first')
            # src[helion_kernels.py:263]: acc = hl.dot(p.to(v_blk.dtype), v_blk, acc=acc)
            v_14 = tl.cast(v_8, tl.bfloat16)
            acc = tl.dot(tl.cast(v_14, tl.bfloat16), tl.cast(v_blk, tl.bfloat16), acc=v_13, input_precision='tf32', out_dtype=tl.float32)
            # src[helion_kernels.py:264]: m_i = m_ij
            m_i = v_4
        # src[helion_kernels.py:266]: (l_i > 0)[:, None],
        v_15 = tl.full([], 0.0, tl.float32)
        v_16 = l_i > v_15
        subscript_4 = v_16[:, None]
        # src[helion_kernels.py:267]: acc / torch.where(l_i > 0, l_i, 1.0)[:, None],
        v_17 = tl.full([], 0.0, tl.float32)
        v_18 = l_i > v_17
        scalar_tensor_3 = tl.full([], 1.0, tl.float32)
        where = tl.where(v_18, l_i, scalar_tensor_3)
        subscript_5 = where[:, None]
        v_19 = acc / subscript_5
        # src[helion_kernels.py:265]: result = torch.where(
        # src[helion_kernels.py:266]:     (l_i > 0)[:, None],
        # src[helion_kernels.py:267]:     acc / torch.where(l_i > 0, l_i, 1.0)[:, None],
        # src[helion_kernels.py:265-269]: ...
        scalar_tensor_4 = tl.full([], 0.0, tl.float32)
        result = tl.where(subscript_4, v_19, scalar_tensor_4)
        # src[helion_kernels.py:270]: out[b, tile_m, h, :] = result.to(out.dtype)
        v_20 = tl.cast(result, tl.bfloat16)
        tl.store(out + tl.broadcast_to(offset_1 * 128 + (0 + indices_3)[None, :] * 1, [_BLOCK_SIZE_2, _RDIM_SIZE_3]), v_20, None)
        if STORE_LSE:
            # qk_scale uses log2(e), so the online state is base-2. FlashAttention
            # exposes the natural-log normalization factor.
            lse = (m_i + libdevice.log2(l_i)) * 0.6931471805599453
            tl.store(softmax_lse + offset_1 + indices_2, lse, None)

def attention(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, sm_scale: float, *, return_softmax_lse: bool = False, _launcher=_default_launcher):
    """Bottom-right causal attention over ``[batch, seq, heads, dim]``.

    Query row ``i`` attends through key ``i + seqlen_k - seqlen_q``, matching
    FlashAttention for both equal and unequal sequence lengths. Equal-length
    specializations retain the triangular key-loop optimization; unequal
    specializations mask the full key range.
    """
    # src[helion_kernels.py:223]: batch = q.size(0)
    batch = q.size(0)
    # src[helion_kernels.py:230]: out = torch.empty_like(q)
    out = torch.empty_like(q)
    softmax_lse = (
        torch.empty(
            (q.size(0), q.size(2), q.size(1)),
            dtype=torch.float32,
            device=q.device,
        )
        if return_softmax_lse
        else out
    )
    # src[helion_kernels.py:231]: qk_scale = sm_scale * 1.44269504088896340736
    qk_scale = sm_scale * 1.4426950408889634
    # src[helion_kernels.py:233]: for b, h in hl.grid([batch, nheads_q]):
    _RDIM_SIZE_3 = 128
    # src[helion_kernels.py:233]: for b, h in hl.grid([batch, nheads_q]):
    # src[helion_kernels.py:234]:     h_kv = h // group
    # src[helion_kernels.py:235]:     for tile_m in hl.tile(m_dim):
    # src[helion_kernels.py:233-270]: ...
    _launcher(_helion_causal_attention_bshd, (1 * 32,), q, k, v, out, softmax_lse, qk_scale, _RDIM_SIZE_3, STORE_LSE=return_softmax_lse, num_warps=4, num_stages=3)
    # src[helion_kernels.py:271]: return out
    return (out, softmax_lse) if return_softmax_lse else out
