"""Generated by Helion, checked in as plain Triton. Do not edit by hand.

Regenerate with:
    python tools/generate.py --batch 1 --seqlen 1 --seqlen-k 4096 --nheads 32 --nheads-kv 8 --head-dim 128 --dtype bf16 --causal

batch=1 seqlen_q=1 seqlen_k=4096 nheads=32 (GQA 32:8) head_dim=128 dtype=bf16 causal=True
"""

from __future__ import annotations

KERNEL_SPEC = {
    'key': 'b1_sq1_sk4096_hq32_hkv8_d128_bf16_causal',
    'batch': 1,
    'seqlen_q': 1,
    'seqlen_k': 4096,
    'nheads_q': 32,
    'nheads_kv': 8,
    'head_dim': 128,
    'dtype': 'bf16',
    'causal': True,
}


import torch
import triton
import triton.language as tl
from torch._inductor.runtime import triton_helpers
from torch._inductor.runtime.triton_compat import libdevice
from .._launcher import default_launcher as _default_launcher
from .._runtime import get_num_sm
from .._runtime import set_triton_allocator

_BLOCK_SIZE_3 = tl.constexpr(128)

@triton.jit
def _helion_decode_attention_bshd(q, k, v, out, qk_scale, _RDIM_SIZE_2: tl.constexpr, _RDIM_SIZE_4: tl.constexpr):
    # src[helion_kernels.py:177]: for b, h in hl.grid([batch, nheads_q]):
    num_pid_m = 1
    num_pid_n = 32
    inner_2d_pid = tl.program_id(0)
    num_pid_in_group = 4 * num_pid_n
    group_id = inner_2d_pid // num_pid_in_group
    first_pid_m = group_id * 4
    group_size_m = min(num_pid_m - first_pid_m, 4)
    pid_1 = inner_2d_pid % num_pid_in_group // group_size_m
    offset_1 = pid_1
    indices_2 = tl.arange(0, _RDIM_SIZE_2).to(tl.int32)
    # src[helion_kernels.py:179]: m_i = hl.full([1], float("-inf"), dtype=torch.float32)
    m_i = tl.full([_RDIM_SIZE_4], float('-inf'), tl.float32)
    # src[helion_kernels.py:180]: l_i = hl.full([1], 1.0, dtype=torch.float32)
    l_i = tl.full([_RDIM_SIZE_4], 1.0, tl.float32)
    # src[helion_kernels.py:181]: acc = hl.zeros([1, head_dim], dtype=torch.float32)
    acc = tl.full([_RDIM_SIZE_4, _RDIM_SIZE_2], 0.0, tl.float32)
    # src[helion_kernels.py:182]: q_row = q[b, :, h, :]
    q_row = tl.load(q + (offset_1 * 128 + (0 + indices_2)[None, :] * 1), None)
    # src[helion_kernels.py:184]: k_blk = k[b, tile_n, h_kv, :]
    symnode_0 = triton_helpers.div_floor_integer(offset_1, 4)
    # src[helion_kernels.py:183]: for tile_n in hl.tile(n_dim):
    # src[helion_kernels.py:184]:     k_blk = k[b, tile_n, h_kv, :]
    # src[helion_kernels.py:185]:     qk = hl.dot(q_row, k_blk.T, out_dtype=torch.float32)
    # src[helion_kernels.py:183-196]: ...
    for offset_3 in tl.range(0, 4096, _BLOCK_SIZE_3, disallow_acc_multi_buffer=False, flatten=False):
        indices_3 = offset_3 + tl.arange(0, _BLOCK_SIZE_3).to(tl.int32)
        q_row_copy = q_row
        m_i_copy = m_i
        l_i_copy = l_i
        acc_copy = acc
        q_row_copy_0 = q_row_copy
        m_i_copy_0 = m_i_copy
        l_i_copy_0 = l_i_copy
        acc_copy_0 = acc_copy
        # src[helion_kernels.py:184]: k_blk = k[b, tile_n, h_kv, :]
        k_blk = tl.load(k + (indices_3[:, None] * 1024 + symnode_0 * 128 + (0 + indices_2)[None, :] * 1), None)
        # src[helion_kernels.py:185]: qk = hl.dot(q_row, k_blk.T, out_dtype=torch.float32)
        permute = tl.permute(k_blk, [1, 0])
        qk = tl.dot(tl.cast(q_row_copy_0, tl.bfloat16), tl.cast(permute, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
        # src[helion_kernels.py:186]: qk = qk * qk_scale
        v_0 = qk * qk_scale
        # src[helion_kernels.py:187]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
        amax = tl.cast(tl.max(v_0, 1), tl.float32)
        v_1 = tl.maximum(m_i_copy_0, amax, tl.PropagateNan.ALL)
        # src[helion_kernels.py:188]: qk = qk - m_ij[:, None]
        subscript = v_1[:, None]
        v_2 = v_0 - subscript
        # src[helion_kernels.py:189]: p = torch.exp2(qk)
        v_3 = libdevice.exp2(v_2)
        # src[helion_kernels.py:190]: l_ij = torch.sum(p, -1)
        l_ij = tl.cast(tl.sum(v_3, 1), tl.float32)
        # src[helion_kernels.py:191]: alpha = torch.exp2(m_i - m_ij)
        v_4 = m_i_copy_0 - v_1
        v_5 = libdevice.exp2(v_4)
        # src[helion_kernels.py:192]: l_i = l_i * alpha + l_ij
        v_6 = l_i_copy_0 * v_5
        l_i = v_6 + l_ij
        # src[helion_kernels.py:193]: acc = acc * alpha[:, None]
        subscript_1 = v_5[:, None]
        v_8 = acc_copy_0 * subscript_1
        # src[helion_kernels.py:194]: v_blk = v[b, tile_n, h_kv, :]
        v_blk = tl.load(v + (indices_3[:, None] * 1024 + symnode_0 * 128 + (0 + indices_2)[None, :] * 1), None, eviction_policy='evict_first')
        # src[helion_kernels.py:195]: acc = hl.dot(p.to(v_blk.dtype), v_blk, acc=acc)
        v_9 = tl.cast(v_3, tl.bfloat16)
        acc = tl.dot(tl.cast(v_9, tl.bfloat16), tl.cast(v_blk, tl.bfloat16), acc=v_8, input_precision='tf32', out_dtype=tl.float32)
        # src[helion_kernels.py:196]: m_i = m_ij
        m_i = v_1
    # src[helion_kernels.py:197]: out[b, :, h, :] = (acc / l_i[:, None]).to(out.dtype)
    subscript_2 = l_i[:, None]
    v_10 = acc / subscript_2
    v_11 = tl.cast(v_10, tl.bfloat16)
    tl.store(out + (offset_1 * 128 + (0 + indices_2)[None, :] * 1), v_11, None)

def attention(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, sm_scale: float, *, _launcher=_default_launcher):
    """Single-token decode over a full ``[batch, cache, heads, dim]`` KV cache.

    FlashAttention aligns unequal causal masks to the bottom right. With one
    query representing the newest token, every cache position is visible, so
    this is the decode-specific form of causal attention without a mask.
    """
    # src[helion_kernels.py:169]: batch = q.size(0)
    batch = q.size(0)
    # src[helion_kernels.py:172]: n_dim = k.size(1)
    n_dim = k.size(1)
    # src[helion_kernels.py:175]: out = torch.empty_like(q)
    out = torch.empty_like(q)
    # src[helion_kernels.py:176]: qk_scale = sm_scale * 1.44269504088896340736
    qk_scale = sm_scale * 1.4426950408889634
    # src[helion_kernels.py:177]: for b, h in hl.grid([batch, nheads_q]):
    _RDIM_SIZE_2 = 128
    _RDIM_SIZE_4 = 1
    # src[helion_kernels.py:177]: for b, h in hl.grid([batch, nheads_q]):
    # src[helion_kernels.py:178]:     h_kv = h // group
    # src[helion_kernels.py:179]:     m_i = hl.full([1], float("-inf"), dtype=torch.float32)
    # src[helion_kernels.py:177-197]: ...
    _launcher(_helion_decode_attention_bshd, (1 * 32,), q, k, v, out, qk_scale, _RDIM_SIZE_2, _RDIM_SIZE_4, num_warps=4, num_stages=3)
    # src[helion_kernels.py:198]: return out
    return out