"""Generated by Helion, checked in as plain Triton. Do not edit by hand.

Regenerate with:
    python tools/generate.py --batch 2 --seqlen 1024 --nheads 16 --head-dim 256 --dtype bf16

batch=2 seqlen_q=1024 seqlen_k=1024 nheads=16 head_dim=256 dtype=bf16 causal=False
"""

from __future__ import annotations

KERNEL_SPEC = {
    'key': 'b2_sq1024_sk1024_hq16_hkv16_d256_bf16_noncausal',
    'batch': 2,
    'seqlen_q': 1024,
    'seqlen_k': 1024,
    'nheads_q': 16,
    'nheads_kv': 16,
    'head_dim': 256,
    'dtype': 'bf16',
    'causal': False,
    'backward': False,
    'varlen': False,
}


import torch
import triton
import triton.language as tl
from torch._inductor.runtime.triton_compat import libdevice
from .._launcher import default_launcher as _default_launcher
from .._runtime import get_num_sm
from .._runtime import set_triton_allocator

_BLOCK_SIZE_2 = tl.constexpr(128)
_BLOCK_SIZE_4 = tl.constexpr(32)
# src[helion_kernels.py:163]: def attention_bshd(
# src[helion_kernels.py:164]:     q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, sm_scale: float
# src[helion_kernels.py:165]: ) -> torch.Tensor:
# src[helion_kernels.py:163-204]: ...
set_triton_allocator()

@triton.jit
def _helion_attention_bshd(q, k, v, out, qk_scale, _RDIM_SIZE_3: tl.constexpr):
    # src[helion_kernels.py:188]: q_blk = q[b, tile_m, h, :]
    q_desc = tl.make_tensor_descriptor(q, [2, 1024, 16, 256], [4194304, 4096, 256, 1], [1, _BLOCK_SIZE_2, 1, 256])
    # src[helion_kernels.py:190]: k_blk = k[b, tile_n, h_kv, :]
    k_desc = tl.make_tensor_descriptor(k, [2, 1024, 16, 256], [4194304, 4096, 256, 1], [1, _BLOCK_SIZE_4, 1, 256])
    # src[helion_kernels.py:182]: for b, h in hl.grid([batch, nheads_q]):
    num_pid_m = 2
    num_pid_n = 16
    inner_2d_pid = tl.program_id(0)
    num_pid_in_group = 2 * num_pid_n
    group_id = inner_2d_pid // num_pid_in_group
    first_pid_m = group_id * 2
    group_size_m = min(num_pid_m - first_pid_m, 2)
    pid_0 = first_pid_m + inner_2d_pid % num_pid_in_group % group_size_m
    pid_1 = inner_2d_pid % num_pid_in_group // group_size_m
    offset_0 = pid_0
    offset_1 = pid_1
    indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
    # src[helion_kernels.py:184]: for tile_m in hl.tile(m_dim):
    # src[helion_kernels.py:185]:     m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
    # src[helion_kernels.py:186]:     l_i = hl.full([tile_m], 1.0, dtype=torch.float32)
    # src[helion_kernels.py:184-203]: ...
    for offset_2 in tl.range(0, 1024, _BLOCK_SIZE_2, disallow_acc_multi_buffer=False):
        indices_2 = offset_2 + tl.arange(0, _BLOCK_SIZE_2).to(tl.int32)
        # src[helion_kernels.py:185]: m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
        m_i = tl.full([_BLOCK_SIZE_2], float('-inf'), tl.float32)
        # src[helion_kernels.py:186]: l_i = hl.full([tile_m], 1.0, dtype=torch.float32)
        l_i = tl.full([_BLOCK_SIZE_2], 1.0, tl.float32)
        # src[helion_kernels.py:187]: acc = hl.zeros([tile_m, head_dim], dtype=torch.float32)
        acc = tl.full([_BLOCK_SIZE_2, _RDIM_SIZE_3], 0.0, tl.float32)
        # src[helion_kernels.py:188]: q_blk = q[b, tile_m, h, :]
        q_blk = tl.reshape(q_desc.load([offset_0, offset_2, offset_1, 0 + 0]), [_BLOCK_SIZE_2, _RDIM_SIZE_3])
        # src[helion_kernels.py:189]: for tile_n in hl.tile(n_dim):
        # src[helion_kernels.py:190]:     k_blk = k[b, tile_n, h_kv, :]
        # src[helion_kernels.py:191]:     qk = hl.dot(q_blk, k_blk.T, out_dtype=torch.float32) * qk_scale
        # src[helion_kernels.py:189-201]: ...
        for offset_4 in tl.range(0, 1024, _BLOCK_SIZE_4, flatten=True):
            indices_4 = offset_4 + tl.arange(0, _BLOCK_SIZE_4).to(tl.int32)
            q_blk_copy = q_blk
            m_i_copy = m_i
            l_i_copy = l_i
            acc_copy = acc
            q_blk_copy_0 = q_blk_copy
            m_i_copy_0 = m_i_copy
            l_i_copy_0 = l_i_copy
            acc_copy_0 = acc_copy
            # src[helion_kernels.py:190]: k_blk = k[b, tile_n, h_kv, :]
            k_blk = tl.reshape(k_desc.load([offset_0, offset_4, offset_1, 0 + 0]), [_BLOCK_SIZE_4, _RDIM_SIZE_3])
            # src[helion_kernels.py:191]: qk = hl.dot(q_blk, k_blk.T, out_dtype=torch.float32) * qk_scale
            permute = tl.permute(k_blk, [1, 0])
            dot = tl.dot(tl.cast(q_blk_copy_0, tl.bfloat16), tl.cast(permute, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
            v_0 = dot * qk_scale
            # src[helion_kernels.py:192]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
            amax = tl.cast(tl.max(v_0, 1), tl.float32)
            v_1 = tl.maximum(m_i_copy_0, amax, tl.PropagateNan.ALL)
            # src[helion_kernels.py:193]: qk = qk - m_ij[:, None]
            subscript = v_1[:, None]
            v_2 = v_0 - subscript
            # src[helion_kernels.py:194]: p = torch.exp2(qk)
            v_3 = libdevice.exp2(v_2)
            # src[helion_kernels.py:195]: l_ij = torch.sum(p, -1)
            l_ij = tl.cast(tl.sum(v_3, 1), tl.float32)
            # src[helion_kernels.py:196]: alpha = torch.exp2(m_i - m_ij)
            v_4 = m_i_copy_0 - v_1
            v_5 = libdevice.exp2(v_4)
            # src[helion_kernels.py:197]: l_i = l_i * alpha + l_ij
            v_6 = l_i_copy_0 * v_5
            l_i = v_6 + l_ij
            # src[helion_kernels.py:198]: acc = acc * alpha[:, None]
            subscript_1 = v_5[:, None]
            v_8 = acc_copy_0 * subscript_1
            # src[helion_kernels.py:199]: v_blk = v[b, tile_n, h_kv, :]
            v_blk = tl.load(v + (offset_0 * 4194304 + indices_4[:, None] * 4096 + offset_1 * 256 + (0 + indices_3)[None, :] * 1), None)
            # src[helion_kernels.py:200]: acc = hl.dot(p.to(v_blk.dtype), v_blk, acc=acc)
            v_9 = tl.cast(v_3, tl.bfloat16)
            acc = tl.dot(tl.cast(v_9, tl.bfloat16), tl.cast(v_blk, tl.bfloat16), acc=v_8, input_precision='tf32', out_dtype=tl.float32)
            # src[helion_kernels.py:201]: m_i = m_ij
            m_i = v_1
        # src[helion_kernels.py:202]: acc = acc / l_i[:, None]
        subscript_2 = l_i[:, None]
        v_10 = acc / subscript_2
        # src[helion_kernels.py:203]: out[b, tile_m, h, :] = acc.to(out.dtype)
        v_11 = tl.cast(v_10, tl.bfloat16)
        tl.store(out + (offset_0 * 4194304 + indices_2[:, None] * 4096 + offset_1 * 256 + (0 + indices_3)[None, :] * 1), v_11, None)

def attention(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, sm_scale: float, *, _launcher=_default_launcher):
    """Non-causal attention over FlashAttention's ``[batch, seq, heads, dim]`` layout.

    ``k``/``v`` may carry fewer heads than ``q`` (grouped-query attention); each
    query head reads the key/value head ``h // (nheads_q // nheads_kv)``.
    """
    # src[helion_kernels.py:171]: batch = q.size(0)
    batch = q.size(0)
    # src[helion_kernels.py:172]: m_dim = q.size(1)
    m_dim = q.size(1)
    # src[helion_kernels.py:175]: n_dim = k.size(1)
    n_dim = k.size(1)
    # src[helion_kernels.py:178]: out = torch.empty_like(q)
    out = torch.empty_like(q)
    # src[helion_kernels.py:179]: qk_scale = sm_scale * 1.44269504088896340736
    qk_scale = sm_scale * 1.4426950408889634
    # src[helion_kernels.py:182]: for b, h in hl.grid([batch, nheads_q]):
    _RDIM_SIZE_3 = 256
    # src[helion_kernels.py:182]: for b, h in hl.grid([batch, nheads_q]):
    # src[helion_kernels.py:183]:     h_kv = h // group
    # src[helion_kernels.py:184]:     for tile_m in hl.tile(m_dim):
    # src[helion_kernels.py:182-203]: ...
    _launcher(_helion_attention_bshd, (2 * 16,), q, k, v, out, qk_scale, _RDIM_SIZE_3, num_warps=8, num_stages=3)
    # src[helion_kernels.py:204]: return out
    return out