"""Generated by Helion, checked in as plain Triton. Do not edit by hand.

Regenerate with:
    python tools/generate.py --batch 4 --seqlen 2048 --nheads 32 --nheads-kv 8 --head-dim 128 --dtype bf16 --causal

batch=4 seqlen_q=2048 seqlen_k=2048 nheads=32 (GQA 32:8) head_dim=128 dtype=bf16 causal=True
"""

from __future__ import annotations

KERNEL_SPEC = {
    'key': 'b4_sq2048_sk2048_hq32_hkv8_d128_bf16_causal',
    'batch': 4,
    'seqlen_q': 2048,
    'seqlen_k': 2048,
    'nheads_q': 32,
    'nheads_kv': 8,
    'head_dim': 128,
    'dtype': 'bf16',
    'causal': True,
}


import torch
import triton
import triton.language as tl
from torch._inductor.runtime import triton_helpers
from torch._inductor.runtime.triton_compat import libdevice
from .._launcher import default_launcher as _default_launcher
from .._runtime import get_num_sm
from .._runtime import set_triton_allocator

_BLOCK_SIZE_2 = tl.constexpr(128)
_BLOCK_SIZE_4 = tl.constexpr(128)
# src[helion_kernels.py:96]: def causal_attention_bshd(
# src[helion_kernels.py:97]:     q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, sm_scale: float
# src[helion_kernels.py:98]: ) -> torch.Tensor:
# src[helion_kernels.py:96-138]: ...
set_triton_allocator()

@triton.jit
def _helion_causal_attention_bshd(q, k, v, out, qk_scale, _RDIM_SIZE_3: tl.constexpr):
    # src[helion_kernels.py:119]: q_blk = q[b, tile_m, h, :]
    q_desc = tl.make_tensor_descriptor(q, [4, 2048, 32, 128], [8388608, 4096, 128, 1], [1, _BLOCK_SIZE_2, 1, 128])
    # src[helion_kernels.py:121]: k_blk = k[b, tile_n, h_kv, :]
    k_desc = tl.make_tensor_descriptor(k, [4, 2048, 8, 128], [2097152, 1024, 128, 1], [1, _BLOCK_SIZE_4, 1, 128])
    # src[helion_kernels.py:113]: for b, h in hl.grid([batch, nheads_q]):
    num_pid_m = 32
    num_pid_n = 4
    inner_2d_pid = tl.program_id(0)
    num_pid_in_group = 8 * num_pid_n
    group_id = inner_2d_pid // num_pid_in_group
    first_pid_m = group_id * 8
    group_size_m = min(num_pid_m - first_pid_m, 8)
    pid_0 = first_pid_m + inner_2d_pid % num_pid_in_group % group_size_m
    pid_1 = inner_2d_pid % num_pid_in_group // group_size_m
    offset_1 = pid_0
    offset_0 = pid_1
    indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
    # src[helion_kernels.py:121]: k_blk = k[b, tile_n, h_kv, :]
    symnode_0 = triton_helpers.div_floor_integer(offset_1, 4)
    # src[helion_kernels.py:115]: for tile_m in hl.tile(m_dim):
    # src[helion_kernels.py:116]:     m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
    # src[helion_kernels.py:117]:     l_i = hl.full([tile_m], 1.0, dtype=torch.float32)
    # src[helion_kernels.py:115-137]: ...
    for offset_2 in tl.range(0, 2048, _BLOCK_SIZE_2, disallow_acc_multi_buffer=False, flatten=False):
        indices_2 = offset_2 + tl.arange(0, _BLOCK_SIZE_2).to(tl.int32)
        # src[helion_kernels.py:116]: m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
        m_i = tl.full([_BLOCK_SIZE_2], float('-inf'), tl.float32)
        # src[helion_kernels.py:117]: l_i = hl.full([tile_m], 1.0, dtype=torch.float32)
        l_i = tl.full([_BLOCK_SIZE_2], 1.0, tl.float32)
        # src[helion_kernels.py:118]: acc = hl.zeros([tile_m, head_dim], dtype=torch.float32)
        acc = tl.full([_BLOCK_SIZE_2, _RDIM_SIZE_3], 0.0, tl.float32)
        # src[helion_kernels.py:119]: q_blk = q[b, tile_m, h, :]
        q_blk = tl.reshape(q_desc.load([offset_0, offset_2, offset_1, 0 + 0]), [_BLOCK_SIZE_2, _RDIM_SIZE_3])
        # src[helion_kernels.py:120]: for tile_n in hl.tile(0, tile_m.end):
        tile_end = offset_2 + _BLOCK_SIZE_2
        # src[helion_kernels.py:120]: for tile_n in hl.tile(0, tile_m.end):
        # src[helion_kernels.py:121]:     k_blk = k[b, tile_n, h_kv, :]
        # src[helion_kernels.py:122]:     qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
        # src[helion_kernels.py:120-135]: ...
        for offset_4 in tl.range(0, tl.cast(tile_end, tl.int32), _BLOCK_SIZE_4, disallow_acc_multi_buffer=False):
            indices_4 = offset_4 + tl.arange(0, _BLOCK_SIZE_4).to(tl.int32)
            mask_4 = indices_4 < tile_end
            q_blk_copy = q_blk
            m_i_copy = m_i
            l_i_copy = l_i
            acc_copy = acc
            q_blk_copy_0 = q_blk_copy
            m_i_copy_0 = m_i_copy
            l_i_copy_0 = l_i_copy
            acc_copy_0 = acc_copy
            # src[helion_kernels.py:121]: k_blk = k[b, tile_n, h_kv, :]
            k_blk = tl.reshape(k_desc.load([offset_0, offset_4, symnode_0, 0 + 0]), [_BLOCK_SIZE_4, _RDIM_SIZE_3])
            # src[helion_kernels.py:122]: qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
            v_0 = tl.cast(qk_scale, tl.bfloat16)
            v_1 = q_blk_copy_0 * v_0
            permute = tl.permute(k_blk, [1, 0])
            qk = tl.dot(tl.cast(v_1, tl.bfloat16), tl.cast(permute, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
            # src[helion_kernels.py:124]: tile_m.index[:, None] >= tile_n.index[None, :], qk, float("-inf")
            subscript = indices_2[:, None]
            subscript_1 = indices_4[None, :]
            v_2 = subscript >= subscript_1
            # src[helion_kernels.py:123]: qk = torch.where(
            # src[helion_kernels.py:124]:     tile_m.index[:, None] >= tile_n.index[None, :], qk, float("-inf")
            # src[helion_kernels.py:125]: )
            scalar_tensor = tl.full([], float('-inf'), tl.float32)
            qk_1 = tl.where(v_2, qk, scalar_tensor)
            # src[helion_kernels.py:126]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
            _mask_to = tl.where(tl.broadcast_to(mask_4[None, :], [_BLOCK_SIZE_2, _BLOCK_SIZE_4]), qk_1, tl.full([], float('-inf'), tl.float32))
            amax = tl.cast(tl.max(_mask_to, 1), tl.float32)
            v_3 = tl.maximum(m_i_copy_0, amax, tl.PropagateNan.ALL)
            # src[helion_kernels.py:127]: qk = qk - m_ij[:, None]
            subscript_2 = v_3[:, None]
            v_4 = qk_1 - subscript_2
            # src[helion_kernels.py:128]: p = torch.exp2(qk)
            v_5 = libdevice.exp2(v_4)
            # src[helion_kernels.py:129]: l_ij = torch.sum(p, -1)
            _mask_to_1 = tl.where(tl.broadcast_to(mask_4[None, :], [_BLOCK_SIZE_2, _BLOCK_SIZE_4]), v_5, tl.full([], 0, tl.float32))
            l_ij = tl.cast(tl.sum(_mask_to_1, 1), tl.float32)
            # src[helion_kernels.py:130]: alpha = torch.exp2(m_i - m_ij)
            v_6 = m_i_copy_0 - v_3
            v_7 = libdevice.exp2(v_6)
            # src[helion_kernels.py:131]: l_i = l_i * alpha + l_ij
            v_8 = l_i_copy_0 * v_7
            l_i = v_8 + l_ij
            # src[helion_kernels.py:132]: acc = acc * alpha[:, None]
            subscript_3 = v_7[:, None]
            v_10 = acc_copy_0 * subscript_3
            # src[helion_kernels.py:133]: v_blk = v[b, tile_n, h_kv, :]
            v_blk = tl.load(v + (offset_0 * 2097152 + indices_4[:, None] * 1024 + symnode_0 * 128 + (0 + indices_3)[None, :] * 1), mask_4[:, None], other=0)
            # src[helion_kernels.py:134]: acc = hl.dot(p.to(v_blk.dtype), v_blk, acc=acc)
            v_11 = tl.cast(v_5, tl.bfloat16)
            acc = tl.dot(tl.cast(v_11, tl.bfloat16), tl.cast(v_blk, tl.bfloat16), acc=v_10, input_precision='tf32', out_dtype=tl.float32)
            # src[helion_kernels.py:135]: m_i = m_ij
            m_i = v_3
        # src[helion_kernels.py:136]: acc = acc / l_i[:, None]
        subscript_4 = l_i[:, None]
        v_12 = acc / subscript_4
        # src[helion_kernels.py:137]: out[b, tile_m, h, :] = acc.to(out.dtype)
        v_13 = tl.cast(v_12, tl.bfloat16)
        tl.store(out + (offset_0 * 8388608 + indices_2[:, None] * 4096 + offset_1 * 128 + (0 + indices_3)[None, :] * 1), v_13, None)

def attention(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, sm_scale: float, *, _launcher=_default_launcher):
    """Causal attention over ``[batch, seq, heads, dim]`` with ``seqlen_q == seqlen_k``.

    The key loop stops at the diagonal instead of masking a full row of blocks,
    so the fully-masked upper triangle is never computed at all.
    """
    # src[helion_kernels.py:104]: batch = q.size(0)
    batch = q.size(0)
    # src[helion_kernels.py:105]: m_dim = q.size(1)
    m_dim = q.size(1)
    # src[helion_kernels.py:108]: n_dim = k.size(1)
    n_dim = k.size(1)
    # src[helion_kernels.py:111]: out = torch.empty_like(q)
    out = torch.empty_like(q)
    # src[helion_kernels.py:112]: qk_scale = sm_scale * 1.44269504088896340736
    qk_scale = sm_scale * 1.4426950408889634
    # src[helion_kernels.py:113]: for b, h in hl.grid([batch, nheads_q]):
    _RDIM_SIZE_3 = 128
    # src[helion_kernels.py:113]: for b, h in hl.grid([batch, nheads_q]):
    # src[helion_kernels.py:114]:     h_kv = h // group
    # src[helion_kernels.py:115]:     for tile_m in hl.tile(m_dim):
    # src[helion_kernels.py:113-137]: ...
    _launcher(_helion_causal_attention_bshd, (32 * 4,), q, k, v, out, qk_scale, _RDIM_SIZE_3, num_warps=8, num_stages=3)
    # src[helion_kernels.py:138]: return out
    return out