"""Generated by Helion, checked in as plain Triton. Do not edit by hand.

Regenerate with:
    python tools/generate.py --batch 8 --seqlen 512 --nheads 16 --head-dim 64 --dtype bf16 --backward

batch=8 seqlen_q=512 seqlen_k=512 nheads=16 head_dim=64 dtype=bf16 causal=False backward
"""

from __future__ import annotations

KERNEL_SPEC = {
    'key': 'b8_sq512_sk512_hq16_hkv16_d64_bf16_noncausal',
    'batch': 8,
    'seqlen_q': 512,
    'seqlen_k': 512,
    'nheads_q': 16,
    'nheads_kv': 16,
    'head_dim': 64,
    'dtype': 'bf16',
    'causal': False,
    'backward': True,
}


import torch
import triton
import triton.language as tl
from torch._inductor.runtime import triton_helpers
from torch._inductor.runtime.triton_compat import libdevice
from .._launcher import default_launcher as _default_launcher
from .._runtime import get_num_sm
from .._runtime import set_triton_allocator

_BLOCK_SIZE_2 = tl.constexpr(256)
_BLOCK_SIZE_4 = tl.constexpr(64)
_BLOCK_SIZE_7 = tl.constexpr(64)
_BLOCK_SIZE_8 = tl.constexpr(128)
_BLOCK_SIZE_11 = tl.constexpr(128)
_BLOCK_SIZE_12 = tl.constexpr(32)
# src[helion_kernels.py:234]: def attention_backward_bshd(
# src[helion_kernels.py:235]:     q: torch.Tensor,
# src[helion_kernels.py:236]:     k: torch.Tensor,
# src[helion_kernels.py:234-336]: ...
set_triton_allocator()

@triton.jit
def _helion_attention_backward_bshd(q, k, lse, out, grad_out, v, dq, dk, dv, x_grid_sem, qk_scale, sm_scale, _NUM_SM: tl.constexpr, _RDIM_SIZE_3: tl.constexpr):
    # src[helion_kernels.py:335]: dv[b, tile_n, h, :] = dv_acc.to(dv.dtype)
    dv_desc = tl.make_tensor_descriptor(dv, [8, 512, 16, 64], [524288, 1024, 64, 1], [1, _BLOCK_SIZE_11, 1, 64])
    # src[helion_kernels.py:312]: for b, h in hl.grid([batch, nheads]):
    # src[helion_kernels.py:313]:     for tile_n in hl.tile(n_dim):
    # src[helion_kernels.py:314]:         k_blk = k[b, tile_n, h, :]
    # src[helion_kernels.py:312-335]: ...
    total_pids = 8 * 16 + 8 * 16 + 8 * 16
    block_size = tl.cdiv(total_pids, _NUM_SM)
    start_pid = tl.program_id(0) * block_size
    end_pid = start_pid + block_size
    if end_pid > total_pids:
        end_pid = total_pids
    for virtual_pid in tl.range(start_pid, end_pid):
        if virtual_pid >= 0 and virtual_pid < 0 + 8 * 16:
            pid_shared = virtual_pid
            # src[helion_kernels.py:271]: for b, h in hl.grid([batch, nheads]):
            # src[helion_kernels.py:272]:     for tile_m in hl.tile(m_dim):
            # src[helion_kernels.py:273]:         m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
            # src[helion_kernels.py:271-284]: ...
            if pid_shared < 8 * 16:
                # src[helion_kernels.py:271]: for b, h in hl.grid([batch, nheads]):
                num_blocks_0 = 8
                pid_0 = pid_shared % num_blocks_0
                pid_1 = pid_shared // num_blocks_0
                offset_0 = pid_0
                offset_1 = pid_1
                indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
                # src[helion_kernels.py:272]: for tile_m in hl.tile(m_dim):
                # src[helion_kernels.py:273]:     m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
                # src[helion_kernels.py:274]:     l_i = hl.full([tile_m], 1.0, dtype=torch.float32)
                # src[helion_kernels.py:272-284]: ...
                for offset_2 in tl.range(0, 512, _BLOCK_SIZE_2, loop_unroll_factor=3, disallow_acc_multi_buffer=True):
                    indices_2 = offset_2 + tl.arange(0, _BLOCK_SIZE_2).to(tl.int32)
                    # src[helion_kernels.py:273]: m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
                    m_i = tl.full([_BLOCK_SIZE_2], float('-inf'), tl.float32)
                    # src[helion_kernels.py:274]: l_i = hl.full([tile_m], 1.0, dtype=torch.float32)
                    l_i = tl.full([_BLOCK_SIZE_2], 1.0, tl.float32)
                    # src[helion_kernels.py:275]: q_blk = q[b, tile_m, h, :]
                    q_blk = tl.load(q + (offset_0 * 524288 + indices_2[:, None] * 1024 + offset_1 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:276]: for tile_n in hl.tile(n_dim):
                    # src[helion_kernels.py:277]:     k_blk = k[b, tile_n, h, :]
                    # src[helion_kernels.py:278]:     qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
                    # src[helion_kernels.py:276-283]: ...
                    for offset_4 in tl.range(0, 512, _BLOCK_SIZE_4, loop_unroll_factor=3):
                        indices_4 = offset_4 + tl.arange(0, _BLOCK_SIZE_4).to(tl.int32)
                        q_blk_copy = q_blk
                        m_i_copy = m_i
                        l_i_copy = l_i
                        q_blk_copy_0 = q_blk_copy
                        m_i_copy_0 = m_i_copy
                        l_i_copy_0 = l_i_copy
                        # src[helion_kernels.py:277]: k_blk = k[b, tile_n, h, :]
                        k_blk = tl.load(k + (offset_0 * 524288 + indices_4[:, None] * 1024 + offset_1 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:278]: qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
                        v_0 = tl.cast(qk_scale, tl.bfloat16)
                        v_1 = q_blk_copy_0 * v_0
                        permute = tl.permute(k_blk, [1, 0])
                        qk = tl.dot(tl.cast(v_1, tl.bfloat16), tl.cast(permute, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:279]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
                        amax = tl.cast(tl.max(qk, 1), tl.float32)
                        v_2 = tl.maximum(m_i_copy_0, amax, tl.PropagateNan.ALL)
                        # src[helion_kernels.py:280]: p = torch.exp2(qk - m_ij[:, None])
                        subscript = v_2[:, None]
                        v_3 = qk - subscript
                        v_4 = libdevice.exp2(v_3)
                        # src[helion_kernels.py:281]: alpha = torch.exp2(m_i - m_ij)
                        v_5 = m_i_copy_0 - v_2
                        v_6 = libdevice.exp2(v_5)
                        # src[helion_kernels.py:282]: l_i = l_i * alpha + torch.sum(p, -1)
                        v_7 = l_i_copy_0 * v_6
                        sum_1 = tl.cast(tl.sum(v_4, 1), tl.float32)
                        l_i = v_7 + sum_1
                        # src[helion_kernels.py:283]: m_i = m_ij
                        m_i = v_2
                    # src[helion_kernels.py:284]: lse[b, tile_m, h] = m_i + torch.log2(l_i)
                    v_9 = libdevice.log2(l_i)
                    v_10 = m_i + v_9
                    tl.store(lse + (offset_0 * 8192 + indices_2 * 16 + offset_1 * 1), v_10, None)
            elif pid_shared < 8 * 16 + 8 * 16:
                # src[helion_kernels.py:289]: for b, h in hl.grid([batch, nheads]):
                pid_shared -= tl.cast(8 * 16, tl.int32)
                num_blocks_1 = 8
                pid_2 = pid_shared % num_blocks_1
                pid_3 = pid_shared // num_blocks_1
                offset_5 = pid_2
                offset_6 = pid_3
                indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
                # src[helion_kernels.py:290]: for tile_m in hl.tile(m_dim):
                # src[helion_kernels.py:291]:     q_blk = q[b, tile_m, h, :]
                # src[helion_kernels.py:292]:     out_blk = out[b, tile_m, h, :]
                # src[helion_kernels.py:290-307]: ...
                for offset_7 in tl.range(0, 512, _BLOCK_SIZE_7):
                    indices_7 = offset_7 + tl.arange(0, _BLOCK_SIZE_7).to(tl.int32)
                    # src[helion_kernels.py:291]: q_blk = q[b, tile_m, h, :]
                    q_blk_1 = tl.load(q + (offset_5 * 524288 + indices_7[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:292]: out_blk = out[b, tile_m, h, :]
                    out_blk = tl.load(out + (offset_5 * 524288 + indices_7[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:293]: grad_out_blk = grad_out[b, tile_m, h, :]
                    grad_out_blk = tl.load(grad_out + (offset_5 * 524288 + indices_7[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:295]: out_blk.to(torch.float32) * grad_out_blk.to(torch.float32), -1
                    v_11 = tl.cast(out_blk, tl.float32)
                    v_12 = tl.cast(grad_out_blk, tl.float32)
                    v_13 = v_11 * v_12
                    # src[helion_kernels.py:294]: delta = torch.sum(
                    # src[helion_kernels.py:295]:     out_blk.to(torch.float32) * grad_out_blk.to(torch.float32), -1
                    # src[helion_kernels.py:296]: )
                    delta = tl.cast(tl.sum(v_13, 1), tl.float32)
                    # src[helion_kernels.py:297]: lse_blk = lse[b, tile_m, h]
                    lse_blk = tl.load(lse + (offset_5 * 8192 + indices_7 * 16 + offset_6 * 1), None)
                    # src[helion_kernels.py:298]: dq_acc = hl.zeros([tile_m, head_dim], dtype=torch.float32)
                    dq_acc = tl.full([_BLOCK_SIZE_7, _RDIM_SIZE_3], 0.0, tl.float32)
                    # src[helion_kernels.py:299]: for tile_n in hl.tile(n_dim):
                    # src[helion_kernels.py:300]:     k_blk = k[b, tile_n, h, :]
                    # src[helion_kernels.py:301]:     v_blk = v[b, tile_n, h, :]
                    # src[helion_kernels.py:299-306]: ...
                    for offset_8 in tl.range(0, 512, _BLOCK_SIZE_8, loop_unroll_factor=2, flatten=True):
                        indices_8 = offset_8 + tl.arange(0, _BLOCK_SIZE_8).to(tl.int32)
                        q_blk_1_copy = q_blk_1
                        lse_blk_copy = lse_blk
                        grad_out_blk_copy = grad_out_blk
                        delta_copy = delta
                        dq_acc_copy = dq_acc
                        q_blk_1_copy_0 = q_blk_1_copy
                        lse_blk_copy_0 = lse_blk_copy
                        grad_out_blk_copy_0 = grad_out_blk_copy
                        delta_copy_0 = delta_copy
                        dq_acc_copy_0 = dq_acc_copy
                        # src[helion_kernels.py:300]: k_blk = k[b, tile_n, h, :]
                        k_blk_1 = tl.load(k + (offset_5 * 524288 + indices_8[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:301]: v_blk = v[b, tile_n, h, :]
                        v_blk = tl.load(v + (offset_5 * 524288 + indices_8[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:302]: qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
                        v_14 = tl.cast(qk_scale, tl.bfloat16)
                        v_15 = q_blk_1_copy_0 * v_14
                        permute_1 = tl.permute(k_blk_1, [1, 0])
                        qk_1 = tl.dot(tl.cast(v_15, tl.bfloat16), tl.cast(permute_1, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:303]: p = torch.exp2(qk - lse_blk[:, None])
                        subscript_1 = lse_blk_copy_0[:, None]
                        v_16 = qk_1 - subscript_1
                        v_17 = libdevice.exp2(v_16)
                        # src[helion_kernels.py:304]: dp = hl.dot(grad_out_blk, v_blk.T, out_dtype=torch.float32)
                        permute_2 = tl.permute(v_blk, [1, 0])
                        dp = tl.dot(tl.cast(grad_out_blk_copy_0, tl.bfloat16), tl.cast(permute_2, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:305]: ds = p * (dp - delta[:, None])
                        subscript_2 = delta_copy_0[:, None]
                        v_18 = dp - subscript_2
                        v_19 = v_17 * v_18
                        # src[helion_kernels.py:306]: dq_acc = hl.dot(ds.to(k_blk.dtype), k_blk, acc=dq_acc)
                        v_20 = tl.cast(v_19, tl.bfloat16)
                        dq_acc = tl.dot(tl.cast(v_20, tl.bfloat16), tl.cast(k_blk_1, tl.bfloat16), acc=dq_acc_copy_0, input_precision='tf32', out_dtype=tl.float32)
                    # src[helion_kernels.py:307]: dq[b, tile_m, h, :] = (dq_acc * sm_scale).to(dq.dtype)
                    v_21 = dq_acc * sm_scale
                    v_22 = tl.cast(v_21, tl.bfloat16)
                    tl.store(dq + (offset_5 * 524288 + indices_7[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), v_22, None)
            else:
                # src[helion_kernels.py:312]: for b, h in hl.grid([batch, nheads]):
                pid_shared -= tl.cast(8 * 16 + 8 * 16, tl.int32)
                num_blocks_2 = 8
                pid_4 = pid_shared % num_blocks_2
                pid_5 = pid_shared // num_blocks_2
                offset_9 = pid_4
                offset_10 = pid_5
                indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
                # src[helion_kernels.py:313]: for tile_n in hl.tile(n_dim):
                # src[helion_kernels.py:314]:     k_blk = k[b, tile_n, h, :]
                # src[helion_kernels.py:315]:     v_blk = v[b, tile_n, h, :]
                # src[helion_kernels.py:313-335]: ...
                for offset_11 in tl.range(0, 512, _BLOCK_SIZE_11, loop_unroll_factor=3):
                    indices_11 = offset_11 + tl.arange(0, _BLOCK_SIZE_11).to(tl.int32)
                    # src[helion_kernels.py:314]: k_blk = k[b, tile_n, h, :]
                    k_blk_2 = tl.load(k + (offset_9 * 524288 + indices_11[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:315]: v_blk = v[b, tile_n, h, :]
                    v_blk_1 = tl.load(v + (offset_9 * 524288 + indices_11[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:316]: dk_acc = hl.zeros([tile_n, head_dim], dtype=torch.float32)
                    dk_acc = tl.full([_BLOCK_SIZE_11, _RDIM_SIZE_3], 0.0, tl.float32)
                    # src[helion_kernels.py:317]: dv_acc = hl.zeros([tile_n, head_dim], dtype=torch.float32)
                    dv_acc = tl.full([_BLOCK_SIZE_11, _RDIM_SIZE_3], 0.0, tl.float32)
                    # src[helion_kernels.py:318]: for tile_m in hl.tile(m_dim):
                    # src[helion_kernels.py:319]:     q_blk = q[b, tile_m, h, :]
                    # src[helion_kernels.py:320]:     out_blk = out[b, tile_m, h, :]
                    # src[helion_kernels.py:318-333]: ...
                    for offset_12 in tl.range(0, 512, _BLOCK_SIZE_12):
                        indices_12 = offset_12 + tl.arange(0, _BLOCK_SIZE_12).to(tl.int32)
                        k_blk_2_copy = k_blk_2
                        v_blk_1_copy = v_blk_1
                        dk_acc_copy = dk_acc
                        dv_acc_copy = dv_acc
                        k_blk_2_copy_0 = k_blk_2_copy
                        v_blk_1_copy_0 = v_blk_1_copy
                        dk_acc_copy_0 = dk_acc_copy
                        dv_acc_copy_0 = dv_acc_copy
                        # src[helion_kernels.py:319]: q_blk = q[b, tile_m, h, :]
                        q_blk_2 = tl.load(q + (offset_9 * 524288 + indices_12[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:320]: out_blk = out[b, tile_m, h, :]
                        out_blk_1 = tl.load(out + (offset_9 * 524288 + indices_12[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:321]: grad_out_blk = grad_out[b, tile_m, h, :]
                        grad_out_blk_1 = tl.load(grad_out + (offset_9 * 524288 + indices_12[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:323]: out_blk.to(torch.float32) * grad_out_blk.to(torch.float32), -1
                        v_23 = tl.cast(out_blk_1, tl.float32)
                        v_24 = tl.cast(grad_out_blk_1, tl.float32)
                        v_25 = v_23 * v_24
                        # src[helion_kernels.py:322]: delta = torch.sum(
                        # src[helion_kernels.py:323]:     out_blk.to(torch.float32) * grad_out_blk.to(torch.float32), -1
                        # src[helion_kernels.py:324]: )
                        delta_1 = tl.cast(tl.sum(v_25, 1), tl.float32)
                        # src[helion_kernels.py:325]: lse_blk = lse[b, tile_m, h]
                        lse_blk_1 = tl.load(lse + (offset_9 * 8192 + indices_12 * 16 + offset_10 * 1), None)
                        # src[helion_kernels.py:326]: qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
                        v_26 = tl.cast(qk_scale, tl.bfloat16)
                        v_27 = q_blk_2 * v_26
                        permute_3 = tl.permute(k_blk_2_copy_0, [1, 0])
                        qk_2 = tl.dot(tl.cast(v_27, tl.bfloat16), tl.cast(permute_3, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:327]: p = torch.exp2(qk - lse_blk[:, None])
                        subscript_3 = lse_blk_1[:, None]
                        v_28 = qk_2 - subscript_3
                        v_29 = libdevice.exp2(v_28)
                        # src[helion_kernels.py:328]: dp = hl.dot(grad_out_blk, v_blk.T, out_dtype=torch.float32)
                        permute_4 = tl.permute(v_blk_1_copy_0, [1, 0])
                        dp_1 = tl.dot(tl.cast(grad_out_blk_1, tl.bfloat16), tl.cast(permute_4, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:329]: ds = p * (dp - delta[:, None])
                        subscript_4 = delta_1[:, None]
                        v_30 = dp_1 - subscript_4
                        v_31 = v_29 * v_30
                        # src[helion_kernels.py:330]: dk_acc = hl.dot(ds.T.to(q_blk.dtype), q_blk, acc=dk_acc)
                        permute_5 = tl.permute(v_31, [1, 0])
                        v_32 = tl.cast(permute_5, tl.bfloat16)
                        dk_acc = tl.dot(tl.cast(v_32, tl.bfloat16), tl.cast(q_blk_2, tl.bfloat16), acc=dk_acc_copy_0, input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:332]: p.T.to(grad_out_blk.dtype), grad_out_blk, acc=dv_acc
                        permute_6 = tl.permute(v_29, [1, 0])
                        v_33 = tl.cast(permute_6, tl.bfloat16)
                        # src[helion_kernels.py:331]: dv_acc = hl.dot(
                        # src[helion_kernels.py:332]:     p.T.to(grad_out_blk.dtype), grad_out_blk, acc=dv_acc
                        # src[helion_kernels.py:333]: )
                        dv_acc = tl.dot(tl.cast(v_33, tl.bfloat16), tl.cast(grad_out_blk_1, tl.bfloat16), acc=dv_acc_copy_0, input_precision='tf32', out_dtype=tl.float32)
                    # src[helion_kernels.py:334]: dk[b, tile_n, h, :] = (dk_acc * sm_scale).to(dk.dtype)
                    v_34 = dk_acc * sm_scale
                    v_35 = tl.cast(v_34, tl.bfloat16)
                    tl.store(dk + (offset_9 * 524288 + indices_11[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), v_35, None)
                    # src[helion_kernels.py:335]: dv[b, tile_n, h, :] = dv_acc.to(dv.dtype)
                    v_36 = tl.cast(dv_acc, tl.bfloat16)
                    dv_desc.store([offset_9, offset_11, offset_10, 0 + 0], tl.cast(tl.reshape(v_36, [1, _BLOCK_SIZE_11, 1, _RDIM_SIZE_3]), tl.bfloat16))
    # src[helion_kernels.py:312]: for b, h in hl.grid([batch, nheads]):
    # src[helion_kernels.py:313]:     for tile_n in hl.tile(n_dim):
    # src[helion_kernels.py:314]:         k_blk = k[b, tile_n, h, :]
    # src[helion_kernels.py:312-335]: ...
    triton_helpers.x_grid_barrier(x_grid_sem)
    for virtual_pid in tl.range(start_pid, end_pid):
        if virtual_pid >= 0 + 8 * 16 and virtual_pid < 0 + 8 * 16 + 8 * 16:
            pid_shared = virtual_pid
            # src[helion_kernels.py:271]: for b, h in hl.grid([batch, nheads]):
            # src[helion_kernels.py:272]:     for tile_m in hl.tile(m_dim):
            # src[helion_kernels.py:273]:         m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
            # src[helion_kernels.py:271-284]: ...
            if pid_shared < 8 * 16:
                # src[helion_kernels.py:271]: for b, h in hl.grid([batch, nheads]):
                num_blocks_0 = 8
                pid_0 = pid_shared % num_blocks_0
                pid_1 = pid_shared // num_blocks_0
                offset_0 = pid_0
                offset_1 = pid_1
                indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
                # src[helion_kernels.py:272]: for tile_m in hl.tile(m_dim):
                # src[helion_kernels.py:273]:     m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
                # src[helion_kernels.py:274]:     l_i = hl.full([tile_m], 1.0, dtype=torch.float32)
                # src[helion_kernels.py:272-284]: ...
                for offset_2 in tl.range(0, 512, _BLOCK_SIZE_2, loop_unroll_factor=3, disallow_acc_multi_buffer=True):
                    indices_2 = offset_2 + tl.arange(0, _BLOCK_SIZE_2).to(tl.int32)
                    # src[helion_kernels.py:273]: m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
                    m_i = tl.full([_BLOCK_SIZE_2], float('-inf'), tl.float32)
                    # src[helion_kernels.py:274]: l_i = hl.full([tile_m], 1.0, dtype=torch.float32)
                    l_i = tl.full([_BLOCK_SIZE_2], 1.0, tl.float32)
                    # src[helion_kernels.py:275]: q_blk = q[b, tile_m, h, :]
                    q_blk = tl.load(q + (offset_0 * 524288 + indices_2[:, None] * 1024 + offset_1 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:276]: for tile_n in hl.tile(n_dim):
                    # src[helion_kernels.py:277]:     k_blk = k[b, tile_n, h, :]
                    # src[helion_kernels.py:278]:     qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
                    # src[helion_kernels.py:276-283]: ...
                    for offset_4 in tl.range(0, 512, _BLOCK_SIZE_4, loop_unroll_factor=3):
                        indices_4 = offset_4 + tl.arange(0, _BLOCK_SIZE_4).to(tl.int32)
                        q_blk_copy = q_blk
                        m_i_copy = m_i
                        l_i_copy = l_i
                        q_blk_copy_0 = q_blk_copy
                        m_i_copy_0 = m_i_copy
                        l_i_copy_0 = l_i_copy
                        # src[helion_kernels.py:277]: k_blk = k[b, tile_n, h, :]
                        k_blk = tl.load(k + (offset_0 * 524288 + indices_4[:, None] * 1024 + offset_1 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:278]: qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
                        v_0 = tl.cast(qk_scale, tl.bfloat16)
                        v_1 = q_blk_copy_0 * v_0
                        permute = tl.permute(k_blk, [1, 0])
                        qk = tl.dot(tl.cast(v_1, tl.bfloat16), tl.cast(permute, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:279]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
                        amax = tl.cast(tl.max(qk, 1), tl.float32)
                        v_2 = tl.maximum(m_i_copy_0, amax, tl.PropagateNan.ALL)
                        # src[helion_kernels.py:280]: p = torch.exp2(qk - m_ij[:, None])
                        subscript = v_2[:, None]
                        v_3 = qk - subscript
                        v_4 = libdevice.exp2(v_3)
                        # src[helion_kernels.py:281]: alpha = torch.exp2(m_i - m_ij)
                        v_5 = m_i_copy_0 - v_2
                        v_6 = libdevice.exp2(v_5)
                        # src[helion_kernels.py:282]: l_i = l_i * alpha + torch.sum(p, -1)
                        v_7 = l_i_copy_0 * v_6
                        sum_1 = tl.cast(tl.sum(v_4, 1), tl.float32)
                        l_i = v_7 + sum_1
                        # src[helion_kernels.py:283]: m_i = m_ij
                        m_i = v_2
                    # src[helion_kernels.py:284]: lse[b, tile_m, h] = m_i + torch.log2(l_i)
                    v_9 = libdevice.log2(l_i)
                    v_10 = m_i + v_9
                    tl.store(lse + (offset_0 * 8192 + indices_2 * 16 + offset_1 * 1), v_10, None)
            elif pid_shared < 8 * 16 + 8 * 16:
                # src[helion_kernels.py:289]: for b, h in hl.grid([batch, nheads]):
                pid_shared -= tl.cast(8 * 16, tl.int32)
                num_blocks_1 = 8
                pid_2 = pid_shared % num_blocks_1
                pid_3 = pid_shared // num_blocks_1
                offset_5 = pid_2
                offset_6 = pid_3
                indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
                # src[helion_kernels.py:290]: for tile_m in hl.tile(m_dim):
                # src[helion_kernels.py:291]:     q_blk = q[b, tile_m, h, :]
                # src[helion_kernels.py:292]:     out_blk = out[b, tile_m, h, :]
                # src[helion_kernels.py:290-307]: ...
                for offset_7 in tl.range(0, 512, _BLOCK_SIZE_7):
                    indices_7 = offset_7 + tl.arange(0, _BLOCK_SIZE_7).to(tl.int32)
                    # src[helion_kernels.py:291]: q_blk = q[b, tile_m, h, :]
                    q_blk_1 = tl.load(q + (offset_5 * 524288 + indices_7[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:292]: out_blk = out[b, tile_m, h, :]
                    out_blk = tl.load(out + (offset_5 * 524288 + indices_7[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:293]: grad_out_blk = grad_out[b, tile_m, h, :]
                    grad_out_blk = tl.load(grad_out + (offset_5 * 524288 + indices_7[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:295]: out_blk.to(torch.float32) * grad_out_blk.to(torch.float32), -1
                    v_11 = tl.cast(out_blk, tl.float32)
                    v_12 = tl.cast(grad_out_blk, tl.float32)
                    v_13 = v_11 * v_12
                    # src[helion_kernels.py:294]: delta = torch.sum(
                    # src[helion_kernels.py:295]:     out_blk.to(torch.float32) * grad_out_blk.to(torch.float32), -1
                    # src[helion_kernels.py:296]: )
                    delta = tl.cast(tl.sum(v_13, 1), tl.float32)
                    # src[helion_kernels.py:297]: lse_blk = lse[b, tile_m, h]
                    lse_blk = tl.load(lse + (offset_5 * 8192 + indices_7 * 16 + offset_6 * 1), None)
                    # src[helion_kernels.py:298]: dq_acc = hl.zeros([tile_m, head_dim], dtype=torch.float32)
                    dq_acc = tl.full([_BLOCK_SIZE_7, _RDIM_SIZE_3], 0.0, tl.float32)
                    # src[helion_kernels.py:299]: for tile_n in hl.tile(n_dim):
                    # src[helion_kernels.py:300]:     k_blk = k[b, tile_n, h, :]
                    # src[helion_kernels.py:301]:     v_blk = v[b, tile_n, h, :]
                    # src[helion_kernels.py:299-306]: ...
                    for offset_8 in tl.range(0, 512, _BLOCK_SIZE_8, loop_unroll_factor=2, flatten=True):
                        indices_8 = offset_8 + tl.arange(0, _BLOCK_SIZE_8).to(tl.int32)
                        q_blk_1_copy = q_blk_1
                        lse_blk_copy = lse_blk
                        grad_out_blk_copy = grad_out_blk
                        delta_copy = delta
                        dq_acc_copy = dq_acc
                        q_blk_1_copy_0 = q_blk_1_copy
                        lse_blk_copy_0 = lse_blk_copy
                        grad_out_blk_copy_0 = grad_out_blk_copy
                        delta_copy_0 = delta_copy
                        dq_acc_copy_0 = dq_acc_copy
                        # src[helion_kernels.py:300]: k_blk = k[b, tile_n, h, :]
                        k_blk_1 = tl.load(k + (offset_5 * 524288 + indices_8[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:301]: v_blk = v[b, tile_n, h, :]
                        v_blk = tl.load(v + (offset_5 * 524288 + indices_8[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:302]: qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
                        v_14 = tl.cast(qk_scale, tl.bfloat16)
                        v_15 = q_blk_1_copy_0 * v_14
                        permute_1 = tl.permute(k_blk_1, [1, 0])
                        qk_1 = tl.dot(tl.cast(v_15, tl.bfloat16), tl.cast(permute_1, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:303]: p = torch.exp2(qk - lse_blk[:, None])
                        subscript_1 = lse_blk_copy_0[:, None]
                        v_16 = qk_1 - subscript_1
                        v_17 = libdevice.exp2(v_16)
                        # src[helion_kernels.py:304]: dp = hl.dot(grad_out_blk, v_blk.T, out_dtype=torch.float32)
                        permute_2 = tl.permute(v_blk, [1, 0])
                        dp = tl.dot(tl.cast(grad_out_blk_copy_0, tl.bfloat16), tl.cast(permute_2, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:305]: ds = p * (dp - delta[:, None])
                        subscript_2 = delta_copy_0[:, None]
                        v_18 = dp - subscript_2
                        v_19 = v_17 * v_18
                        # src[helion_kernels.py:306]: dq_acc = hl.dot(ds.to(k_blk.dtype), k_blk, acc=dq_acc)
                        v_20 = tl.cast(v_19, tl.bfloat16)
                        dq_acc = tl.dot(tl.cast(v_20, tl.bfloat16), tl.cast(k_blk_1, tl.bfloat16), acc=dq_acc_copy_0, input_precision='tf32', out_dtype=tl.float32)
                    # src[helion_kernels.py:307]: dq[b, tile_m, h, :] = (dq_acc * sm_scale).to(dq.dtype)
                    v_21 = dq_acc * sm_scale
                    v_22 = tl.cast(v_21, tl.bfloat16)
                    tl.store(dq + (offset_5 * 524288 + indices_7[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), v_22, None)
            else:
                # src[helion_kernels.py:312]: for b, h in hl.grid([batch, nheads]):
                pid_shared -= tl.cast(8 * 16 + 8 * 16, tl.int32)
                num_blocks_2 = 8
                pid_4 = pid_shared % num_blocks_2
                pid_5 = pid_shared // num_blocks_2
                offset_9 = pid_4
                offset_10 = pid_5
                indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
                # src[helion_kernels.py:313]: for tile_n in hl.tile(n_dim):
                # src[helion_kernels.py:314]:     k_blk = k[b, tile_n, h, :]
                # src[helion_kernels.py:315]:     v_blk = v[b, tile_n, h, :]
                # src[helion_kernels.py:313-335]: ...
                for offset_11 in tl.range(0, 512, _BLOCK_SIZE_11, loop_unroll_factor=3):
                    indices_11 = offset_11 + tl.arange(0, _BLOCK_SIZE_11).to(tl.int32)
                    # src[helion_kernels.py:314]: k_blk = k[b, tile_n, h, :]
                    k_blk_2 = tl.load(k + (offset_9 * 524288 + indices_11[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:315]: v_blk = v[b, tile_n, h, :]
                    v_blk_1 = tl.load(v + (offset_9 * 524288 + indices_11[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:316]: dk_acc = hl.zeros([tile_n, head_dim], dtype=torch.float32)
                    dk_acc = tl.full([_BLOCK_SIZE_11, _RDIM_SIZE_3], 0.0, tl.float32)
                    # src[helion_kernels.py:317]: dv_acc = hl.zeros([tile_n, head_dim], dtype=torch.float32)
                    dv_acc = tl.full([_BLOCK_SIZE_11, _RDIM_SIZE_3], 0.0, tl.float32)
                    # src[helion_kernels.py:318]: for tile_m in hl.tile(m_dim):
                    # src[helion_kernels.py:319]:     q_blk = q[b, tile_m, h, :]
                    # src[helion_kernels.py:320]:     out_blk = out[b, tile_m, h, :]
                    # src[helion_kernels.py:318-333]: ...
                    for offset_12 in tl.range(0, 512, _BLOCK_SIZE_12):
                        indices_12 = offset_12 + tl.arange(0, _BLOCK_SIZE_12).to(tl.int32)
                        k_blk_2_copy = k_blk_2
                        v_blk_1_copy = v_blk_1
                        dk_acc_copy = dk_acc
                        dv_acc_copy = dv_acc
                        k_blk_2_copy_0 = k_blk_2_copy
                        v_blk_1_copy_0 = v_blk_1_copy
                        dk_acc_copy_0 = dk_acc_copy
                        dv_acc_copy_0 = dv_acc_copy
                        # src[helion_kernels.py:319]: q_blk = q[b, tile_m, h, :]
                        q_blk_2 = tl.load(q + (offset_9 * 524288 + indices_12[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:320]: out_blk = out[b, tile_m, h, :]
                        out_blk_1 = tl.load(out + (offset_9 * 524288 + indices_12[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:321]: grad_out_blk = grad_out[b, tile_m, h, :]
                        grad_out_blk_1 = tl.load(grad_out + (offset_9 * 524288 + indices_12[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:323]: out_blk.to(torch.float32) * grad_out_blk.to(torch.float32), -1
                        v_23 = tl.cast(out_blk_1, tl.float32)
                        v_24 = tl.cast(grad_out_blk_1, tl.float32)
                        v_25 = v_23 * v_24
                        # src[helion_kernels.py:322]: delta = torch.sum(
                        # src[helion_kernels.py:323]:     out_blk.to(torch.float32) * grad_out_blk.to(torch.float32), -1
                        # src[helion_kernels.py:324]: )
                        delta_1 = tl.cast(tl.sum(v_25, 1), tl.float32)
                        # src[helion_kernels.py:325]: lse_blk = lse[b, tile_m, h]
                        lse_blk_1 = tl.load(lse + (offset_9 * 8192 + indices_12 * 16 + offset_10 * 1), None)
                        # src[helion_kernels.py:326]: qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
                        v_26 = tl.cast(qk_scale, tl.bfloat16)
                        v_27 = q_blk_2 * v_26
                        permute_3 = tl.permute(k_blk_2_copy_0, [1, 0])
                        qk_2 = tl.dot(tl.cast(v_27, tl.bfloat16), tl.cast(permute_3, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:327]: p = torch.exp2(qk - lse_blk[:, None])
                        subscript_3 = lse_blk_1[:, None]
                        v_28 = qk_2 - subscript_3
                        v_29 = libdevice.exp2(v_28)
                        # src[helion_kernels.py:328]: dp = hl.dot(grad_out_blk, v_blk.T, out_dtype=torch.float32)
                        permute_4 = tl.permute(v_blk_1_copy_0, [1, 0])
                        dp_1 = tl.dot(tl.cast(grad_out_blk_1, tl.bfloat16), tl.cast(permute_4, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:329]: ds = p * (dp - delta[:, None])
                        subscript_4 = delta_1[:, None]
                        v_30 = dp_1 - subscript_4
                        v_31 = v_29 * v_30
                        # src[helion_kernels.py:330]: dk_acc = hl.dot(ds.T.to(q_blk.dtype), q_blk, acc=dk_acc)
                        permute_5 = tl.permute(v_31, [1, 0])
                        v_32 = tl.cast(permute_5, tl.bfloat16)
                        dk_acc = tl.dot(tl.cast(v_32, tl.bfloat16), tl.cast(q_blk_2, tl.bfloat16), acc=dk_acc_copy_0, input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:332]: p.T.to(grad_out_blk.dtype), grad_out_blk, acc=dv_acc
                        permute_6 = tl.permute(v_29, [1, 0])
                        v_33 = tl.cast(permute_6, tl.bfloat16)
                        # src[helion_kernels.py:331]: dv_acc = hl.dot(
                        # src[helion_kernels.py:332]:     p.T.to(grad_out_blk.dtype), grad_out_blk, acc=dv_acc
                        # src[helion_kernels.py:333]: )
                        dv_acc = tl.dot(tl.cast(v_33, tl.bfloat16), tl.cast(grad_out_blk_1, tl.bfloat16), acc=dv_acc_copy_0, input_precision='tf32', out_dtype=tl.float32)
                    # src[helion_kernels.py:334]: dk[b, tile_n, h, :] = (dk_acc * sm_scale).to(dk.dtype)
                    v_34 = dk_acc * sm_scale
                    v_35 = tl.cast(v_34, tl.bfloat16)
                    tl.store(dk + (offset_9 * 524288 + indices_11[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), v_35, None)
                    # src[helion_kernels.py:335]: dv[b, tile_n, h, :] = dv_acc.to(dv.dtype)
                    v_36 = tl.cast(dv_acc, tl.bfloat16)
                    dv_desc.store([offset_9, offset_11, offset_10, 0 + 0], tl.cast(tl.reshape(v_36, [1, _BLOCK_SIZE_11, 1, _RDIM_SIZE_3]), tl.bfloat16))
    # src[helion_kernels.py:312]: for b, h in hl.grid([batch, nheads]):
    # src[helion_kernels.py:313]:     for tile_n in hl.tile(n_dim):
    # src[helion_kernels.py:314]:         k_blk = k[b, tile_n, h, :]
    # src[helion_kernels.py:312-335]: ...
    triton_helpers.x_grid_barrier(x_grid_sem)
    for virtual_pid in tl.range(start_pid, end_pid):
        if virtual_pid >= 0 + 8 * 16 + 8 * 16 and virtual_pid < 0 + 8 * 16 + 8 * 16 + 8 * 16:
            pid_shared = virtual_pid
            # src[helion_kernels.py:271]: for b, h in hl.grid([batch, nheads]):
            # src[helion_kernels.py:272]:     for tile_m in hl.tile(m_dim):
            # src[helion_kernels.py:273]:         m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
            # src[helion_kernels.py:271-284]: ...
            if pid_shared < 8 * 16:
                # src[helion_kernels.py:271]: for b, h in hl.grid([batch, nheads]):
                num_blocks_0 = 8
                pid_0 = pid_shared % num_blocks_0
                pid_1 = pid_shared // num_blocks_0
                offset_0 = pid_0
                offset_1 = pid_1
                indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
                # src[helion_kernels.py:272]: for tile_m in hl.tile(m_dim):
                # src[helion_kernels.py:273]:     m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
                # src[helion_kernels.py:274]:     l_i = hl.full([tile_m], 1.0, dtype=torch.float32)
                # src[helion_kernels.py:272-284]: ...
                for offset_2 in tl.range(0, 512, _BLOCK_SIZE_2, loop_unroll_factor=3, disallow_acc_multi_buffer=True):
                    indices_2 = offset_2 + tl.arange(0, _BLOCK_SIZE_2).to(tl.int32)
                    # src[helion_kernels.py:273]: m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
                    m_i = tl.full([_BLOCK_SIZE_2], float('-inf'), tl.float32)
                    # src[helion_kernels.py:274]: l_i = hl.full([tile_m], 1.0, dtype=torch.float32)
                    l_i = tl.full([_BLOCK_SIZE_2], 1.0, tl.float32)
                    # src[helion_kernels.py:275]: q_blk = q[b, tile_m, h, :]
                    q_blk = tl.load(q + (offset_0 * 524288 + indices_2[:, None] * 1024 + offset_1 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:276]: for tile_n in hl.tile(n_dim):
                    # src[helion_kernels.py:277]:     k_blk = k[b, tile_n, h, :]
                    # src[helion_kernels.py:278]:     qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
                    # src[helion_kernels.py:276-283]: ...
                    for offset_4 in tl.range(0, 512, _BLOCK_SIZE_4, loop_unroll_factor=3):
                        indices_4 = offset_4 + tl.arange(0, _BLOCK_SIZE_4).to(tl.int32)
                        q_blk_copy = q_blk
                        m_i_copy = m_i
                        l_i_copy = l_i
                        q_blk_copy_0 = q_blk_copy
                        m_i_copy_0 = m_i_copy
                        l_i_copy_0 = l_i_copy
                        # src[helion_kernels.py:277]: k_blk = k[b, tile_n, h, :]
                        k_blk = tl.load(k + (offset_0 * 524288 + indices_4[:, None] * 1024 + offset_1 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:278]: qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
                        v_0 = tl.cast(qk_scale, tl.bfloat16)
                        v_1 = q_blk_copy_0 * v_0
                        permute = tl.permute(k_blk, [1, 0])
                        qk = tl.dot(tl.cast(v_1, tl.bfloat16), tl.cast(permute, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:279]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
                        amax = tl.cast(tl.max(qk, 1), tl.float32)
                        v_2 = tl.maximum(m_i_copy_0, amax, tl.PropagateNan.ALL)
                        # src[helion_kernels.py:280]: p = torch.exp2(qk - m_ij[:, None])
                        subscript = v_2[:, None]
                        v_3 = qk - subscript
                        v_4 = libdevice.exp2(v_3)
                        # src[helion_kernels.py:281]: alpha = torch.exp2(m_i - m_ij)
                        v_5 = m_i_copy_0 - v_2
                        v_6 = libdevice.exp2(v_5)
                        # src[helion_kernels.py:282]: l_i = l_i * alpha + torch.sum(p, -1)
                        v_7 = l_i_copy_0 * v_6
                        sum_1 = tl.cast(tl.sum(v_4, 1), tl.float32)
                        l_i = v_7 + sum_1
                        # src[helion_kernels.py:283]: m_i = m_ij
                        m_i = v_2
                    # src[helion_kernels.py:284]: lse[b, tile_m, h] = m_i + torch.log2(l_i)
                    v_9 = libdevice.log2(l_i)
                    v_10 = m_i + v_9
                    tl.store(lse + (offset_0 * 8192 + indices_2 * 16 + offset_1 * 1), v_10, None)
            elif pid_shared < 8 * 16 + 8 * 16:
                # src[helion_kernels.py:289]: for b, h in hl.grid([batch, nheads]):
                pid_shared -= tl.cast(8 * 16, tl.int32)
                num_blocks_1 = 8
                pid_2 = pid_shared % num_blocks_1
                pid_3 = pid_shared // num_blocks_1
                offset_5 = pid_2
                offset_6 = pid_3
                indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
                # src[helion_kernels.py:290]: for tile_m in hl.tile(m_dim):
                # src[helion_kernels.py:291]:     q_blk = q[b, tile_m, h, :]
                # src[helion_kernels.py:292]:     out_blk = out[b, tile_m, h, :]
                # src[helion_kernels.py:290-307]: ...
                for offset_7 in tl.range(0, 512, _BLOCK_SIZE_7):
                    indices_7 = offset_7 + tl.arange(0, _BLOCK_SIZE_7).to(tl.int32)
                    # src[helion_kernels.py:291]: q_blk = q[b, tile_m, h, :]
                    q_blk_1 = tl.load(q + (offset_5 * 524288 + indices_7[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:292]: out_blk = out[b, tile_m, h, :]
                    out_blk = tl.load(out + (offset_5 * 524288 + indices_7[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:293]: grad_out_blk = grad_out[b, tile_m, h, :]
                    grad_out_blk = tl.load(grad_out + (offset_5 * 524288 + indices_7[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:295]: out_blk.to(torch.float32) * grad_out_blk.to(torch.float32), -1
                    v_11 = tl.cast(out_blk, tl.float32)
                    v_12 = tl.cast(grad_out_blk, tl.float32)
                    v_13 = v_11 * v_12
                    # src[helion_kernels.py:294]: delta = torch.sum(
                    # src[helion_kernels.py:295]:     out_blk.to(torch.float32) * grad_out_blk.to(torch.float32), -1
                    # src[helion_kernels.py:296]: )
                    delta = tl.cast(tl.sum(v_13, 1), tl.float32)
                    # src[helion_kernels.py:297]: lse_blk = lse[b, tile_m, h]
                    lse_blk = tl.load(lse + (offset_5 * 8192 + indices_7 * 16 + offset_6 * 1), None)
                    # src[helion_kernels.py:298]: dq_acc = hl.zeros([tile_m, head_dim], dtype=torch.float32)
                    dq_acc = tl.full([_BLOCK_SIZE_7, _RDIM_SIZE_3], 0.0, tl.float32)
                    # src[helion_kernels.py:299]: for tile_n in hl.tile(n_dim):
                    # src[helion_kernels.py:300]:     k_blk = k[b, tile_n, h, :]
                    # src[helion_kernels.py:301]:     v_blk = v[b, tile_n, h, :]
                    # src[helion_kernels.py:299-306]: ...
                    for offset_8 in tl.range(0, 512, _BLOCK_SIZE_8, loop_unroll_factor=2, flatten=True):
                        indices_8 = offset_8 + tl.arange(0, _BLOCK_SIZE_8).to(tl.int32)
                        q_blk_1_copy = q_blk_1
                        lse_blk_copy = lse_blk
                        grad_out_blk_copy = grad_out_blk
                        delta_copy = delta
                        dq_acc_copy = dq_acc
                        q_blk_1_copy_0 = q_blk_1_copy
                        lse_blk_copy_0 = lse_blk_copy
                        grad_out_blk_copy_0 = grad_out_blk_copy
                        delta_copy_0 = delta_copy
                        dq_acc_copy_0 = dq_acc_copy
                        # src[helion_kernels.py:300]: k_blk = k[b, tile_n, h, :]
                        k_blk_1 = tl.load(k + (offset_5 * 524288 + indices_8[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:301]: v_blk = v[b, tile_n, h, :]
                        v_blk = tl.load(v + (offset_5 * 524288 + indices_8[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:302]: qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
                        v_14 = tl.cast(qk_scale, tl.bfloat16)
                        v_15 = q_blk_1_copy_0 * v_14
                        permute_1 = tl.permute(k_blk_1, [1, 0])
                        qk_1 = tl.dot(tl.cast(v_15, tl.bfloat16), tl.cast(permute_1, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:303]: p = torch.exp2(qk - lse_blk[:, None])
                        subscript_1 = lse_blk_copy_0[:, None]
                        v_16 = qk_1 - subscript_1
                        v_17 = libdevice.exp2(v_16)
                        # src[helion_kernels.py:304]: dp = hl.dot(grad_out_blk, v_blk.T, out_dtype=torch.float32)
                        permute_2 = tl.permute(v_blk, [1, 0])
                        dp = tl.dot(tl.cast(grad_out_blk_copy_0, tl.bfloat16), tl.cast(permute_2, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:305]: ds = p * (dp - delta[:, None])
                        subscript_2 = delta_copy_0[:, None]
                        v_18 = dp - subscript_2
                        v_19 = v_17 * v_18
                        # src[helion_kernels.py:306]: dq_acc = hl.dot(ds.to(k_blk.dtype), k_blk, acc=dq_acc)
                        v_20 = tl.cast(v_19, tl.bfloat16)
                        dq_acc = tl.dot(tl.cast(v_20, tl.bfloat16), tl.cast(k_blk_1, tl.bfloat16), acc=dq_acc_copy_0, input_precision='tf32', out_dtype=tl.float32)
                    # src[helion_kernels.py:307]: dq[b, tile_m, h, :] = (dq_acc * sm_scale).to(dq.dtype)
                    v_21 = dq_acc * sm_scale
                    v_22 = tl.cast(v_21, tl.bfloat16)
                    tl.store(dq + (offset_5 * 524288 + indices_7[:, None] * 1024 + offset_6 * 64 + (0 + indices_3)[None, :] * 1), v_22, None)
            else:
                # src[helion_kernels.py:312]: for b, h in hl.grid([batch, nheads]):
                pid_shared -= tl.cast(8 * 16 + 8 * 16, tl.int32)
                num_blocks_2 = 8
                pid_4 = pid_shared % num_blocks_2
                pid_5 = pid_shared // num_blocks_2
                offset_9 = pid_4
                offset_10 = pid_5
                indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
                # src[helion_kernels.py:313]: for tile_n in hl.tile(n_dim):
                # src[helion_kernels.py:314]:     k_blk = k[b, tile_n, h, :]
                # src[helion_kernels.py:315]:     v_blk = v[b, tile_n, h, :]
                # src[helion_kernels.py:313-335]: ...
                for offset_11 in tl.range(0, 512, _BLOCK_SIZE_11, loop_unroll_factor=3):
                    indices_11 = offset_11 + tl.arange(0, _BLOCK_SIZE_11).to(tl.int32)
                    # src[helion_kernels.py:314]: k_blk = k[b, tile_n, h, :]
                    k_blk_2 = tl.load(k + (offset_9 * 524288 + indices_11[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:315]: v_blk = v[b, tile_n, h, :]
                    v_blk_1 = tl.load(v + (offset_9 * 524288 + indices_11[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                    # src[helion_kernels.py:316]: dk_acc = hl.zeros([tile_n, head_dim], dtype=torch.float32)
                    dk_acc = tl.full([_BLOCK_SIZE_11, _RDIM_SIZE_3], 0.0, tl.float32)
                    # src[helion_kernels.py:317]: dv_acc = hl.zeros([tile_n, head_dim], dtype=torch.float32)
                    dv_acc = tl.full([_BLOCK_SIZE_11, _RDIM_SIZE_3], 0.0, tl.float32)
                    # src[helion_kernels.py:318]: for tile_m in hl.tile(m_dim):
                    # src[helion_kernels.py:319]:     q_blk = q[b, tile_m, h, :]
                    # src[helion_kernels.py:320]:     out_blk = out[b, tile_m, h, :]
                    # src[helion_kernels.py:318-333]: ...
                    for offset_12 in tl.range(0, 512, _BLOCK_SIZE_12):
                        indices_12 = offset_12 + tl.arange(0, _BLOCK_SIZE_12).to(tl.int32)
                        k_blk_2_copy = k_blk_2
                        v_blk_1_copy = v_blk_1
                        dk_acc_copy = dk_acc
                        dv_acc_copy = dv_acc
                        k_blk_2_copy_0 = k_blk_2_copy
                        v_blk_1_copy_0 = v_blk_1_copy
                        dk_acc_copy_0 = dk_acc_copy
                        dv_acc_copy_0 = dv_acc_copy
                        # src[helion_kernels.py:319]: q_blk = q[b, tile_m, h, :]
                        q_blk_2 = tl.load(q + (offset_9 * 524288 + indices_12[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:320]: out_blk = out[b, tile_m, h, :]
                        out_blk_1 = tl.load(out + (offset_9 * 524288 + indices_12[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:321]: grad_out_blk = grad_out[b, tile_m, h, :]
                        grad_out_blk_1 = tl.load(grad_out + (offset_9 * 524288 + indices_12[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), None)
                        # src[helion_kernels.py:323]: out_blk.to(torch.float32) * grad_out_blk.to(torch.float32), -1
                        v_23 = tl.cast(out_blk_1, tl.float32)
                        v_24 = tl.cast(grad_out_blk_1, tl.float32)
                        v_25 = v_23 * v_24
                        # src[helion_kernels.py:322]: delta = torch.sum(
                        # src[helion_kernels.py:323]:     out_blk.to(torch.float32) * grad_out_blk.to(torch.float32), -1
                        # src[helion_kernels.py:324]: )
                        delta_1 = tl.cast(tl.sum(v_25, 1), tl.float32)
                        # src[helion_kernels.py:325]: lse_blk = lse[b, tile_m, h]
                        lse_blk_1 = tl.load(lse + (offset_9 * 8192 + indices_12 * 16 + offset_10 * 1), None)
                        # src[helion_kernels.py:326]: qk = hl.dot(q_blk * qk_scale, k_blk.T, out_dtype=torch.float32)
                        v_26 = tl.cast(qk_scale, tl.bfloat16)
                        v_27 = q_blk_2 * v_26
                        permute_3 = tl.permute(k_blk_2_copy_0, [1, 0])
                        qk_2 = tl.dot(tl.cast(v_27, tl.bfloat16), tl.cast(permute_3, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:327]: p = torch.exp2(qk - lse_blk[:, None])
                        subscript_3 = lse_blk_1[:, None]
                        v_28 = qk_2 - subscript_3
                        v_29 = libdevice.exp2(v_28)
                        # src[helion_kernels.py:328]: dp = hl.dot(grad_out_blk, v_blk.T, out_dtype=torch.float32)
                        permute_4 = tl.permute(v_blk_1_copy_0, [1, 0])
                        dp_1 = tl.dot(tl.cast(grad_out_blk_1, tl.bfloat16), tl.cast(permute_4, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:329]: ds = p * (dp - delta[:, None])
                        subscript_4 = delta_1[:, None]
                        v_30 = dp_1 - subscript_4
                        v_31 = v_29 * v_30
                        # src[helion_kernels.py:330]: dk_acc = hl.dot(ds.T.to(q_blk.dtype), q_blk, acc=dk_acc)
                        permute_5 = tl.permute(v_31, [1, 0])
                        v_32 = tl.cast(permute_5, tl.bfloat16)
                        dk_acc = tl.dot(tl.cast(v_32, tl.bfloat16), tl.cast(q_blk_2, tl.bfloat16), acc=dk_acc_copy_0, input_precision='tf32', out_dtype=tl.float32)
                        # src[helion_kernels.py:332]: p.T.to(grad_out_blk.dtype), grad_out_blk, acc=dv_acc
                        permute_6 = tl.permute(v_29, [1, 0])
                        v_33 = tl.cast(permute_6, tl.bfloat16)
                        # src[helion_kernels.py:331]: dv_acc = hl.dot(
                        # src[helion_kernels.py:332]:     p.T.to(grad_out_blk.dtype), grad_out_blk, acc=dv_acc
                        # src[helion_kernels.py:333]: )
                        dv_acc = tl.dot(tl.cast(v_33, tl.bfloat16), tl.cast(grad_out_blk_1, tl.bfloat16), acc=dv_acc_copy_0, input_precision='tf32', out_dtype=tl.float32)
                    # src[helion_kernels.py:334]: dk[b, tile_n, h, :] = (dk_acc * sm_scale).to(dk.dtype)
                    v_34 = dk_acc * sm_scale
                    v_35 = tl.cast(v_34, tl.bfloat16)
                    tl.store(dk + (offset_9 * 524288 + indices_11[:, None] * 1024 + offset_10 * 64 + (0 + indices_3)[None, :] * 1), v_35, None)
                    # src[helion_kernels.py:335]: dv[b, tile_n, h, :] = dv_acc.to(dv.dtype)
                    v_36 = tl.cast(dv_acc, tl.bfloat16)
                    dv_desc.store([offset_9, offset_11, offset_10, 0 + 0], tl.cast(tl.reshape(v_36, [1, _BLOCK_SIZE_11, 1, _RDIM_SIZE_3]), tl.bfloat16))

def attention_backward(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, out: torch.Tensor, grad_out: torch.Tensor, sm_scale: float, *, _launcher=_default_launcher):
    """Non-causal MHA backward over ``[batch, seq, heads, dim]`` tensors.

    This follows the recompute strategy used by FlashAttention backward.  A
    first pass recreates the per-query log-sum-exp values that the existing
    forward-only modules do not expose.  The following two passes recompute
    probabilities blockwise and produce dQ, then dK/dV, without materializing
    the quadratic attention matrix.

    The first checked-in specialization intentionally covers MHA with equal
    query/key lengths only.  The generator rejects causal, cross-attention, and
    GQA shapes until their masking and reduction rules are implemented here.
    """
    # src[helion_kernels.py:254]: batch = q.size(0)
    batch = q.size(0)
    # src[helion_kernels.py:255]: m_dim = q.size(1)
    m_dim = q.size(1)
    # src[helion_kernels.py:256]: n_dim = k.size(1)
    n_dim = k.size(1)
    # src[helion_kernels.py:257]: nheads = hl.specialize(q.size(2))
    nheads = 16
    # src[helion_kernels.py:259]: dq = torch.empty_like(q)
    dq = torch.empty_like(q)
    # src[helion_kernels.py:260]: dk = torch.empty_like(k)
    dk = torch.empty_like(k)
    # src[helion_kernels.py:261]: dv = torch.empty_like(v)
    dv = torch.empty_like(v)
    # src[helion_kernels.py:262]: lse = torch.empty(
    # src[helion_kernels.py:263]:     (batch, m_dim, nheads),
    # src[helion_kernels.py:264]:     dtype=torch.float32,
    # src[helion_kernels.py:262-266]: ...
    lse = torch.empty((batch, m_dim, nheads), dtype=torch.float32, device=q.device)
    # src[helion_kernels.py:267]: qk_scale = sm_scale * 1.44269504088896340736
    qk_scale = sm_scale * 1.4426950408889634
    # src[helion_kernels.py:271]: for b, h in hl.grid([batch, nheads]):
    _NUM_SM = get_num_sm(q.device)
    _RDIM_SIZE_3 = 64
    # src[helion_kernels.py:312]: for b, h in hl.grid([batch, nheads]):
    # src[helion_kernels.py:313]:     for tile_n in hl.tile(n_dim):
    # src[helion_kernels.py:314]:         k_blk = k[b, tile_n, h, :]
    # src[helion_kernels.py:312-335]: ...
    _launcher(_helion_attention_backward_bshd, (_NUM_SM,), q, k, lse, out, grad_out, v, dq, dk, dv, torch.zeros((1,), device=q.device, dtype=torch.uint32), qk_scale, sm_scale, _NUM_SM, _RDIM_SIZE_3, num_warps=4, num_stages=1, launch_cooperative_grid=True)
    # src[helion_kernels.py:336]: return dq, dk, dv
    return (dq, dk, dv)