"""Generated by Helion, checked in as plain Triton. Do not edit by hand.

Regenerate with:
    python tools/generate.py --batch 8 --seqlen 1024 --nheads 8 --head-dim 32 --dtype bf16 --causal

batch=8 seqlen_q=1024 seqlen_k=1024 nheads=8 head_dim=32 dtype=bf16 causal=True

Autotuning provenance:
    Helion version: 1.4.0
    Config selection: fixed
    Autotuning wall time: 0.000 s
    Measured time: 0.034656 ms
    Config: helion.Config(block_sizes=[64, 64], indexing=['pointer', 'pointer', 'pointer', 'pointer', 'pointer'], num_stages=3, num_warps=4, pid_type='flat')
"""

from __future__ import annotations

KERNEL_SPEC = {
    'key': 'b8_sq1024_sk1024_hq8_hkv8_d32_bf16_causal',
    'batch': 8,
    'seqlen_q': 1024,
    'seqlen_k': 1024,
    'nheads_q': 8,
    'nheads_kv': 8,
    'head_dim': 32,
    'dtype': 'bf16',
    'causal': True,
    'backward': False,
    'varlen': False,
}


import torch
import triton
import triton.language as tl
from torch._inductor.runtime.triton_compat import libdevice
from .._launcher import default_launcher as _default_launcher
from .._runtime import get_num_sm
from .._runtime import set_triton_allocator

_BLOCK_SIZE_2 = tl.constexpr(64)
_BLOCK_SIZE_4 = tl.constexpr(64)

@triton.jit
def _helion_causal_attention_bshd_16k(q, k, v, out, qk_scale, _RDIM_SIZE_3: tl.constexpr):
    # src[helion_kernels.py:444]: for tile_b, tile_h, tile_m in hl.tile(
    # src[helion_kernels.py:445]:     [batch, nheads_q, m_dim], block_size=[1, 1, None]
    # src[helion_kernels.py:446]: ):
    num_blocks_0 = 8
    num_blocks_1 = 8
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    pid_2 = tl.program_id(0) // (num_blocks_0 * num_blocks_1)
    offset_0 = pid_0
    offset_1 = pid_1
    offset_2 = pid_2 * _BLOCK_SIZE_2
    indices_2 = (offset_2 + tl.arange(0, _BLOCK_SIZE_2)).to(tl.int32)
    indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
    # src[helion_kernels.py:450]: m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
    m_i = tl.full([_BLOCK_SIZE_2], float('-inf'), tl.float32)
    # src[helion_kernels.py:451]: l_i = hl.zeros([tile_m], dtype=torch.float32)
    l_i = tl.full([_BLOCK_SIZE_2], 0.0, tl.float32)
    # src[helion_kernels.py:452]: acc = hl.zeros([tile_m, head_dim], dtype=torch.float32)
    acc = tl.full([_BLOCK_SIZE_2, _RDIM_SIZE_3], 0.0, tl.float32)
    # src[helion_kernels.py:453]: q_blk = q[b, tile_m, h, :]
    q_blk = tl.load(q + (offset_0 * 262144 + indices_2[:, None] * 256 + offset_1 * 32 + (0 + indices_3)[None, :] * 1), None)
    # src[helion_kernels.py:455]: key_stop = tile_m.end
    tile_end = offset_2 + _BLOCK_SIZE_2
    # src[helion_kernels.py:458]: for tile_n in hl.tile(0, key_stop):
    # src[helion_kernels.py:459]:     k_blk = k[b, tile_n, h_kv, :]
    # src[helion_kernels.py:460]:     qk = hl.dot(q_blk, k_blk.T, out_dtype=torch.float32) * qk_scale
    # src[helion_kernels.py:458-486]: ...
    end_0 = tl.cast(tile_end, tl.int32)
    for offset_4 in tl.range(0, tl.cast(tile_end, tl.int32), _BLOCK_SIZE_4):
        indices_4 = offset_4 + tl.arange(0, _BLOCK_SIZE_4).to(tl.int32)
        mask_4 = indices_4 < tile_end
        q_blk_copy = q_blk
        m_i_copy = m_i
        l_i_copy = l_i
        acc_copy = acc
        q_blk_copy_0 = q_blk_copy
        m_i_copy_0 = m_i_copy
        l_i_copy_0 = l_i_copy
        acc_copy_0 = acc_copy
        # src[helion_kernels.py:459]: k_blk = k[b, tile_n, h_kv, :]
        k_blk = tl.load(k + (offset_0 * 262144 + indices_4[:, None] * 256 + offset_1 * 32 + (0 + indices_3)[None, :] * 1), mask_4[:, None], other=0)
        # src[helion_kernels.py:460]: qk = hl.dot(q_blk, k_blk.T, out_dtype=torch.float32) * qk_scale
        permute = tl.permute(k_blk, [1, 0])
        dot = tl.dot(tl.cast(q_blk_copy_0, tl.bfloat16), tl.cast(permute, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
        v_0 = dot * qk_scale
        # src[helion_kernels.py:463]: if m_dim == n_dim and tile_n.end <= tile_m.begin:
        tile_end_1 = tl.minimum(offset_4 + _BLOCK_SIZE_4, end_0)
        le = tile_end_1 <= offset_2
        # src[helion_kernels.py:463]: if m_dim == n_dim and tile_n.end <= tile_m.begin:
        # src[helion_kernels.py:464]:     m_ij = torch.maximum(m_i, torch.amax(qk, -1))
        # src[helion_kernels.py:465]:     p = torch.exp2(qk - m_ij[:, None])
        # src[helion_kernels.py:463-481]: ...
        if le:
            m_i_copy_0_copy = m_i_copy_0
            v_0_copy = v_0
            m_i_copy_0_copy_0 = m_i_copy_0_copy
            v_0_copy_0 = v_0_copy
            # src[helion_kernels.py:464]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
            _mask_to = tl.where(tl.broadcast_to(mask_4[None, :], [_BLOCK_SIZE_2, _BLOCK_SIZE_4]), v_0_copy_0, tl.full([], float('-inf'), tl.float32))
            amax = tl.cast(tl.max(_mask_to, 1), tl.float32)
            v_1 = tl.maximum(m_i_copy_0_copy_0, amax, tl.PropagateNan.ALL)
            # src[helion_kernels.py:465]: p = torch.exp2(qk - m_ij[:, None])
            subscript = v_1[:, None]
            v_2 = v_0_copy_0 - subscript
            v_3 = libdevice.exp2(v_2)
            # src[helion_kernels.py:466]: alpha = torch.exp2(m_i - m_ij)
            v_4 = m_i_copy_0_copy_0 - v_1
            v_5 = libdevice.exp2(v_4)
        else:
            # src[helion_kernels.py:463]: if m_dim == n_dim and tile_n.end <= tile_m.begin:
            # src[helion_kernels.py:464]:     m_ij = torch.maximum(m_i, torch.amax(qk, -1))
            # src[helion_kernels.py:465]:     p = torch.exp2(qk - m_ij[:, None])
            # src[helion_kernels.py:463-481]: ...
            v_0_copy_1 = v_0
            m_i_copy_0_copy_1 = m_i_copy_0
            v_0_copy_1_0 = v_0_copy_1
            m_i_copy_0_copy_1_0 = m_i_copy_0_copy_1
            # src[helion_kernels.py:468]: score_mask = tile_n.index[None, :] <= (
            subscript_1 = indices_4[None, :]
            # src[helion_kernels.py:469]: tile_m.index + causal_offset
            v_6 = tl.full([], 0, tl.int32)
            v_7 = indices_2 + v_6
            # src[helion_kernels.py:468]: score_mask = tile_n.index[None, :] <= (
            # src[helion_kernels.py:469]:     tile_m.index + causal_offset
            # src[helion_kernels.py:470]: )[:, None]
            subscript_2 = v_7[:, None]
            v_8 = subscript_1 <= subscript_2
            # src[helion_kernels.py:471]: qk = torch.where(score_mask, qk, float("-inf"))
            scalar_tensor = tl.full([], float('-inf'), tl.float32)
            v_0 = tl.where(v_8, v_0_copy_1_0, scalar_tensor)
            # src[helion_kernels.py:472]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
            _mask_to_1 = tl.where(tl.broadcast_to(mask_4[None, :], [_BLOCK_SIZE_2, _BLOCK_SIZE_4]), v_0, tl.full([], float('-inf'), tl.float32))
            amax_1 = tl.cast(tl.max(_mask_to_1, 1), tl.float32)
            v_1 = tl.maximum(m_i_copy_0_copy_1_0, amax_1, tl.PropagateNan.ALL)
            # src[helion_kernels.py:473]: has_key = m_ij != float("-inf")
            v_10 = tl.full([], float('-inf'), tl.float32)
            v_11 = v_1 != v_10
            # src[helion_kernels.py:476]: score_mask, qk - m_ij[:, None], float("-inf")
            subscript_3 = v_1[:, None]
            v_12 = v_0 - subscript_3
            # src[helion_kernels.py:475]: torch.where(
            # src[helion_kernels.py:476]:     score_mask, qk - m_ij[:, None], float("-inf")
            # src[helion_kernels.py:477]: )
            scalar_tensor_1 = tl.full([], float('-inf'), tl.float32)
            where_1 = tl.where(v_8, v_12, scalar_tensor_1)
            # src[helion_kernels.py:474]: p = torch.exp2(
            # src[helion_kernels.py:475]:     torch.where(
            # src[helion_kernels.py:476]:         score_mask, qk - m_ij[:, None], float("-inf")
            # src[helion_kernels.py:474-478]: ...
            v_3 = libdevice.exp2(where_1)
            # src[helion_kernels.py:480]: has_key, torch.exp2(m_i - m_ij), 1.0
            v_14 = m_i_copy_0_copy_1_0 - v_1
            v_15 = libdevice.exp2(v_14)
            # src[helion_kernels.py:479]: alpha = torch.where(
            # src[helion_kernels.py:480]:     has_key, torch.exp2(m_i - m_ij), 1.0
            # src[helion_kernels.py:481]: )
            scalar_tensor_2 = tl.full([], 1.0, tl.float32)
            v_5 = tl.where(v_11, v_15, scalar_tensor_2)
        # src[helion_kernels.py:482]: l_i = l_i * alpha + torch.sum(p, -1)
        v_16 = l_i_copy_0 * v_5
        _mask_to_2 = tl.where(tl.broadcast_to(mask_4[None, :], [_BLOCK_SIZE_2, _BLOCK_SIZE_4]), v_3, tl.full([], 0, tl.float32))
        sum_1 = tl.cast(tl.sum(_mask_to_2, 1), tl.float32)
        l_i = v_16 + sum_1
        # src[helion_kernels.py:483]: acc = acc * alpha[:, None]
        subscript_4 = v_5[:, None]
        v_18 = acc_copy_0 * subscript_4
        # src[helion_kernels.py:484]: v_blk = v[b, tile_n, h_kv, :]
        v_blk = tl.load(v + (offset_0 * 262144 + indices_4[:, None] * 256 + offset_1 * 32 + (0 + indices_3)[None, :] * 1), mask_4[:, None], other=0)
        # src[helion_kernels.py:485]: acc = hl.dot(p.to(v_blk.dtype), v_blk, acc=acc)
        v_19 = tl.cast(v_3, tl.bfloat16)
        acc = tl.dot(tl.cast(v_19, tl.bfloat16), tl.cast(v_blk, tl.bfloat16), acc=v_18, input_precision='tf32', out_dtype=tl.float32)
        # src[helion_kernels.py:486]: m_i = m_ij
        m_i = v_1
    # src[helion_kernels.py:488]: (l_i > 0)[:, None],
    v_20 = tl.full([], 0.0, tl.float32)
    v_21 = l_i > v_20
    subscript_5 = v_21[:, None]
    # src[helion_kernels.py:489]: acc / torch.where(l_i > 0, l_i, 1.0)[:, None],
    v_22 = tl.full([], 0.0, tl.float32)
    v_23 = l_i > v_22
    scalar_tensor_3 = tl.full([], 1.0, tl.float32)
    where = tl.where(v_23, l_i, scalar_tensor_3)
    subscript_6 = where[:, None]
    v_24 = acc / subscript_6
    # src[helion_kernels.py:487]: result = torch.where(
    # src[helion_kernels.py:488]:     (l_i > 0)[:, None],
    # src[helion_kernels.py:489]:     acc / torch.where(l_i > 0, l_i, 1.0)[:, None],
    # src[helion_kernels.py:487-491]: ...
    scalar_tensor_4 = tl.full([], 0.0, tl.float32)
    result = tl.where(subscript_5, v_24, scalar_tensor_4)
    # src[helion_kernels.py:492]: out[b, tile_m, h, :] = result.to(out.dtype)
    v_25 = tl.cast(result, tl.bfloat16)
    tl.store(out + (offset_0 * 262144 + indices_2[:, None] * 256 + offset_1 * 32 + (0 + indices_3)[None, :] * 1), v_25, None)

def attention(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, sm_scale: float, *, _launcher=_default_launcher):
    """Tile-parallel causal attention for explicitly validated shapes."""
    # src[helion_kernels.py:431]: batch = q.size(0)
    batch = q.size(0)
    # src[helion_kernels.py:438]: out = torch.empty_like(q)
    out = torch.empty_like(q)
    # src[helion_kernels.py:439]: qk_scale = sm_scale * 1.44269504088896340736
    qk_scale = sm_scale * 1.4426950408889634
    # src[helion_kernels.py:444]: for tile_b, tile_h, tile_m in hl.tile(
    # src[helion_kernels.py:445]:     [batch, nheads_q, m_dim], block_size=[1, 1, None]
    # src[helion_kernels.py:446]: ):
    _BLOCK_SIZE_2 = 64
    _RDIM_SIZE_3 = 32
    # src[helion_kernels.py:444]: for tile_b, tile_h, tile_m in hl.tile(
    # src[helion_kernels.py:445]:     [batch, nheads_q, m_dim], block_size=[1, 1, None]
    # src[helion_kernels.py:446]: ):
    # src[helion_kernels.py:444-492]: ...
    _launcher(_helion_causal_attention_bshd_16k, (8 * 8 * ((1024 + _BLOCK_SIZE_2 - 1) // _BLOCK_SIZE_2),), q, k, v, out, qk_scale, _RDIM_SIZE_3, num_warps=4, num_stages=3)
    # src[helion_kernels.py:493]: return out
    return out