"""Generated by Helion, checked in as plain Triton. Do not edit by hand.

Regenerate with:
    python tools/generate.py --batch 2 --seqlen 200 --seqlen-k 320 --nheads 8 --nheads-kv 2 --head-dim 128 --dtype bf16 --causal --paged --page-size 16

paged page_size=16 batch=2 seqlen_q=200 seqlen_k=320 nheads=8 (GQA 8:2) head_dim=128 dtype=bf16 causal=True

Autotuning provenance:
    Helion version: 1.4.0
    Config selection: autotuned
    Autotuning wall time: 79.985 s
    Measured time: 0.038784 ms
    Config: helion.Config(atomic_indexing=[], block_sizes=[256], indexing=['pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], l2_groupings=[1], load_eviction_policies=['', 'last', '', 'first', '', '', ''], loop_orders=[[0, 1]], num_stages=1, num_warps=16, pid_type='flat', range_flattens=[None, None, None], range_multi_buffers=[None, None, None], range_num_stages=[0, 0, 0], range_unroll_factors=[0, 0, 0], range_warp_specializes=[])
"""

from __future__ import annotations

KERNEL_SPEC = {
    'key': 'paged_b2_sq200_sk320_hq8_hkv2_d128_bf16_causal_ps16',
    'batch': 2,
    'seqlen_q': 200,
    'seqlen_k': 320,
    'nheads_q': 8,
    'nheads_kv': 2,
    'head_dim': 128,
    'dtype': 'bf16',
    'causal': True,
    'backward': False,
    'varlen': False,
    'paged': True,
    'page_size': 16,
}


import torch
import triton
import triton.language as tl
from torch._inductor.runtime import triton_helpers
from torch._inductor.runtime.triton_compat import libdevice
from .._launcher import default_launcher as _default_launcher
from .._runtime import get_num_sm
from .._runtime import set_triton_allocator

_BLOCK_SIZE_2 = tl.constexpr(256)

@triton.jit
def _helion_paged_attention_thd(cu_seqlens_q, seqused_k, q, block_table, k, v, out, block_table_stride_0, block_table_stride_1, cu_seqlens_q_stride_0, k_stride_0, k_stride_1, k_stride_2, k_stride_3, out_stride_0, out_stride_1, out_stride_2, q_stride_0, q_stride_1, q_stride_2, seqused_k_stride_0, v_stride_0, v_stride_1, v_stride_2, v_stride_3, qk_scale, _RDIM_SIZE_3: tl.constexpr, _RDIM_SIZE_5: tl.constexpr):
    # src[helion_kernels.py:629]: for b, h in hl.grid([batch, nheads_q]):
    num_blocks_0 = 2
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0
    offset_0 = pid_0
    offset_1 = pid_1
    indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
    indices_5 = tl.arange(0, _RDIM_SIZE_5).to(tl.int32)
    # src[helion_kernels.py:631]: q_start = cu_seqlens_q[b]
    q_start = tl.load(cu_seqlens_q + offset_0 * cu_seqlens_q_stride_0, None)
    # src[helion_kernels.py:632]: q_end = cu_seqlens_q[b + 1]
    add = 1 + offset_0
    q_end = tl.load(cu_seqlens_q + add * cu_seqlens_q_stride_0, None, eviction_policy='evict_last')
    # src[helion_kernels.py:633]: seqlen_q = q_end - q_start
    v_0 = q_end - q_start
    # src[helion_kernels.py:634]: seqlen_k = seqused_k[b]
    seqlen_k = tl.load(seqused_k + offset_0 * seqused_k_stride_0, None)
    # src[helion_kernels.py:657]: k_page = hl.load(
    # src[helion_kernels.py:658]:     k,
    # src[helion_kernels.py:659]:     [physical_block, slice(None), h_kv, slice(None)],
    # src[helion_kernels.py:657-661]: ...
    symnode_0 = triton_helpers.div_floor_integer(offset_1, 4)
    # src[helion_kernels.py:635]: for tile_m in hl.tile(max_q):
    # src[helion_kernels.py:636]:     valid_m = tile_m.index < seqlen_q
    # src[helion_kernels.py:637]:     q_index = q_start + tile_m.index
    # src[helion_kernels.py:635-701]: ...
    for offset_2 in tl.range(0, 200, _BLOCK_SIZE_2):
        indices_2 = offset_2 + tl.arange(0, _BLOCK_SIZE_2).to(tl.int32)
        mask_2 = indices_2 < 200
        v_0_copy = v_0
        q_start_copy = q_start
        seqlen_k_copy = seqlen_k
        v_0_copy_0 = v_0_copy
        q_start_copy_0 = q_start_copy
        seqlen_k_copy_0 = seqlen_k_copy
        # src[helion_kernels.py:636]: valid_m = tile_m.index < seqlen_q
        v_1 = indices_2 < v_0_copy_0
        # src[helion_kernels.py:637]: q_index = q_start + tile_m.index
        v_2 = q_start_copy_0 + indices_2
        # src[helion_kernels.py:641]: extra_mask=valid_m[:, None],
        subscript = v_1[:, None]
        # src[helion_kernels.py:638]: q_blk = hl.load(
        # src[helion_kernels.py:639]:     q,
        # src[helion_kernels.py:640]:     [q_index, h, slice(None)],
        # src[helion_kernels.py:638-642]: ...
        q_blk = tl.load(q + (v_2[:, None] * q_stride_0 + offset_1 * q_stride_1 + (0 + indices_3)[None, :] * q_stride_2), mask_2[:, None] & subscript, other=0, eviction_policy='evict_first')
        # src[helion_kernels.py:643]: m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
        m_i = tl.full([_BLOCK_SIZE_2], float('-inf'), tl.float32)
        # src[helion_kernels.py:644]: l_i = hl.zeros([tile_m], dtype=torch.float32)
        l_i = tl.full([_BLOCK_SIZE_2], 0.0, tl.float32)
        # src[helion_kernels.py:645]: acc = hl.zeros([tile_m, head_dim], dtype=torch.float32)
        acc = tl.full([_BLOCK_SIZE_2, _RDIM_SIZE_3], 0.0, tl.float32)
        # src[helion_kernels.py:650]: for tile_block in hl.tile(max_blocks, block_size=1):
        # src[helion_kernels.py:651]:     key_positions = (
        # src[helion_kernels.py:652]:         tile_block.begin * page_size + hl.arange(page_size)
        # src[helion_kernels.py:650-690]: ...
        for offset_4 in tl.range(0, 20):
            seqlen_k_copy_0_copy = seqlen_k_copy_0
            q_blk_copy = q_blk
            v_1_copy = v_1
            v_0_copy_0_copy = v_0_copy_0
            m_i_copy = m_i
            l_i_copy = l_i
            acc_copy = acc
            seqlen_k_copy_0_copy_0 = seqlen_k_copy_0_copy
            q_blk_copy_0 = q_blk_copy
            v_1_copy_0 = v_1_copy
            v_0_copy_0_copy_0 = v_0_copy_0_copy
            m_i_copy_0 = m_i_copy
            l_i_copy_0 = l_i_copy
            acc_copy_0 = acc_copy
            # src[helion_kernels.py:652]: tile_block.begin * page_size + hl.arange(page_size)
            mul = 16 * offset_4
            iota = tl.arange(0, 16)
            v_3 = tl.cast(mul, tl.int32)
            v_4 = iota + v_3
            # src[helion_kernels.py:654]: valid_n = key_positions < seqlen_k
            v_5 = v_4 < seqlen_k_copy_0_copy_0
            # src[helion_kernels.py:656]: physical_block = block_table[b, logical_block]
            physical_block = tl.load(block_table + (offset_0 * block_table_stride_0 + offset_4 * block_table_stride_1), None)
            # src[helion_kernels.py:660]: extra_mask=valid_n[:, None],
            subscript_1 = v_5[:, None]
            # src[helion_kernels.py:657]: k_page = hl.load(
            # src[helion_kernels.py:658]:     k,
            # src[helion_kernels.py:659]:     [physical_block, slice(None), h_kv, slice(None)],
            # src[helion_kernels.py:657-661]: ...
            k_page = tl.load(k + (physical_block[:, None] * k_stride_0 + (0 + indices_5)[:, None] * k_stride_1 + symnode_0 * k_stride_2 + (0 + indices_3)[None, :] * k_stride_3), subscript_1, other=0)
            # src[helion_kernels.py:662]: k_blk = k_page.reshape(page_size, head_dim)
            k_blk = tl.reshape(k_page, [_RDIM_SIZE_5, _RDIM_SIZE_3])
            # src[helion_kernels.py:663]: qk = hl.dot(q_blk, k_blk.T, out_dtype=torch.float32) * qk_scale
            permute = tl.permute(k_blk, [1, 0])
            dot = tl.dot(tl.cast(q_blk_copy_0, tl.bfloat16), tl.cast(permute, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
            v_6 = dot * qk_scale
            # src[helion_kernels.py:664]: score_mask = valid_m[:, None] & valid_n[None, :]
            subscript_2 = v_1_copy_0[:, None]
            subscript_3 = v_5[None, :]
            v_7 = subscript_2 & subscript_3
            # src[helion_kernels.py:666]: causal_bound = tile_m.index + seqlen_k - seqlen_q
            v_8 = indices_2 + seqlen_k_copy_0_copy_0
            v_9 = v_8 - v_0_copy_0_copy_0
            # src[helion_kernels.py:668]: key_positions[None, :] <= causal_bound[:, None]
            subscript_4 = v_4[None, :]
            subscript_5 = v_9[:, None]
            v_10 = subscript_4 <= subscript_5
            # src[helion_kernels.py:667]: score_mask = score_mask & (
            # src[helion_kernels.py:668]:     key_positions[None, :] <= causal_bound[:, None]
            # src[helion_kernels.py:669]: )
            v_11 = v_7 & v_10
            # src[helion_kernels.py:670]: qk = torch.where(score_mask, qk, float("-inf"))
            scalar_tensor = tl.full([], float('-inf'), tl.float32)
            qk_1 = tl.where(v_11, v_6, scalar_tensor)
            # src[helion_kernels.py:671]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
            _mask_to = tl.where(tl.broadcast_to(mask_2[:, None], [_BLOCK_SIZE_2, _RDIM_SIZE_5]), qk_1, tl.full([], float('-inf'), tl.float32))
            amax = tl.cast(tl.max(_mask_to, 1), tl.float32)
            v_12 = tl.maximum(m_i_copy_0, amax, tl.PropagateNan.ALL)
            # src[helion_kernels.py:672]: has_key = m_ij != float("-inf")
            v_13 = tl.full([], float('-inf'), tl.float32)
            v_14 = v_12 != v_13
            # src[helion_kernels.py:674]: torch.where(score_mask, qk - m_ij[:, None], float("-inf"))
            subscript_6 = v_12[:, None]
            v_15 = qk_1 - subscript_6
            scalar_tensor_1 = tl.full([], float('-inf'), tl.float32)
            where_1 = tl.where(v_11, v_15, scalar_tensor_1)
            # src[helion_kernels.py:673]: p = torch.exp2(
            # src[helion_kernels.py:674]:     torch.where(score_mask, qk - m_ij[:, None], float("-inf"))
            # src[helion_kernels.py:675]: )
            v_16 = libdevice.exp2(where_1)
            # src[helion_kernels.py:678]: torch.exp2(m_i - m_ij),
            v_17 = m_i_copy_0 - v_12
            v_18 = libdevice.exp2(v_17)
            # src[helion_kernels.py:676]: alpha = torch.where(
            # src[helion_kernels.py:677]:     has_key,
            # src[helion_kernels.py:678]:     torch.exp2(m_i - m_ij),
            # src[helion_kernels.py:676-680]: ...
            scalar_tensor_2 = tl.full([], 1.0, tl.float32)
            alpha = tl.where(v_14, v_18, scalar_tensor_2)
            # src[helion_kernels.py:681]: l_i = l_i * alpha + torch.sum(p, -1)
            v_19 = l_i_copy_0 * alpha
            _mask_to_1 = tl.where(tl.broadcast_to(mask_2[:, None], [_BLOCK_SIZE_2, _RDIM_SIZE_5]), v_16, tl.full([], 0, tl.float32))
            sum_1 = tl.cast(tl.sum(_mask_to_1, 1), tl.float32)
            l_i = v_19 + sum_1
            # src[helion_kernels.py:682]: acc = acc * alpha[:, None]
            subscript_7 = alpha[:, None]
            v_21 = acc_copy_0 * subscript_7
            # src[helion_kernels.py:686]: extra_mask=valid_n[:, None],
            subscript_8 = v_5[:, None]
            # src[helion_kernels.py:683]: v_page = hl.load(
            # src[helion_kernels.py:684]:     v,
            # src[helion_kernels.py:685]:     [physical_block, slice(None), h_kv, slice(None)],
            # src[helion_kernels.py:683-687]: ...
            v_page = tl.load(v + (physical_block[:, None] * v_stride_0 + (0 + indices_5)[:, None] * v_stride_1 + symnode_0 * v_stride_2 + (0 + indices_3)[None, :] * v_stride_3), subscript_8, other=0)
            # src[helion_kernels.py:688]: v_blk = v_page.reshape(page_size, head_dim)
            v_blk = tl.reshape(v_page, [_RDIM_SIZE_5, _RDIM_SIZE_3])
            # src[helion_kernels.py:689]: acc = hl.dot(p.to(v_blk.dtype), v_blk, acc=acc)
            v_22 = tl.cast(v_16, tl.bfloat16)
            acc = tl.dot(tl.cast(v_22, tl.bfloat16), tl.cast(v_blk, tl.bfloat16), acc=v_21, input_precision='tf32', out_dtype=tl.float32)
            # src[helion_kernels.py:690]: m_i = m_ij
            m_i = v_12
        # src[helion_kernels.py:692]: (l_i > 0)[:, None],
        v_23 = tl.full([], 0.0, tl.float32)
        v_24 = l_i > v_23
        subscript_9 = v_24[:, None]
        # src[helion_kernels.py:693]: acc / torch.where(l_i > 0, l_i, 1.0)[:, None],
        v_25 = tl.full([], 0.0, tl.float32)
        v_26 = l_i > v_25
        scalar_tensor_3 = tl.full([], 1.0, tl.float32)
        where = tl.where(v_26, l_i, scalar_tensor_3)
        subscript_10 = where[:, None]
        v_27 = acc / subscript_10
        # src[helion_kernels.py:691]: result = torch.where(
        # src[helion_kernels.py:692]:     (l_i > 0)[:, None],
        # src[helion_kernels.py:693]:     acc / torch.where(l_i > 0, l_i, 1.0)[:, None],
        # src[helion_kernels.py:691-695]: ...
        scalar_tensor_4 = tl.full([], 0.0, tl.float32)
        result = tl.where(subscript_9, v_27, scalar_tensor_4)
        # src[helion_kernels.py:699]: result.to(out.dtype),
        v_28 = tl.cast(result, tl.bfloat16)
        # src[helion_kernels.py:700]: extra_mask=valid_m[:, None],
        subscript_11 = v_1[:, None]
        # src[helion_kernels.py:696]: hl.store(
        # src[helion_kernels.py:697]:     out,
        # src[helion_kernels.py:698]:     [q_index, h, slice(None)],
        # src[helion_kernels.py:696-701]: ...
        tl.store(out + (v_2[:, None] * out_stride_0 + offset_1 * out_stride_1 + (0 + indices_3)[None, :] * out_stride_2), v_28, mask_2[:, None] & subscript_11)

def attention_paged(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, cu_seqlens_q: torch.Tensor, seqused_k: torch.Tensor, block_table: torch.Tensor, max_seqlen_q, max_seqlen_k, sm_scale: float, causal, *, _launcher=_default_launcher):
    """Attention over packed queries and a block-table-addressed paged KV cache.

    Query token totals, physical cache allocation, block-table strides, and
    per-request cache lengths remain dynamic.  The generated specialization
    fixes the batch, maximum lengths, head geometry, page size, dtype, and
    masking mode.  Logical key positions are translated through ``block_table``
    before every K/V load, so physical pages need not be contiguous or ordered.
    """
    # src[helion_kernels.py:626]: out = torch.empty_like(q)
    out = torch.empty_like(q)
    # src[helion_kernels.py:627]: qk_scale = sm_scale * 1.44269504088896340736
    qk_scale = sm_scale * 1.4426950408889634
    # src[helion_kernels.py:629]: for b, h in hl.grid([batch, nheads_q]):
    _RDIM_SIZE_3 = 128
    _RDIM_SIZE_5 = 16
    # src[helion_kernels.py:629]: for b, h in hl.grid([batch, nheads_q]):
    # src[helion_kernels.py:630]:     h_kv = h // group
    # src[helion_kernels.py:631]:     q_start = cu_seqlens_q[b]
    # src[helion_kernels.py:629-701]: ...
    _launcher(_helion_paged_attention_thd, (2 * 8,), cu_seqlens_q, seqused_k, q, block_table, k, v, out, block_table.stride(0), block_table.stride(1), cu_seqlens_q.stride(0), k.stride(0), k.stride(1), k.stride(2), k.stride(3), out.stride(0), out.stride(1), out.stride(2), q.stride(0), q.stride(1), q.stride(2), seqused_k.stride(0), v.stride(0), v.stride(1), v.stride(2), v.stride(3), qk_scale, _RDIM_SIZE_3, _RDIM_SIZE_5, num_warps=16, num_stages=1)
    # src[helion_kernels.py:702]: return out
    return out