"""Generated by Helion, checked in as plain Triton. Do not edit by hand.

Regenerate with:
    python tools/generate.py --batch 4 --seqlen 1 --seqlen-k 1024 --nheads 8 --nheads-kv 2 --head-dim 128 --dtype bf16 --causal --paged --page-size 16

paged page_size=16 batch=4 seqlen_q=1 seqlen_k=1024 nheads=8 (GQA 8:2) head_dim=128 dtype=bf16 causal=True

Autotuning provenance:
    Helion version: unknown (legacy artifact)
    Config selection: incumbent
    Autotuning wall time: unknown (legacy artifact)
    Measured time: 0.071170 ms
    Artifact origin selection: autotuned
    Config: helion.Config(atomic_indexing=[], block_sizes=[1], indexing=['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], l2_groupings=[1], load_eviction_policies=['', '', '', '', '', '', ''], loop_orders=[[0, 1]], num_sm_multiplier=1, num_stages=5, num_warps=4, pid_type='persistent_interleaved', range_flattens=[None, False, True], range_multi_buffers=[None, None, None], range_num_stages=[0, 0, 0], range_unroll_factors=[0, 0, 0], range_warp_specializes=[], static_ranges=[False])
    Rejected search:
        Helion version: 1.4.0
        Autotuning wall time: 66.590 s
        Candidate time: 0.094370 ms
        Incumbent validation time: 0.071170 ms
        Candidate config: helion.Config(atomic_indexing=[], block_sizes=[4], indexing=['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], l2_groupings=[1], load_eviction_policies=['', '', '', '', '', '', ''], loop_orders=[[0, 1]], num_stages=1, num_warps=1, pid_type='flat', range_flattens=[None, None, None], range_multi_buffers=[None, None, None], range_num_stages=[0, 0, 0], range_unroll_factors=[0, 0, 0], range_warp_specializes=[], static_ranges=[False])
"""

from __future__ import annotations

KERNEL_SPEC = {
    'key': 'paged_b4_sq1_sk1024_hq8_hkv2_d128_bf16_causal_ps16',
    'batch': 4,
    'seqlen_q': 1,
    'seqlen_k': 1024,
    'nheads_q': 8,
    'nheads_kv': 2,
    'head_dim': 128,
    'dtype': 'bf16',
    'causal': True,
    'backward': False,
    'varlen': False,
    'paged': True,
    'page_size': 16,
}


import torch
import triton
import triton.language as tl
from torch._inductor.runtime import triton_helpers
from torch._inductor.runtime.triton_compat import libdevice
from .._launcher import default_launcher as _default_launcher
from .._runtime import get_num_sm
from .._runtime import set_triton_allocator

_BLOCK_SIZE_2 = tl.constexpr(1)

@triton.jit
def _helion_paged_attention_thd(cu_seqlens_q, seqused_k, q, block_table, k, v, out, block_table_stride_0, block_table_stride_1, cu_seqlens_q_stride_0, k_stride_0, k_stride_1, k_stride_2, k_stride_3, out_stride_0, out_stride_1, out_stride_2, q_stride_0, q_stride_1, q_stride_2, seqused_k_stride_0, v_stride_0, v_stride_1, v_stride_2, v_stride_3, qk_scale, _NUM_SM: tl.constexpr, _RDIM_SIZE_3: tl.constexpr, _RDIM_SIZE_5: tl.constexpr):
    # src[helion_kernels.py:526]: for b, h in hl.grid([batch, nheads_q]):
    # src[helion_kernels.py:527]:     h_kv = h // group
    # src[helion_kernels.py:528]:     q_start = cu_seqlens_q[b]
    # src[helion_kernels.py:526-598]: ...
    total_pids = 4 * 8
    for virtual_pid in tl.range(tl.program_id(0), total_pids, _NUM_SM):
        # src[helion_kernels.py:526]: for b, h in hl.grid([batch, nheads_q]):
        num_blocks_0 = 4
        pid_0 = virtual_pid % num_blocks_0
        pid_1 = virtual_pid // num_blocks_0
        offset_0 = pid_0
        offset_1 = pid_1
        indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
        indices_5 = tl.arange(0, _RDIM_SIZE_5).to(tl.int32)
        # src[helion_kernels.py:528]: q_start = cu_seqlens_q[b]
        q_start = tl.load(cu_seqlens_q + offset_0 * cu_seqlens_q_stride_0, None)
        # src[helion_kernels.py:529]: q_end = cu_seqlens_q[b + 1]
        add = 1 + offset_0
        q_end = tl.load(cu_seqlens_q + add * cu_seqlens_q_stride_0, None)
        # src[helion_kernels.py:530]: seqlen_q = q_end - q_start
        v_0 = q_end - q_start
        # src[helion_kernels.py:531]: seqlen_k = seqused_k[b]
        seqlen_k = tl.load(seqused_k + offset_0 * seqused_k_stride_0, None)
        # src[helion_kernels.py:554]: k_page = hl.load(
        # src[helion_kernels.py:555]:     k,
        # src[helion_kernels.py:556]:     [physical_block, slice(None), h_kv, slice(None)],
        # src[helion_kernels.py:554-558]: ...
        symnode_0 = triton_helpers.div_floor_integer(offset_1, 4)
        # src[helion_kernels.py:532]: for tile_m in hl.tile(max_q):
        # src[helion_kernels.py:533]:     valid_m = tile_m.index < seqlen_q
        # src[helion_kernels.py:534]:     q_index = q_start + tile_m.index
        # src[helion_kernels.py:532-598]: ...
        for offset_2 in tl.range(0, 1, flatten=False):
            indices_2 = offset_2 + tl.arange(0, 1).to(tl.int32)
            v_0_copy = v_0
            q_start_copy = q_start
            seqlen_k_copy = seqlen_k
            v_0_copy_0 = v_0_copy
            q_start_copy_0 = q_start_copy
            seqlen_k_copy_0 = seqlen_k_copy
            # src[helion_kernels.py:533]: valid_m = tile_m.index < seqlen_q
            v_1 = indices_2 < v_0_copy_0
            # src[helion_kernels.py:534]: q_index = q_start + tile_m.index
            v_2 = q_start_copy_0 + indices_2
            # src[helion_kernels.py:538]: extra_mask=valid_m[:, None],
            subscript = v_1[:, None]
            # src[helion_kernels.py:535]: q_blk = hl.load(
            # src[helion_kernels.py:536]:     q,
            # src[helion_kernels.py:537]:     [q_index, h, slice(None)],
            # src[helion_kernels.py:535-539]: ...
            q_blk = tl.load(q + (v_2[:, None] * q_stride_0 + offset_1 * q_stride_1 + (0 + indices_3)[None, :] * q_stride_2), subscript, other=0)
            # src[helion_kernels.py:540]: m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
            m_i = tl.full([_BLOCK_SIZE_2], float('-inf'), tl.float32)
            # src[helion_kernels.py:541]: l_i = hl.zeros([tile_m], dtype=torch.float32)
            l_i = tl.full([_BLOCK_SIZE_2], 0.0, tl.float32)
            # src[helion_kernels.py:542]: acc = hl.zeros([tile_m, head_dim], dtype=torch.float32)
            acc = tl.full([_BLOCK_SIZE_2, _RDIM_SIZE_3], 0.0, tl.float32)
            # src[helion_kernels.py:547]: for tile_block in hl.tile(max_blocks, block_size=1):
            # src[helion_kernels.py:548]:     key_positions = (
            # src[helion_kernels.py:549]:         tile_block.begin * page_size + hl.arange(page_size)
            # src[helion_kernels.py:547-587]: ...
            for offset_4 in tl.range(0, 64, flatten=True):
                seqlen_k_copy_0_copy = seqlen_k_copy_0
                q_blk_copy = q_blk
                v_1_copy = v_1
                v_0_copy_0_copy = v_0_copy_0
                m_i_copy = m_i
                l_i_copy = l_i
                acc_copy = acc
                seqlen_k_copy_0_copy_0 = seqlen_k_copy_0_copy
                q_blk_copy_0 = q_blk_copy
                v_1_copy_0 = v_1_copy
                v_0_copy_0_copy_0 = v_0_copy_0_copy
                m_i_copy_0 = m_i_copy
                l_i_copy_0 = l_i_copy
                acc_copy_0 = acc_copy
                # src[helion_kernels.py:549]: tile_block.begin * page_size + hl.arange(page_size)
                mul = 16 * offset_4
                iota = tl.arange(0, 16)
                v_3 = tl.cast(mul, tl.int32)
                v_4 = iota + v_3
                # src[helion_kernels.py:551]: valid_n = key_positions < seqlen_k
                v_5 = v_4 < seqlen_k_copy_0_copy_0
                # src[helion_kernels.py:553]: physical_block = block_table[b, logical_block]
                physical_block = tl.load(block_table + (offset_0 * block_table_stride_0 + offset_4 * block_table_stride_1), None)
                # src[helion_kernels.py:557]: extra_mask=valid_n[:, None],
                subscript_1 = v_5[:, None]
                # src[helion_kernels.py:554]: k_page = hl.load(
                # src[helion_kernels.py:555]:     k,
                # src[helion_kernels.py:556]:     [physical_block, slice(None), h_kv, slice(None)],
                # src[helion_kernels.py:554-558]: ...
                k_page = tl.load(k + (physical_block[:, None] * k_stride_0 + (0 + indices_5)[:, None] * k_stride_1 + symnode_0 * k_stride_2 + (0 + indices_3)[None, :] * k_stride_3), subscript_1, other=0)
                # src[helion_kernels.py:559]: k_blk = k_page.reshape(page_size, head_dim)
                k_blk = tl.reshape(k_page, [_RDIM_SIZE_5, _RDIM_SIZE_3])
                # src[helion_kernels.py:560]: qk = hl.dot(q_blk, k_blk.T, out_dtype=torch.float32) * qk_scale
                permute = tl.permute(k_blk, [1, 0])
                dot = tl.dot(tl.cast(q_blk_copy_0, tl.bfloat16), tl.cast(permute, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
                v_6 = dot * qk_scale
                # src[helion_kernels.py:561]: score_mask = valid_m[:, None] & valid_n[None, :]
                subscript_2 = v_1_copy_0[:, None]
                subscript_3 = v_5[None, :]
                v_7 = subscript_2 & subscript_3
                # src[helion_kernels.py:563]: causal_bound = tile_m.index + seqlen_k - seqlen_q
                v_8 = indices_2 + seqlen_k_copy_0_copy_0
                v_9 = v_8 - v_0_copy_0_copy_0
                # src[helion_kernels.py:565]: key_positions[None, :] <= causal_bound[:, None]
                subscript_4 = v_4[None, :]
                subscript_5 = v_9[:, None]
                v_10 = subscript_4 <= subscript_5
                # src[helion_kernels.py:564]: score_mask = score_mask & (
                # src[helion_kernels.py:565]:     key_positions[None, :] <= causal_bound[:, None]
                # src[helion_kernels.py:566]: )
                v_11 = v_7 & v_10
                # src[helion_kernels.py:567]: qk = torch.where(score_mask, qk, float("-inf"))
                scalar_tensor = tl.full([], float('-inf'), tl.float32)
                qk_1 = tl.where(v_11, v_6, scalar_tensor)
                # src[helion_kernels.py:568]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
                amax = tl.cast(tl.max(qk_1, 1), tl.float32)
                v_12 = tl.maximum(m_i_copy_0, amax, tl.PropagateNan.ALL)
                # src[helion_kernels.py:569]: has_key = m_ij != float("-inf")
                v_13 = tl.full([], float('-inf'), tl.float32)
                v_14 = v_12 != v_13
                # src[helion_kernels.py:571]: torch.where(score_mask, qk - m_ij[:, None], float("-inf"))
                subscript_6 = v_12[:, None]
                v_15 = qk_1 - subscript_6
                scalar_tensor_1 = tl.full([], float('-inf'), tl.float32)
                where_1 = tl.where(v_11, v_15, scalar_tensor_1)
                # src[helion_kernels.py:570]: p = torch.exp2(
                # src[helion_kernels.py:571]:     torch.where(score_mask, qk - m_ij[:, None], float("-inf"))
                # src[helion_kernels.py:572]: )
                v_16 = libdevice.exp2(where_1)
                # src[helion_kernels.py:575]: torch.exp2(m_i - m_ij),
                v_17 = m_i_copy_0 - v_12
                v_18 = libdevice.exp2(v_17)
                # src[helion_kernels.py:573]: alpha = torch.where(
                # src[helion_kernels.py:574]:     has_key,
                # src[helion_kernels.py:575]:     torch.exp2(m_i - m_ij),
                # src[helion_kernels.py:573-577]: ...
                scalar_tensor_2 = tl.full([], 1.0, tl.float32)
                alpha = tl.where(v_14, v_18, scalar_tensor_2)
                # src[helion_kernels.py:578]: l_i = l_i * alpha + torch.sum(p, -1)
                v_19 = l_i_copy_0 * alpha
                sum_1 = tl.cast(tl.sum(v_16, 1), tl.float32)
                l_i = v_19 + sum_1
                # src[helion_kernels.py:579]: acc = acc * alpha[:, None]
                subscript_7 = alpha[:, None]
                v_21 = acc_copy_0 * subscript_7
                # src[helion_kernels.py:583]: extra_mask=valid_n[:, None],
                subscript_8 = v_5[:, None]
                # src[helion_kernels.py:580]: v_page = hl.load(
                # src[helion_kernels.py:581]:     v,
                # src[helion_kernels.py:582]:     [physical_block, slice(None), h_kv, slice(None)],
                # src[helion_kernels.py:580-584]: ...
                v_page = tl.load(v + (physical_block[:, None] * v_stride_0 + (0 + indices_5)[:, None] * v_stride_1 + symnode_0 * v_stride_2 + (0 + indices_3)[None, :] * v_stride_3), subscript_8, other=0)
                # src[helion_kernels.py:585]: v_blk = v_page.reshape(page_size, head_dim)
                v_blk = tl.reshape(v_page, [_RDIM_SIZE_5, _RDIM_SIZE_3])
                # src[helion_kernels.py:586]: acc = hl.dot(p.to(v_blk.dtype), v_blk, acc=acc)
                v_22 = tl.cast(v_16, tl.bfloat16)
                acc = tl.dot(tl.cast(v_22, tl.bfloat16), tl.cast(v_blk, tl.bfloat16), acc=v_21, input_precision='tf32', out_dtype=tl.float32)
                # src[helion_kernels.py:587]: m_i = m_ij
                m_i = v_12
            # src[helion_kernels.py:589]: (l_i > 0)[:, None],
            v_23 = tl.full([], 0.0, tl.float32)
            v_24 = l_i > v_23
            subscript_9 = v_24[:, None]
            # src[helion_kernels.py:590]: acc / torch.where(l_i > 0, l_i, 1.0)[:, None],
            v_25 = tl.full([], 0.0, tl.float32)
            v_26 = l_i > v_25
            scalar_tensor_3 = tl.full([], 1.0, tl.float32)
            where = tl.where(v_26, l_i, scalar_tensor_3)
            subscript_10 = where[:, None]
            v_27 = acc / subscript_10
            # src[helion_kernels.py:588]: result = torch.where(
            # src[helion_kernels.py:589]:     (l_i > 0)[:, None],
            # src[helion_kernels.py:590]:     acc / torch.where(l_i > 0, l_i, 1.0)[:, None],
            # src[helion_kernels.py:588-592]: ...
            scalar_tensor_4 = tl.full([], 0.0, tl.float32)
            result = tl.where(subscript_9, v_27, scalar_tensor_4)
            # src[helion_kernels.py:596]: result.to(out.dtype),
            v_28 = tl.cast(result, tl.bfloat16)
            # src[helion_kernels.py:597]: extra_mask=valid_m[:, None],
            subscript_11 = v_1[:, None]
            # src[helion_kernels.py:593]: hl.store(
            # src[helion_kernels.py:594]:     out,
            # src[helion_kernels.py:595]:     [q_index, h, slice(None)],
            # src[helion_kernels.py:593-598]: ...
            tl.store(out + (v_2[:, None] * out_stride_0 + offset_1 * out_stride_1 + (0 + indices_3)[None, :] * out_stride_2), v_28, subscript_11)

def attention_paged(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, cu_seqlens_q: torch.Tensor, seqused_k: torch.Tensor, block_table: torch.Tensor, max_seqlen_q, max_seqlen_k, sm_scale: float, causal, *, _launcher=_default_launcher):
    """Attention over packed queries and a block-table-addressed paged KV cache.

    Query token totals, physical cache allocation, block-table strides, and
    per-request cache lengths remain dynamic.  The generated specialization
    fixes the batch, maximum lengths, head geometry, page size, dtype, and
    masking mode.  Logical key positions are translated through ``block_table``
    before every K/V load, so physical pages need not be contiguous or ordered.
    """
    # src[helion_kernels.py:523]: out = torch.empty_like(q)
    out = torch.empty_like(q)
    # src[helion_kernels.py:524]: qk_scale = sm_scale * 1.44269504088896340736
    qk_scale = sm_scale * 1.4426950408889634
    # src[helion_kernels.py:526]: for b, h in hl.grid([batch, nheads_q]):
    _NUM_SM = get_num_sm(q.device)
    _RDIM_SIZE_3 = 128
    _RDIM_SIZE_5 = 16
    # src[helion_kernels.py:526]: for b, h in hl.grid([batch, nheads_q]):
    # src[helion_kernels.py:527]:     h_kv = h // group
    # src[helion_kernels.py:528]:     q_start = cu_seqlens_q[b]
    # src[helion_kernels.py:526-598]: ...
    _launcher(_helion_paged_attention_thd, (_NUM_SM,), cu_seqlens_q, seqused_k, q, block_table, k, v, out, block_table.stride(0), block_table.stride(1), cu_seqlens_q.stride(0), k.stride(0), k.stride(1), k.stride(2), k.stride(3), out.stride(0), out.stride(1), out.stride(2), q.stride(0), q.stride(1), q.stride(2), seqused_k.stride(0), v.stride(0), v.stride(1), v.stride(2), v.stride(3), qk_scale, _NUM_SM, _RDIM_SIZE_3, _RDIM_SIZE_5, num_warps=4, num_stages=5)
    # src[helion_kernels.py:599]: return out
    return out
