"""Generated by Helion, checked in as plain Triton. Do not edit by hand.

Regenerate with:
    python tools/generate.py --batch 8 --seqlen 512 --nheads 16 --head-dim 64 --dtype bf16 --causal --varlen

varlen batch=8 seqlen_q=512 seqlen_k=512 nheads=16 head_dim=64 dtype=bf16 causal=True

Autotuning provenance:
    Helion version: 1.4.0
    Config selection: autotuned
    Autotuning wall time: 112.206 s
    Measured time: 0.059728 ms
    Config: helion.Config(atomic_indexing=[], block_sizes=[128, 128], indexing=['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer'], l2_groupings=[1], load_eviction_policies=['', '', '', '', 'last', '', ''], loop_orders=[[0, 1]], num_stages=2, num_warps=8, pid_type='flat', range_flattens=[None, None, None], range_multi_buffers=[None, None, None], range_num_stages=[0, 0, 0], range_unroll_factors=[0, 0, 0], range_warp_specializes=[])
"""

from __future__ import annotations

KERNEL_SPEC = {
    'key': 'varlen_b8_sq512_sk512_hq16_hkv16_d64_bf16_causal',
    'batch': 8,
    'seqlen_q': 512,
    'seqlen_k': 512,
    'nheads_q': 16,
    'nheads_kv': 16,
    'head_dim': 64,
    'dtype': 'bf16',
    'causal': True,
    'backward': False,
    'varlen': True,
}


import torch
import triton
import triton.language as tl
from torch._inductor.runtime.triton_compat import libdevice
from .._launcher import default_launcher as _default_launcher
from .._runtime import get_num_sm
from .._runtime import set_triton_allocator

_BLOCK_SIZE_2 = tl.constexpr(128)
_BLOCK_SIZE_4 = tl.constexpr(128)

@triton.jit
def _helion_varlen_attention_thd(cu_seqlens_q, cu_seqlens_k, q, k, v, out, cu_seqlens_k_stride_0, cu_seqlens_q_stride_0, k_stride_0, k_stride_1, k_stride_2, out_stride_0, out_stride_1, out_stride_2, q_stride_0, q_stride_1, q_stride_2, v_stride_0, v_stride_1, v_stride_2, qk_scale, _RDIM_SIZE_3: tl.constexpr):
    # src[helion_kernels.py:521]: for b, h in hl.grid([batch, nheads_q]):
    num_blocks_0 = 8
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0
    offset_0 = pid_0
    offset_1 = pid_1
    indices_3 = tl.arange(0, _RDIM_SIZE_3).to(tl.int32)
    # src[helion_kernels.py:523]: q_start = cu_seqlens_q[b]
    q_start = tl.load(cu_seqlens_q + offset_0 * cu_seqlens_q_stride_0, None)
    # src[helion_kernels.py:524]: q_end = cu_seqlens_q[b + 1]
    add = 1 + offset_0
    q_end = tl.load(cu_seqlens_q + add * cu_seqlens_q_stride_0, None)
    # src[helion_kernels.py:525]: k_start = cu_seqlens_k[b]
    k_start = tl.load(cu_seqlens_k + offset_0 * cu_seqlens_k_stride_0, None)
    # src[helion_kernels.py:526]: k_end = cu_seqlens_k[b + 1]
    k_end = tl.load(cu_seqlens_k + add * cu_seqlens_k_stride_0, None)
    # src[helion_kernels.py:527]: seqlen_q = q_end - q_start
    v_0 = q_end - q_start
    # src[helion_kernels.py:528]: seqlen_k = k_end - k_start
    v_1 = k_end - k_start
    # src[helion_kernels.py:529]: for tile_m in hl.tile(max_q):
    # src[helion_kernels.py:530]:     valid_m = tile_m.index < seqlen_q
    # src[helion_kernels.py:531]:     q_index = q_start + tile_m.index
    # src[helion_kernels.py:529-585]: ...
    for offset_2 in tl.range(0, 512, _BLOCK_SIZE_2):
        indices_2 = offset_2 + tl.arange(0, _BLOCK_SIZE_2).to(tl.int32)
        v_0_copy = v_0
        q_start_copy = q_start
        v_1_copy = v_1
        k_start_copy = k_start
        v_0_copy_0 = v_0_copy
        q_start_copy_0 = q_start_copy
        v_1_copy_0 = v_1_copy
        k_start_copy_0 = k_start_copy
        # src[helion_kernels.py:530]: valid_m = tile_m.index < seqlen_q
        v_2 = indices_2 < v_0_copy_0
        # src[helion_kernels.py:531]: q_index = q_start + tile_m.index
        v_3 = q_start_copy_0 + indices_2
        # src[helion_kernels.py:535]: extra_mask=valid_m[:, None],
        subscript = v_2[:, None]
        # src[helion_kernels.py:532]: q_blk = hl.load(
        # src[helion_kernels.py:533]:     q,
        # src[helion_kernels.py:534]:     [q_index, h, slice(None)],
        # src[helion_kernels.py:532-536]: ...
        q_blk = tl.load(q + (v_3[:, None] * q_stride_0 + offset_1 * q_stride_1 + (0 + indices_3)[None, :] * q_stride_2), subscript, other=0, eviction_policy='evict_last')
        # src[helion_kernels.py:537]: m_i = hl.full([tile_m], float("-inf"), dtype=torch.float32)
        m_i = tl.full([_BLOCK_SIZE_2], float('-inf'), tl.float32)
        # src[helion_kernels.py:538]: l_i = hl.zeros([tile_m], dtype=torch.float32)
        l_i = tl.full([_BLOCK_SIZE_2], 0.0, tl.float32)
        # src[helion_kernels.py:539]: acc = hl.zeros([tile_m, head_dim], dtype=torch.float32)
        acc = tl.full([_BLOCK_SIZE_2, _RDIM_SIZE_3], 0.0, tl.float32)
        # src[helion_kernels.py:540]: for tile_n in hl.tile(max_k):
        # src[helion_kernels.py:541]:     valid_n = tile_n.index < seqlen_k
        # src[helion_kernels.py:542]:     k_index = k_start + tile_n.index
        # src[helion_kernels.py:540-574]: ...
        for offset_4 in tl.range(0, 512, _BLOCK_SIZE_4):
            indices_4 = offset_4 + tl.arange(0, _BLOCK_SIZE_4).to(tl.int32)
            v_1_copy_0_copy = v_1_copy_0
            k_start_copy_0_copy = k_start_copy_0
            q_blk_copy = q_blk
            v_2_copy = v_2
            v_0_copy_0_copy = v_0_copy_0
            m_i_copy = m_i
            l_i_copy = l_i
            acc_copy = acc
            v_1_copy_0_copy_0 = v_1_copy_0_copy
            k_start_copy_0_copy_0 = k_start_copy_0_copy
            q_blk_copy_0 = q_blk_copy
            v_2_copy_0 = v_2_copy
            v_0_copy_0_copy_0 = v_0_copy_0_copy
            m_i_copy_0 = m_i_copy
            l_i_copy_0 = l_i_copy
            acc_copy_0 = acc_copy
            # src[helion_kernels.py:541]: valid_n = tile_n.index < seqlen_k
            v_4 = indices_4 < v_1_copy_0_copy_0
            # src[helion_kernels.py:542]: k_index = k_start + tile_n.index
            v_5 = k_start_copy_0_copy_0 + indices_4
            # src[helion_kernels.py:546]: extra_mask=valid_n[:, None],
            subscript_1 = v_4[:, None]
            # src[helion_kernels.py:543]: k_blk = hl.load(
            # src[helion_kernels.py:544]:     k,
            # src[helion_kernels.py:545]:     [k_index, h_kv, slice(None)],
            # src[helion_kernels.py:543-547]: ...
            k_blk = tl.load(k + (v_5[:, None] * k_stride_0 + offset_1 * k_stride_1 + (0 + indices_3)[None, :] * k_stride_2), subscript_1, other=0)
            # src[helion_kernels.py:548]: qk = hl.dot(q_blk, k_blk.T, out_dtype=torch.float32) * qk_scale
            permute = tl.permute(k_blk, [1, 0])
            dot = tl.dot(tl.cast(q_blk_copy_0, tl.bfloat16), tl.cast(permute, tl.bfloat16), input_precision='tf32', out_dtype=tl.float32)
            v_6 = dot * qk_scale
            # src[helion_kernels.py:549]: score_mask = valid_m[:, None] & valid_n[None, :]
            subscript_2 = v_2_copy_0[:, None]
            subscript_3 = v_4[None, :]
            v_7 = subscript_2 & subscript_3
            # src[helion_kernels.py:551]: causal_bound = tile_m.index + seqlen_k - seqlen_q
            v_8 = indices_2 + v_1_copy_0_copy_0
            v_9 = v_8 - v_0_copy_0_copy_0
            # src[helion_kernels.py:553]: tile_n.index[None, :] <= causal_bound[:, None]
            subscript_4 = indices_4[None, :]
            subscript_5 = v_9[:, None]
            v_10 = subscript_4 <= subscript_5
            # src[helion_kernels.py:552]: score_mask = score_mask & (
            # src[helion_kernels.py:553]:     tile_n.index[None, :] <= causal_bound[:, None]
            # src[helion_kernels.py:554]: )
            v_11 = v_7 & v_10
            # src[helion_kernels.py:555]: qk = torch.where(score_mask, qk, float("-inf"))
            scalar_tensor = tl.full([], float('-inf'), tl.float32)
            qk_1 = tl.where(v_11, v_6, scalar_tensor)
            # src[helion_kernels.py:556]: m_ij = torch.maximum(m_i, torch.amax(qk, -1))
            amax = tl.cast(tl.max(qk_1, 1), tl.float32)
            v_12 = tl.maximum(m_i_copy_0, amax, tl.PropagateNan.ALL)
            # src[helion_kernels.py:557]: has_key = m_ij != float("-inf")
            v_13 = tl.full([], float('-inf'), tl.float32)
            v_14 = v_12 != v_13
            # src[helion_kernels.py:559]: torch.where(score_mask, qk - m_ij[:, None], float("-inf"))
            subscript_6 = v_12[:, None]
            v_15 = qk_1 - subscript_6
            scalar_tensor_1 = tl.full([], float('-inf'), tl.float32)
            where_1 = tl.where(v_11, v_15, scalar_tensor_1)
            # src[helion_kernels.py:558]: p = torch.exp2(
            # src[helion_kernels.py:559]:     torch.where(score_mask, qk - m_ij[:, None], float("-inf"))
            # src[helion_kernels.py:560]: )
            v_16 = libdevice.exp2(where_1)
            # src[helion_kernels.py:563]: torch.exp2(m_i - m_ij),
            v_17 = m_i_copy_0 - v_12
            v_18 = libdevice.exp2(v_17)
            # src[helion_kernels.py:561]: alpha = torch.where(
            # src[helion_kernels.py:562]:     has_key,
            # src[helion_kernels.py:563]:     torch.exp2(m_i - m_ij),
            # src[helion_kernels.py:561-565]: ...
            scalar_tensor_2 = tl.full([], 1.0, tl.float32)
            alpha = tl.where(v_14, v_18, scalar_tensor_2)
            # src[helion_kernels.py:566]: l_i = l_i * alpha + torch.sum(p, -1)
            v_19 = l_i_copy_0 * alpha
            sum_1 = tl.cast(tl.sum(v_16, 1), tl.float32)
            l_i = v_19 + sum_1
            # src[helion_kernels.py:567]: acc = acc * alpha[:, None]
            subscript_7 = alpha[:, None]
            v_21 = acc_copy_0 * subscript_7
            # src[helion_kernels.py:571]: extra_mask=valid_n[:, None],
            subscript_8 = v_4[:, None]
            # src[helion_kernels.py:568]: v_blk = hl.load(
            # src[helion_kernels.py:569]:     v,
            # src[helion_kernels.py:570]:     [k_index, h_kv, slice(None)],
            # src[helion_kernels.py:568-572]: ...
            v_blk = tl.load(v + (v_5[:, None] * v_stride_0 + offset_1 * v_stride_1 + (0 + indices_3)[None, :] * v_stride_2), subscript_8, other=0)
            # src[helion_kernels.py:573]: acc = hl.dot(p.to(v_blk.dtype), v_blk, acc=acc)
            v_22 = tl.cast(v_16, tl.bfloat16)
            acc = tl.dot(tl.cast(v_22, tl.bfloat16), tl.cast(v_blk, tl.bfloat16), acc=v_21, input_precision='tf32', out_dtype=tl.float32)
            # src[helion_kernels.py:574]: m_i = m_ij
            m_i = v_12
        # src[helion_kernels.py:576]: (l_i > 0)[:, None],
        v_23 = tl.full([], 0.0, tl.float32)
        v_24 = l_i > v_23
        subscript_9 = v_24[:, None]
        # src[helion_kernels.py:577]: acc / torch.where(l_i > 0, l_i, 1.0)[:, None],
        v_25 = tl.full([], 0.0, tl.float32)
        v_26 = l_i > v_25
        scalar_tensor_3 = tl.full([], 1.0, tl.float32)
        where = tl.where(v_26, l_i, scalar_tensor_3)
        subscript_10 = where[:, None]
        v_27 = acc / subscript_10
        # src[helion_kernels.py:575]: result = torch.where(
        # src[helion_kernels.py:576]:     (l_i > 0)[:, None],
        # src[helion_kernels.py:577]:     acc / torch.where(l_i > 0, l_i, 1.0)[:, None],
        # src[helion_kernels.py:575-579]: ...
        scalar_tensor_4 = tl.full([], 0.0, tl.float32)
        result = tl.where(subscript_9, v_27, scalar_tensor_4)
        # src[helion_kernels.py:583]: result.to(out.dtype),
        v_28 = tl.cast(result, tl.bfloat16)
        # src[helion_kernels.py:584]: extra_mask=valid_m[:, None],
        subscript_11 = v_2[:, None]
        # src[helion_kernels.py:580]: hl.store(
        # src[helion_kernels.py:581]:     out,
        # src[helion_kernels.py:582]:     [q_index, h, slice(None)],
        # src[helion_kernels.py:580-585]: ...
        tl.store(out + (v_3[:, None] * out_stride_0 + offset_1 * out_stride_1 + (0 + indices_3)[None, :] * out_stride_2), v_28, subscript_11)

def attention_varlen(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, cu_seqlens_q: torch.Tensor, cu_seqlens_k: torch.Tensor, max_seqlen_q, max_seqlen_k, sm_scale: float, causal, *, _launcher=_default_launcher):
    """Attention over FlashAttention's packed ``[total, heads, dim]`` layout.

    The first tensor dimension is deliberately dynamic.  The batch size,
    maximum sequence lengths, head counts, head dimension, and masking mode
    remain compile-time specializations, while each invocation reads the
    actual per-sequence bounds from the two device-resident cumulative-length
    arrays.
    """
    # src[helion_kernels.py:518]: out = torch.empty_like(q)
    out = torch.empty_like(q)
    # src[helion_kernels.py:519]: qk_scale = sm_scale * 1.44269504088896340736
    qk_scale = sm_scale * 1.4426950408889634
    # src[helion_kernels.py:521]: for b, h in hl.grid([batch, nheads_q]):
    _RDIM_SIZE_3 = 64
    # src[helion_kernels.py:521]: for b, h in hl.grid([batch, nheads_q]):
    # src[helion_kernels.py:522]:     h_kv = h // group
    # src[helion_kernels.py:523]:     q_start = cu_seqlens_q[b]
    # src[helion_kernels.py:521-585]: ...
    _launcher(_helion_varlen_attention_thd, (8 * 16,), cu_seqlens_q, cu_seqlens_k, q, k, v, out, cu_seqlens_k.stride(0), cu_seqlens_q.stride(0), k.stride(0), k.stride(1), k.stride(2), out.stride(0), out.stride(1), out.stride(2), q.stride(0), q.stride(1), q.stride(2), v.stride(0), v.stride(1), v.stride(2), qk_scale, _RDIM_SIZE_3, num_warps=8, num_stages=2)
    # src[helion_kernels.py:586]: return out
    return out